// Code generated by scripts/gen_email_templates. DO NOT EDIT.
//
// This file defines every transactional email template published on Kibamail
// for the HiveLoop app, along with the Handlebars variables each template expects.
//
// Every template is sent via POST /v1/emails/send using the slug as template.id.
// The variable `business_address` is resolved by Kibamail from workspace
// settings and never passed per-send.

package email

// TemplateSlug is the Kibamail unique slug for a transactional email template.
type TemplateSlug string

// Variables a template expects at send time. Every value MUST be a non-empty
// string — the render step fails loudly on missing keys.
type TemplateVars = map[string]string

const (
	// --- Authentication ---
	TmplAuthAccountDeleted  TemplateSlug = "auth-account-deleted"
	TmplAuthConfirmEmail    TemplateSlug = "auth-confirm-email"
	TmplAuthEmailChanged    TemplateSlug = "auth-email-changed"
	TmplAuthNewSignin       TemplateSlug = "auth-new-signin"
	TmplAuthOtpLogin        TemplateSlug = "auth-otp-login"
	TmplAuthPasswordChanged TemplateSlug = "auth-password-changed"
	TmplAuthPasswordReset   TemplateSlug = "auth-password-reset"
	TmplAuthWelcome         TemplateSlug = "auth-welcome"

	// --- Organization ---
	TmplOrgInvite         TemplateSlug = "org-invite"
	TmplOrgInviteAccepted TemplateSlug = "org-invite-accepted"
	TmplOrgMemberRemoved  TemplateSlug = "org-member-removed"
	TmplOrgRoleChanged    TemplateSlug = "org-role-changed"

	// --- Billing & Subscriptions ---
	TmplBillingOverageStarted       TemplateSlug = "billing-overage-started"
	TmplBillingPaymentFailed        TemplateSlug = "billing-payment-failed"
	TmplBillingPlanChanged          TemplateSlug = "billing-plan-changed"
	TmplBillingReceipt              TemplateSlug = "billing-receipt"
	TmplBillingRenewalReminder      TemplateSlug = "billing-renewal-reminder"
	TmplBillingSandboxChanged       TemplateSlug = "billing-sandbox-changed"
	TmplBillingSubscriptionActive   TemplateSlug = "billing-subscription-active"
	TmplBillingSubscriptionCanceled TemplateSlug = "billing-subscription-canceled"
	TmplBillingSubscriptionRevoked  TemplateSlug = "billing-subscription-revoked"
	TmplBillingUsage80              TemplateSlug = "billing-usage-80"

	// --- Agent Runs & Activity ---
	TmplAgentsApprovalRequired TemplateSlug = "agents-approval-required"
	TmplAgentsApprovalTimeout  TemplateSlug = "agents-approval-timeout"
	TmplAgentsAutoDisabled     TemplateSlug = "agents-auto-disabled"
	TmplAgentsPingReminder     TemplateSlug = "agents-ping-reminder"
	TmplAgentsRunDigest        TemplateSlug = "agents-run-digest"
	TmplAgentsRunError         TemplateSlug = "agents-run-error"
	TmplAgentsRunFailed        TemplateSlug = "agents-run-failed"

	// --- Triggers ---
	TmplTriggersFirstEvent     TemplateSlug = "triggers-first-event"
	TmplTriggersSilent         TemplateSlug = "triggers-silent"
	TmplTriggersWebhookFailing TemplateSlug = "triggers-webhook-failing"

	// --- Integrations ---
	TmplIntegrationsMisconfigured TemplateSlug = "integrations-misconfigured"
	TmplIntegrationsReauth        TemplateSlug = "integrations-reauth"
	TmplIntegrationsRevoked       TemplateSlug = "integrations-revoked"

	// --- LLM & Proxy ---
	TmplLlmCredentialInvalid TemplateSlug = "llm-credential-invalid"
	TmplLlmMonthlyCost       TemplateSlug = "llm-monthly-cost"
	TmplLlmRateLimited       TemplateSlug = "llm-rate-limited"
	TmplLlmSpendSpike        TemplateSlug = "llm-spend-spike"

	// --- API Keys ---
	TmplApiKeyCreated    TemplateSlug = "api-key-created"
	TmplApiKeyExpiring   TemplateSlug = "api-key-expiring"
	TmplApiKeyFirstUsed  TemplateSlug = "api-key-first-used"
	TmplApiKeyRevoked    TemplateSlug = "api-key-revoked"
	TmplApiKeySuspicious TemplateSlug = "api-key-suspicious"

	// --- Custom Domains ---
	TmplDomainCertRenewalFailed  TemplateSlug = "domain-cert-renewal-failed"
	TmplDomainVerificationFailed TemplateSlug = "domain-verification-failed"
	TmplDomainVerified           TemplateSlug = "domain-verified"

	// --- Sandbox Templates ---
	TmplSandboxTemplateBuilt  TemplateSlug = "sandbox-template-built"
	TmplSandboxTemplateFailed TemplateSlug = "sandbox-template-failed"

	// --- Storage & Memory ---
	TmplStorageMemory90      TemplateSlug = "storage-memory-90"
	TmplStorageWorkspaceFull TemplateSlug = "storage-workspace-full"

	// --- Marketplace ---
	TmplMarketplaceDeprecated       TemplateSlug = "marketplace-deprecated"
	TmplMarketplaceEarnings         TemplateSlug = "marketplace-earnings"
	TmplMarketplaceInstallMilestone TemplateSlug = "marketplace-install-milestone"
	TmplMarketplaceInstalled        TemplateSlug = "marketplace-installed"
	TmplMarketplacePayout           TemplateSlug = "marketplace-payout"
	TmplMarketplacePublished        TemplateSlug = "marketplace-published"
	TmplMarketplaceRejected         TemplateSlug = "marketplace-rejected"
	TmplMarketplaceSubmitted        TemplateSlug = "marketplace-submitted"
	TmplMarketplaceUpdated          TemplateSlug = "marketplace-updated"
	TmplMarketplaceVerified         TemplateSlug = "marketplace-verified"

	// --- Platform ---
	TmplPlatformIncident    TemplateSlug = "platform-incident"
	TmplPlatformLegalUpdate TemplateSlug = "platform-legal-update"
	TmplPlatformMaintenance TemplateSlug = "platform-maintenance"
	TmplPlatformModeration  TemplateSlug = "platform-moderation"
)

// templateVars lists the variables each template expects at send time, in
// documentation order. `business_address` is resolved server-side by Kibamail.
var templateVars = map[TemplateSlug][]string{
	// Authentication
	TmplAuthAccountDeleted:  {"deletedAt", "firstName"},
	TmplAuthConfirmEmail:    {"confirmationUrl", "email", "expiresIn", "firstName"},
	TmplAuthEmailChanged:    {"changedAt", "firstName", "newEmail", "oldEmail"},
	TmplAuthNewSignin:       {"device", "firstName", "ip", "location", "signedInAt"},
	TmplAuthOtpLogin:        {"code", "email", "expiresIn"},
	TmplAuthPasswordChanged: {"changedAt", "firstName"},
	TmplAuthPasswordReset:   {"expiresIn", "firstName", "resetUrl"},
	TmplAuthWelcome:         {"firstName"},

	// Organization
	TmplOrgInvite:         {"expiresIn", "firstName", "inviteUrl", "inviterName", "orgName", "role"},
	TmplOrgInviteAccepted: {"adminFirstName", "invitedEmail", "invitedName", "orgName", "role"},
	TmplOrgMemberRemoved:  {"firstName", "orgName", "removedBy"},
	TmplOrgRoleChanged:    {"changedBy", "firstName", "newRole", "oldRole", "orgName"},

	// Billing & Subscriptions
	TmplBillingOverageStarted:       {"agentName", "costPerRun", "firstName", "periodEnd"},
	TmplBillingPaymentFailed:        {"amount", "firstName", "nextRetryDate", "plan", "updatePaymentUrl"},
	TmplBillingPlanChanged:          {"effectiveDate", "firstName", "newPlan", "oldPlan"},
	TmplBillingReceipt:              {"amount", "currency", "firstName", "invoiceNumber", "invoiceUrl", "paidAt"},
	TmplBillingRenewalReminder:      {"amount", "firstName", "plan", "renewalDate"},
	TmplBillingSandboxChanged:       {"action", "agentName", "firstName", "monthlyCost"},
	TmplBillingSubscriptionActive:   {"agentCount", "amount", "currency", "firstName", "periodEnd", "plan"},
	TmplBillingSubscriptionCanceled: {"firstName", "periodEnd", "plan"},
	TmplBillingSubscriptionRevoked:  {"firstName", "plan"},
	TmplBillingUsage80:              {"agentName", "firstName", "included", "used"},

	// Agent Runs & Activity
	TmplAgentsApprovalRequired: {"agentName", "approveUrl", "denyUrl", "firstName", "toolName", "toolSummary"},
	TmplAgentsApprovalTimeout:  {"agentName", "firstName", "timeoutMinutes", "toolName"},
	TmplAgentsAutoDisabled:     {"agentName", "disabledAt", "firstName", "reason"},
	TmplAgentsPingReminder:     {"agentName", "firstName", "message", "scheduledFor"},
	TmplAgentsRunDigest:        {"cost", "errors", "firstName", "period", "runs", "topAgentName", "topAgentRuns"},
	TmplAgentsRunError:         {"agentName", "errorSummary", "erroredAt", "firstName", "runId"},
	TmplAgentsRunFailed:        {"agentName", "errorSummary", "failedAt", "firstName", "runId"},

	// Triggers
	TmplTriggersFirstEvent:     {"agentName", "firstName", "triggerName"},
	TmplTriggersSilent:         {"agentName", "daysSince", "firstName", "triggerName"},
	TmplTriggersWebhookFailing: {"agentName", "failureRate", "firstName", "integration", "lastError"},

	// Integrations
	TmplIntegrationsMisconfigured: {"agentName", "firstName", "integration"},
	TmplIntegrationsReauth:        {"firstName", "integration"},
	TmplIntegrationsRevoked:       {"firstName", "integration", "revokedAt"},

	// LLM & Proxy
	TmplLlmCredentialInvalid: {"credentialName", "firstName", "provider"},
	TmplLlmMonthlyCost:       {"agentCount", "firstName", "month", "topAgentCost", "topAgentName", "totalAmount"},
	TmplLlmRateLimited:       {"firstName", "provider", "windowMinutes"},
	TmplLlmSpendSpike:        {"amount", "baselineAmount", "firstName", "windowHours"},

	// API Keys
	TmplApiKeyCreated:    {"createdAt", "createdFromIp", "firstName", "keyName", "keyPrefix"},
	TmplApiKeyExpiring:   {"daysRemaining", "expiresAt", "firstName", "keyName"},
	TmplApiKeyFirstUsed:  {"firstName", "keyName", "usedAt", "usedFromIp"},
	TmplApiKeyRevoked:    {"firstName", "keyName", "revokedAt", "revokedBy"},
	TmplApiKeySuspicious: {"firstName", "keyName", "reason", "suspiciousIp"},

	// Custom Domains
	TmplDomainCertRenewalFailed:  {"domain", "expiresAt", "firstName", "reason"},
	TmplDomainVerificationFailed: {"domain", "firstName", "reason"},
	TmplDomainVerified:           {"domain", "firstName", "verifiedAt"},

	// Sandbox Templates
	TmplSandboxTemplateBuilt:  {"builtAt", "firstName", "sizeMb", "templateName"},
	TmplSandboxTemplateFailed: {"errorSummary", "firstName", "logsUrl", "templateName"},

	// Storage & Memory
	TmplStorageMemory90:      {"agentName", "firstName", "limitMb", "usedMb"},
	TmplStorageWorkspaceFull: {"firstName", "limitGb", "usedGb"},

	// Marketplace
	TmplMarketplaceDeprecated:       {"agentName", "firstName", "publisherName", "recommendedAlternative"},
	TmplMarketplaceEarnings:         {"amount", "firstName", "installCount", "month", "topAgentName"},
	TmplMarketplaceInstallMilestone: {"agentName", "firstName", "installCount", "marketplaceUrl", "milestone"},
	TmplMarketplaceInstalled:        {"agentName", "firstName", "orgName", "publisherName"},
	TmplMarketplacePayout:           {"amount", "currency", "firstName", "paidAt", "period"},
	TmplMarketplacePublished:        {"agentName", "firstName", "marketplaceUrl", "publishedAt"},
	TmplMarketplaceRejected:         {"agentName", "firstName", "reason", "reviewerNote"},
	TmplMarketplaceSubmitted:        {"agentName", "firstName", "submittedAt"},
	TmplMarketplaceUpdated:          {"agentName", "changelogSummary", "firstName", "newVersion", "oldVersion"},
	TmplMarketplaceVerified:         {"agentName", "firstName", "marketplaceUrl", "verifiedAt"},

	// Platform
	TmplPlatformIncident:    {"firstName", "severity", "startedAt", "summary", "title"},
	TmplPlatformLegalUpdate: {"effectiveDate", "firstName", "privacyUrl", "summary", "termsUrl"},
	TmplPlatformMaintenance: {"details", "endsAt", "firstName", "scope", "startsAt"},
	TmplPlatformModeration:  {"action", "appealUrl", "firstName", "reason"},
}

// templateMeta carries the human-readable name, subject template, and
// description for every slug. Useful for admin UIs, logs, and sanity checks.
type TemplateMeta struct {
	Slug        TemplateSlug
	Name        string
	Subject     string
	Description string
	Variables   []string
}

var templateMeta = map[TemplateSlug]TemplateMeta{
	// Authentication
	TmplAuthAccountDeleted: {
		Slug:        "auth-account-deleted",
		Name:        "Auth — Account deleted",
		Subject:     "Your HiveLoop account has been deleted",
		Description: "Sent when an account is deleted (or scheduled for deletion). Variables: firstName, deletedAt.",
		Variables:   []string{"deletedAt", "firstName"},
	},
	TmplAuthConfirmEmail: {
		Slug:        "auth-confirm-email",
		Name:        "Auth — Confirm email",
		Subject:     "Confirm your email",
		Description: "Sent on signup or email change. Variables: firstName, email, confirmationUrl, expiresIn.",
		Variables:   []string{"confirmationUrl", "email", "expiresIn", "firstName"},
	},
	TmplAuthEmailChanged: {
		Slug:        "auth-email-changed",
		Name:        "Auth — Email changed",
		Subject:     "Your HiveLoop email address was changed",
		Description: "Notification sent to the OLD email when the user changes their email. Variables: firstName, oldEmail, newEmail, changedAt.",
		Variables:   []string{"changedAt", "firstName", "newEmail", "oldEmail"},
	},
	TmplAuthNewSignin: {
		Slug:        "auth-new-signin",
		Name:        "Auth — New sign-in",
		Subject:     "New sign-in to your HiveLoop account",
		Description: "Sent on sign-in from an unrecognized device or IP. Variables: firstName, device, ip, location, signedInAt.",
		Variables:   []string{"device", "firstName", "ip", "location", "signedInAt"},
	},
	TmplAuthOtpLogin: {
		Slug:        "auth-otp-login",
		Name:        "Auth — OTP login code",
		Subject:     "Your HiveLoop login code: {{code}}",
		Description: "Sent when a user requests a passwordless email login. Variables: code, email, expiresIn.",
		Variables:   []string{"code", "email", "expiresIn"},
	},
	TmplAuthPasswordChanged: {
		Slug:        "auth-password-changed",
		Name:        "Auth — Password changed",
		Subject:     "Your HiveLoop password was changed",
		Description: "Sent after a successful password change. Variables: firstName, changedAt.",
		Variables:   []string{"changedAt", "firstName"},
	},
	TmplAuthPasswordReset: {
		Slug:        "auth-password-reset",
		Name:        "Auth — Password reset",
		Subject:     "Reset your HiveLoop password",
		Description: "Sent when user requests a password reset. Variables: firstName, resetUrl, expiresIn.",
		Variables:   []string{"expiresIn", "firstName", "resetUrl"},
	},
	TmplAuthWelcome: {
		Slug:        "auth-welcome",
		Name:        "Auth — Welcome",
		Subject:     "Welcome to HiveLoop, {{firstName}}",
		Description: "Sent once, immediately after a user confirms their email for the first time. Variables: firstName.",
		Variables:   []string{"firstName"},
	},

	// Organization
	TmplOrgInvite: {
		Slug:        "org-invite",
		Name:        "Org — Invitation to join",
		Subject:     "{{inviterName}} invited you to {{orgName}}",
		Description: "Fires when an admin invites a user to an organization. Variables: firstName, inviterName, orgName, role, inviteUrl, expiresIn.",
		Variables:   []string{"expiresIn", "firstName", "inviteUrl", "inviterName", "orgName", "role"},
	},
	TmplOrgInviteAccepted: {
		Slug:        "org-invite-accepted",
		Name:        "Org — Invite accepted",
		Subject:     "{{invitedName}} joined {{orgName}}",
		Description: "Notifies the admin when an invitee accepts their invitation. Variables: adminFirstName, invitedName, invitedEmail, orgName, role.",
		Variables:   []string{"adminFirstName", "invitedEmail", "invitedName", "orgName", "role"},
	},
	TmplOrgMemberRemoved: {
		Slug:        "org-member-removed",
		Name:        "Org — Member removed",
		Subject:     "You've been removed from {{orgName}}",
		Description: "Fires when a member is removed from an organization. Variables: firstName, orgName, removedBy.",
		Variables:   []string{"firstName", "orgName", "removedBy"},
	},
	TmplOrgRoleChanged: {
		Slug:        "org-role-changed",
		Name:        "Org — Role changed",
		Subject:     "Your role in {{orgName}} is now {{newRole}}",
		Description: "Fires when an admin changes a member's role in an organization. Variables: firstName, orgName, oldRole, newRole, changedBy.",
		Variables:   []string{"changedBy", "firstName", "newRole", "oldRole", "orgName"},
	},

	// Billing & Subscriptions
	TmplBillingOverageStarted: {
		Slug:        "billing-overage-started",
		Name:        "Billing — Overage started",
		Subject:     "{{agentName}} is now on overage pricing",
		Description: "Fires on the first overage run for an agent. Vars: firstName, agentName, costPerRun, periodEnd.",
		Variables:   []string{"agentName", "costPerRun", "firstName", "periodEnd"},
	},
	TmplBillingPaymentFailed: {
		Slug:        "billing-payment-failed",
		Name:        "Billing — Payment failed",
		Subject:     "Action required: payment failed for {{plan}}",
		Description: "Fires on Polar subscription.past_due. Vars: firstName, plan, amount, nextRetryDate, updatePaymentUrl.",
		Variables:   []string{"amount", "firstName", "nextRetryDate", "plan", "updatePaymentUrl"},
	},
	TmplBillingPlanChanged: {
		Slug:        "billing-plan-changed",
		Name:        "Billing — Plan changed",
		Subject:     "Your plan changed: {{oldPlan}} → {{newPlan}}",
		Description: "Fires on plan upgrade/downgrade. Vars: firstName, oldPlan, newPlan, effectiveDate.",
		Variables:   []string{"effectiveDate", "firstName", "newPlan", "oldPlan"},
	},
	TmplBillingReceipt: {
		Slug:        "billing-receipt",
		Name:        "Billing — Receipt",
		Subject:     "Receipt {{invoiceNumber}} from HiveLoop",
		Description: "Fires on successful charge. Vars: firstName, invoiceNumber, amount, currency, paidAt, invoiceUrl.",
		Variables:   []string{"amount", "currency", "firstName", "invoiceNumber", "invoiceUrl", "paidAt"},
	},
	TmplBillingRenewalReminder: {
		Slug:        "billing-renewal-reminder",
		Name:        "Billing — Renewal reminder",
		Subject:     "Your {{plan}} plan renews on {{renewalDate}}",
		Description: "Fires 3 days before subscription renewal. Vars: firstName, plan, amount, renewalDate.",
		Variables:   []string{"amount", "firstName", "plan", "renewalDate"},
	},
	TmplBillingSandboxChanged: {
		Slug:        "billing-sandbox-changed",
		Name:        "Billing — Sandbox add-on updated",
		Subject:     "Dedicated sandbox {{action}} for {{agentName}}",
		Description: "Fires when the dedicated sandbox add-on is enabled or removed for an agent. Vars: firstName, agentName, action, monthlyCost.",
		Variables:   []string{"action", "agentName", "firstName", "monthlyCost"},
	},
	TmplBillingSubscriptionActive: {
		Slug:        "billing-subscription-active",
		Name:        "Billing — Subscription active",
		Subject:     "Your HiveLoop {{plan}} plan is active",
		Description: "Fires on Polar subscription.created/active. Vars: firstName, plan, amount, currency, periodEnd, agentCount.",
		Variables:   []string{"agentCount", "amount", "currency", "firstName", "periodEnd", "plan"},
	},
	TmplBillingSubscriptionCanceled: {
		Slug:        "billing-subscription-canceled",
		Name:        "Billing — Subscription canceled",
		Subject:     "Your {{plan}} subscription is canceled",
		Description: "Fires when a subscription is canceled; user keeps access until period end. Vars: firstName, plan, periodEnd.",
		Variables:   []string{"firstName", "periodEnd", "plan"},
	},
	TmplBillingSubscriptionRevoked: {
		Slug:        "billing-subscription-revoked",
		Name:        "Billing — Subscription revoked",
		Subject:     "Your HiveLoop {{plan}} access has ended",
		Description: "Fires when subscription access fully ends. Vars: firstName, plan.",
		Variables:   []string{"firstName", "plan"},
	},
	TmplBillingUsage80: {
		Slug:        "billing-usage-80",
		Name:        "Billing — Usage at 80%",
		Subject:     "{{agentName}} is approaching its monthly run limit",
		Description: "Fires when an agent reaches 80% of included monthly runs. Vars: firstName, agentName, used, included.",
		Variables:   []string{"agentName", "firstName", "included", "used"},
	},

	// Agent Runs & Activity
	TmplAgentsApprovalRequired: {
		Slug:        "agents-approval-required",
		Name:        "Agents — Approval required",
		Subject:     "{{agentName}} is waiting on your approval",
		Description: "Fires when an agent hits a require_approval step and is blocked on a human decision. Variables: firstName, agentName, toolName, toolSummary, approveUrl, denyUrl.",
		Variables:   []string{"agentName", "approveUrl", "denyUrl", "firstName", "toolName", "toolSummary"},
	},
	TmplAgentsApprovalTimeout: {
		Slug:        "agents-approval-timeout",
		Name:        "Agents — Approval timed out",
		Subject:     "{{agentName}}: approval window closed",
		Description: "Fires when a require_approval tool call times out without a human response. Variables: firstName, agentName, toolName, timeoutMinutes.",
		Variables:   []string{"agentName", "firstName", "timeoutMinutes", "toolName"},
	},
	TmplAgentsAutoDisabled: {
		Slug:        "agents-auto-disabled",
		Name:        "Agents — Auto-disabled",
		Subject:     "{{agentName}} was auto-disabled",
		Description: "Fires when an agent is auto-disabled after repeated failures or crossing a budget cap. Variables: firstName, agentName, reason, disabledAt.",
		Variables:   []string{"agentName", "disabledAt", "firstName", "reason"},
	},
	TmplAgentsPingReminder: {
		Slug:        "agents-ping-reminder",
		Name:        "Agents — Ping reminder",
		Subject:     "Reminder from {{agentName}}",
		Description: "Fires when an agent's ping_me_back reminder triggers at its scheduled time. Variables: firstName, agentName, message, scheduledFor.",
		Variables:   []string{"agentName", "firstName", "message", "scheduledFor"},
	},
	TmplAgentsRunDigest: {
		Slug:        "agents-run-digest",
		Name:        "Agents — Run digest",
		Subject:     "Your agent digest for {{period}}",
		Description: "Daily or weekly digest of agent runs across a workspace. Variables: firstName, period, runs, errors, cost, topAgentName, topAgentRuns.",
		Variables:   []string{"cost", "errors", "firstName", "period", "runs", "topAgentName", "topAgentRuns"},
	},
	TmplAgentsRunError: {
		Slug:        "agents-run-error",
		Name:        "Agents — Run errored",
		Subject:     "{{agentName}}: run finished with an error",
		Description: "Fires when an agent run completes its lifecycle but raised an LLM or tool error. Variables: firstName, agentName, runId, errorSummary, erroredAt.",
		Variables:   []string{"agentName", "errorSummary", "erroredAt", "firstName", "runId"},
	},
	TmplAgentsRunFailed: {
		Slug:        "agents-run-failed",
		Name:        "Agents — Run failed",
		Subject:     "{{agentName}}: run failed",
		Description: "Fires when an agent run fails at dispatch. Variables: firstName, agentName, runId, errorSummary, failedAt.",
		Variables:   []string{"agentName", "errorSummary", "failedAt", "firstName", "runId"},
	},

	// Triggers
	TmplTriggersFirstEvent: {
		Slug:        "triggers-first-event",
		Name:        "Triggers — First event received",
		Subject:     "{{agentName}} received its first event",
		Description: "Sent after the first webhook/event is received following trigger setup. Variables: firstName, agentName, triggerName.",
		Variables:   []string{"agentName", "firstName", "triggerName"},
	},
	TmplTriggersSilent: {
		Slug:        "triggers-silent",
		Name:        "Triggers — No events received",
		Subject:     "{{agentName}} hasn't received any events yet",
		Description: "Sent when no events have arrived for N days after trigger setup. Variables: firstName, agentName, triggerName, daysSince.",
		Variables:   []string{"agentName", "daysSince", "firstName", "triggerName"},
	},
	TmplTriggersWebhookFailing: {
		Slug:        "triggers-webhook-failing",
		Name:        "Triggers — Webhook failing",
		Subject:     "{{integration}} webhook is failing for {{agentName}}",
		Description: "Sent when upstream webhook deliveries repeatedly return 4xx/5xx. Variables: firstName, integration, agentName, failureRate, lastError.",
		Variables:   []string{"agentName", "failureRate", "firstName", "integration", "lastError"},
	},

	// Integrations
	TmplIntegrationsMisconfigured: {
		Slug:        "integrations-misconfigured",
		Name:        "Integrations — Setup incomplete",
		Subject:     "{{integration}} setup needs one more step",
		Description: "Sent when an integration is connected but its webhook is not configured (WebhookConfigured = false). Variables: firstName, integration, agentName.",
		Variables:   []string{"agentName", "firstName", "integration"},
	},
	TmplIntegrationsReauth: {
		Slug:        "integrations-reauth",
		Name:        "Integrations — Reauthorize required",
		Subject:     "{{integration}} needs to be reauthorized",
		Description: "Sent when an OAuth token refresh fails and the integration needs manual reauthorization. Variables: firstName, integration.",
		Variables:   []string{"firstName", "integration"},
	},
	TmplIntegrationsRevoked: {
		Slug:        "integrations-revoked",
		Name:        "Integrations — Connection revoked",
		Subject:     "{{integration}} has been disconnected",
		Description: "Sent when an integration connection is revoked (InConnection.RevokedAt set or Nango disconnect). Variables: firstName, integration, revokedAt.",
		Variables:   []string{"firstName", "integration", "revokedAt"},
	},

	// LLM & Proxy
	TmplLlmCredentialInvalid: {
		Slug:        "llm-credential-invalid",
		Name:        "LLM — Credential invalid",
		Subject:     "{{provider}} credential rejected — action required",
		Description: "Fires when the LLM proxy gets a 401 from a provider. Vars: firstName, provider, credentialName.",
		Variables:   []string{"credentialName", "firstName", "provider"},
	},
	TmplLlmMonthlyCost: {
		Slug:        "llm-monthly-cost",
		Name:        "LLM — Monthly cost summary",
		Subject:     "Your {{month}} LLM cost summary",
		Description: "End-of-month opt-in cost digest. Vars: firstName, month, totalAmount, agentCount, topAgentName, topAgentCost.",
		Variables:   []string{"agentCount", "firstName", "month", "topAgentCost", "topAgentName", "totalAmount"},
	},
	TmplLlmRateLimited: {
		Slug:        "llm-rate-limited",
		Name:        "LLM — Provider rate limit",
		Subject:     "{{provider}} is throttling your agents",
		Description: "Fires when a provider sustains 429s through the proxy. Vars: firstName, provider, windowMinutes.",
		Variables:   []string{"firstName", "provider", "windowMinutes"},
	},
	TmplLlmSpendSpike: {
		Slug:        "llm-spend-spike",
		Name:        "LLM — Spend spike detected",
		Subject:     "LLM spend spike: {{amount}} in the last {{windowHours}}h",
		Description: "Fires on anomalous LLM spend vs baseline. Vars: firstName, amount, windowHours, baselineAmount.",
		Variables:   []string{"amount", "baselineAmount", "firstName", "windowHours"},
	},

	// API Keys
	TmplApiKeyCreated: {
		Slug:        "api-key-created",
		Name:        "API keys — Key created",
		Subject:     "New API key created: {{keyName}}",
		Description: "Fires on POST /api-keys. Vars: firstName, keyName, keyPrefix, createdAt, createdFromIp.",
		Variables:   []string{"createdAt", "createdFromIp", "firstName", "keyName", "keyPrefix"},
	},
	TmplApiKeyExpiring: {
		Slug:        "api-key-expiring",
		Name:        "API keys — Key expiring soon",
		Subject:     "{{keyName}} expires in {{daysRemaining}} days",
		Description: "Fires 7 days before ExpiresAt. Vars: firstName, keyName, expiresAt, daysRemaining.",
		Variables:   []string{"daysRemaining", "expiresAt", "firstName", "keyName"},
	},
	TmplApiKeyFirstUsed: {
		Slug:        "api-key-first-used",
		Name:        "API keys — First use detected",
		Subject:     "{{keyName}} was used for the first time",
		Description: "Fires the first time LastUsedAt goes non-null. Vars: firstName, keyName, usedFromIp, usedAt.",
		Variables:   []string{"firstName", "keyName", "usedAt", "usedFromIp"},
	},
	TmplApiKeyRevoked: {
		Slug:        "api-key-revoked",
		Name:        "API keys — Key revoked",
		Subject:     "API key revoked: {{keyName}}",
		Description: "Fires when RevokedAt is set on an API key. Vars: firstName, keyName, revokedBy, revokedAt.",
		Variables:   []string{"firstName", "keyName", "revokedAt", "revokedBy"},
	},
	TmplApiKeySuspicious: {
		Slug:        "api-key-suspicious",
		Name:        "API keys — Suspicious activity",
		Subject:     "Suspicious activity on API key {{keyName}}",
		Description: "Fires on anomalous IP or scope activity for an API key. Vars: firstName, keyName, suspiciousIp, reason.",
		Variables:   []string{"firstName", "keyName", "reason", "suspiciousIp"},
	},

	// Custom Domains
	TmplDomainCertRenewalFailed: {
		Slug:        "domain-cert-renewal-failed",
		Name:        "Domains — Certificate renewal failed",
		Subject:     "Certificate renewal failed for {{domain}}",
		Description: "Triggered when ACME certificate renewal fails for a verified domain. Variables: firstName, domain, expiresAt, reason.",
		Variables:   []string{"domain", "expiresAt", "firstName", "reason"},
	},
	TmplDomainVerificationFailed: {
		Slug:        "domain-verification-failed",
		Name:        "Domains — Domain verification failed",
		Subject:     "Action needed: couldn't verify {{domain}}",
		Description: "Triggered when domain verification (CNAME/ACME) fails. Variables: firstName, domain, reason.",
		Variables:   []string{"domain", "firstName", "reason"},
	},
	TmplDomainVerified: {
		Slug:        "domain-verified",
		Name:        "Domains — Domain verified",
		Subject:     "{{domain}} is verified",
		Description: "Triggered when a custom domain's DNS and ACME challenge succeed. Variables: firstName, domain, verifiedAt.",
		Variables:   []string{"domain", "firstName", "verifiedAt"},
	},

	// Sandbox Templates
	TmplSandboxTemplateBuilt: {
		Slug:        "sandbox-template-built",
		Name:        "Sandbox — Template built",
		Subject:     "{{templateName}} is ready to use",
		Description: "Triggered when an async sandbox template build completes successfully. Variables: firstName, templateName, builtAt, sizeMb.",
		Variables:   []string{"builtAt", "firstName", "sizeMb", "templateName"},
	},
	TmplSandboxTemplateFailed: {
		Slug:        "sandbox-template-failed",
		Name:        "Sandbox — Template build failed",
		Subject:     "Build failed for {{templateName}}",
		Description: "Triggered when an async sandbox template build fails. Variables: firstName, templateName, errorSummary, logsUrl.",
		Variables:   []string{"errorSummary", "firstName", "logsUrl", "templateName"},
	},

	// Storage & Memory
	TmplStorageMemory90: {
		Slug:        "storage-memory-90",
		Name:        "Storage — Agent memory at 90%",
		Subject:     "{{agentName}} memory is 90% full",
		Description: "Triggered when an agent's memory hits 90% of its limit. Variables: firstName, agentName, usedMb, limitMb.",
		Variables:   []string{"agentName", "firstName", "limitMb", "usedMb"},
	},
	TmplStorageWorkspaceFull: {
		Slug:        "storage-workspace-full",
		Name:        "Storage — Workspace storage full",
		Subject:     "Your workspace is out of storage",
		Description: "Triggered when workspace storage reaches its limit. Variables: firstName, usedGb, limitGb.",
		Variables:   []string{"firstName", "limitGb", "usedGb"},
	},

	// Marketplace
	TmplMarketplaceDeprecated: {
		Slug:        "marketplace-deprecated",
		Name:        "Marketplace — Agent deprecated",
		Subject:     "{{agentName}} has been deprecated",
		Description: "Fires when a publisher archives an installed agent. Variables: firstName, agentName, publisherName, recommendedAlternative (optional).",
		Variables:   []string{"agentName", "firstName", "publisherName", "recommendedAlternative"},
	},
	TmplMarketplaceEarnings: {
		Slug:        "marketplace-earnings",
		Name:        "Marketplace — Monthly earnings statement",
		Subject:     "Your {{month}} marketplace earnings: {{amount}}",
		Description: "Monthly earnings statement at $2.50 per install. Variables: firstName, month, amount, installCount, topAgentName.",
		Variables:   []string{"amount", "firstName", "installCount", "month", "topAgentName"},
	},
	TmplMarketplaceInstallMilestone: {
		Slug:        "marketplace-install-milestone",
		Name:        "Marketplace — Install milestone",
		Subject:     "{{agentName}} hit {{milestone}} installs",
		Description: "Fires when an agent crosses a 10, 100, or 1000 install milestone. Variables: firstName, agentName, installCount, milestone, marketplaceUrl.",
		Variables:   []string{"agentName", "firstName", "installCount", "marketplaceUrl", "milestone"},
	},
	TmplMarketplaceInstalled: {
		Slug:        "marketplace-installed",
		Name:        "Marketplace — Agent installed",
		Subject:     "{{agentName}} is installed in {{orgName}}",
		Description: "Fires when a marketplace agent is installed into the installer's org. Variables: firstName, agentName, orgName, publisherName.",
		Variables:   []string{"agentName", "firstName", "orgName", "publisherName"},
	},
	TmplMarketplacePayout: {
		Slug:        "marketplace-payout",
		Name:        "Marketplace — Payout sent",
		Subject:     "Payout sent: {{amount}} {{currency}} for {{period}}",
		Description: "Fires when a Polar payout completes. Variables: firstName, amount, currency, paidAt, period.",
		Variables:   []string{"amount", "currency", "firstName", "paidAt", "period"},
	},
	TmplMarketplacePublished: {
		Slug:        "marketplace-published",
		Name:        "Marketplace — Agent published",
		Subject:     "{{agentName}} is live on the marketplace",
		Description: "Fires when an admin approves a marketplace submission / PublishedAt is set. Variables: firstName, agentName, marketplaceUrl, publishedAt.",
		Variables:   []string{"agentName", "firstName", "marketplaceUrl", "publishedAt"},
	},
	TmplMarketplaceRejected: {
		Slug:        "marketplace-rejected",
		Name:        "Marketplace — Changes requested",
		Subject:     "Changes requested on {{agentName}}",
		Description: "Fires when marketplace reviewers flag a submission (Flagged = true). Variables: firstName, agentName, reason, reviewerNote.",
		Variables:   []string{"agentName", "firstName", "reason", "reviewerNote"},
	},
	TmplMarketplaceSubmitted: {
		Slug:        "marketplace-submitted",
		Name:        "Marketplace — Submission received",
		Subject:     "{{agentName}} is in the marketplace review queue",
		Description: "Fires when a publisher submits an agent for marketplace review. Variables: firstName, agentName, submittedAt.",
		Variables:   []string{"agentName", "firstName", "submittedAt"},
	},
	TmplMarketplaceUpdated: {
		Slug:        "marketplace-updated",
		Name:        "Marketplace — New version available",
		Subject:     "{{agentName}} updated to {{newVersion}}",
		Description: "Fires when a publisher ships a new version of an installed agent. Variables: firstName, agentName, oldVersion, newVersion, changelogSummary.",
		Variables:   []string{"agentName", "changelogSummary", "firstName", "newVersion", "oldVersion"},
	},
	TmplMarketplaceVerified: {
		Slug:        "marketplace-verified",
		Name:        "Marketplace — Verified badge granted",
		Subject:     "{{agentName}} is now verified",
		Description: "Fires when an agent receives the verified badge (VerifiedAt set). Variables: firstName, agentName, verifiedAt, marketplaceUrl.",
		Variables:   []string{"agentName", "firstName", "marketplaceUrl", "verifiedAt"},
	},

	// Platform
	TmplPlatformIncident: {
		Slug:        "platform-incident",
		Name:        "Platform — Incident update",
		Subject:     "HiveLoop incident: {{title}}",
		Description: "Fires when a platform incident / service degradation is declared. Variables: firstName, title, summary, startedAt, severity.",
		Variables:   []string{"firstName", "severity", "startedAt", "summary", "title"},
	},
	TmplPlatformLegalUpdate: {
		Slug:        "platform-legal-update",
		Name:        "Platform — Terms and Privacy update",
		Subject:     "Updates to the HiveLoop Terms and Privacy Policy",
		Description: "Fires when HiveLoop updates its Terms of Service or Privacy Policy. Variables: firstName, effectiveDate, summary, termsUrl, privacyUrl.",
		Variables:   []string{"effectiveDate", "firstName", "privacyUrl", "summary", "termsUrl"},
	},
	TmplPlatformMaintenance: {
		Slug:        "platform-maintenance",
		Name:        "Platform — Scheduled maintenance",
		Subject:     "Scheduled maintenance on HiveLoop {{scope}}",
		Description: "Fires when HiveLoop has scheduled maintenance on a subsystem. Variables: firstName, startsAt, endsAt, scope, details.",
		Variables:   []string{"details", "endsAt", "firstName", "scope", "startsAt"},
	},
	TmplPlatformModeration: {
		Slug:        "platform-moderation",
		Name:        "Platform — Moderation action",
		Subject:     "Action taken on your HiveLoop account: {{action}}",
		Description: "Fires when trust and safety takes a moderation action on an account (suspension, warning, etc.). Variables: firstName, action, reason, appealUrl.",
		Variables:   []string{"action", "appealUrl", "firstName", "reason"},
	},
}

// VariablesFor returns the list of variable keys a template expects at
// send time. `business_address` is omitted — Kibamail resolves it.
func (s TemplateSlug) VariablesFor() []string {
	vars, ok := templateVars[s]
	if !ok {
		return nil
	}
	out := make([]string, len(vars))
	copy(out, vars)
	return out
}

// Meta returns the full metadata record for a template slug.
func (s TemplateSlug) Meta() (TemplateMeta, bool) {
	m, ok := templateMeta[s]
	return m, ok
}

// AllSlugs returns every registered template slug, for iteration / validation.
func AllSlugs() []TemplateSlug {
	out := make([]TemplateSlug, 0, len(templateMeta))
	for s := range templateMeta {
		out = append(out, s)
	}
	return out
}

// Validate checks that every variable listed for `slug` is present in `vars`
// and non-empty. Returns the list of missing or empty keys.
func Validate(slug TemplateSlug, vars TemplateVars) []string {
	required := templateVars[slug]
	missing := make([]string, 0, len(required))
	for _, k := range required {
		v, ok := vars[k]
		if !ok || v == "" {
			missing = append(missing, k)
		}
	}
	return missing
}
