// Package bridge provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package bridge

import (
	"encoding/json"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	BearerScopes bearerContextKey = "bearer.Scopes"
)

// Defines values for ApprovalDecision.
const (
	ApprovalDecisionApprove ApprovalDecision = "approve"
	ApprovalDecisionDeny    ApprovalDecision = "deny"
)

// Valid indicates whether the value is a known member of the ApprovalDecision enum.
func (e ApprovalDecision) Valid() bool {
	switch e {
	case ApprovalDecisionApprove:
		return true
	case ApprovalDecisionDeny:
		return true
	default:
		return false
	}
}

// Defines values for ApprovalStatus.
const (
	Approved ApprovalStatus = "approved"
	Denied   ApprovalStatus = "denied"
	Pending  ApprovalStatus = "pending"
)

// Valid indicates whether the value is a known member of the ApprovalStatus enum.
func (e ApprovalStatus) Valid() bool {
	switch e {
	case Approved:
		return true
	case Denied:
		return true
	case Pending:
		return true
	default:
		return false
	}
}

// Defines values for CacheTtl.
const (
	FiveMinutes CacheTtl = "five_minutes"
	OneHour     CacheTtl = "one_hour"
)

// Valid indicates whether the value is a known member of the CacheTtl enum.
func (e CacheTtl) Valid() bool {
	switch e {
	case FiveMinutes:
		return true
	case OneHour:
		return true
	default:
		return false
	}
}

// Defines values for ContentBlock0Type.
const (
	Text ContentBlock0Type = "text"
)

// Valid indicates whether the value is a known member of the ContentBlock0Type enum.
func (e ContentBlock0Type) Valid() bool {
	switch e {
	case Text:
		return true
	default:
		return false
	}
}

// Defines values for ContentBlock1Type.
const (
	ContentBlock1TypeToolCall ContentBlock1Type = "tool_call"
)

// Valid indicates whether the value is a known member of the ContentBlock1Type enum.
func (e ContentBlock1Type) Valid() bool {
	switch e {
	case ContentBlock1TypeToolCall:
		return true
	default:
		return false
	}
}

// Defines values for ContentBlock2Type.
const (
	ContentBlock2TypeToolResult ContentBlock2Type = "tool_result"
)

// Valid indicates whether the value is a known member of the ContentBlock2Type enum.
func (e ContentBlock2Type) Valid() bool {
	switch e {
	case ContentBlock2TypeToolResult:
		return true
	default:
		return false
	}
}

// Defines values for ContentBlock3Type.
const (
	Image ContentBlock3Type = "image"
)

// Valid indicates whether the value is a known member of the ContentBlock3Type enum.
func (e ContentBlock3Type) Valid() bool {
	switch e {
	case Image:
		return true
	default:
		return false
	}
}

// Defines values for McpTransport0Type.
const (
	Stdio McpTransport0Type = "stdio"
)

// Valid indicates whether the value is a known member of the McpTransport0Type enum.
func (e McpTransport0Type) Valid() bool {
	switch e {
	case Stdio:
		return true
	default:
		return false
	}
}

// Defines values for McpTransport1Type.
const (
	StreamableHttp McpTransport1Type = "streamable_http"
)

// Valid indicates whether the value is a known member of the McpTransport1Type enum.
func (e McpTransport1Type) Valid() bool {
	switch e {
	case StreamableHttp:
		return true
	default:
		return false
	}
}

// Defines values for ProviderType.
const (
	ProviderTypeAnthropic ProviderType = "anthropic"
	ProviderTypeCohere    ProviderType = "cohere"
	ProviderTypeCustom    ProviderType = "custom"
	ProviderTypeDeepSeek  ProviderType = "deep_seek"
	ProviderTypeFireworks ProviderType = "fireworks"
	ProviderTypeGoogle    ProviderType = "google"
	ProviderTypeGroq      ProviderType = "groq"
	ProviderTypeMistral   ProviderType = "mistral"
	ProviderTypeOllama    ProviderType = "ollama"
	ProviderTypeOpenAi    ProviderType = "open_ai"
	ProviderTypeTogether  ProviderType = "together"
	ProviderTypeXAi       ProviderType = "x_ai"
)

// Valid indicates whether the value is a known member of the ProviderType enum.
func (e ProviderType) Valid() bool {
	switch e {
	case ProviderTypeAnthropic:
		return true
	case ProviderTypeCohere:
		return true
	case ProviderTypeCustom:
		return true
	case ProviderTypeDeepSeek:
		return true
	case ProviderTypeFireworks:
		return true
	case ProviderTypeGoogle:
		return true
	case ProviderTypeGroq:
		return true
	case ProviderTypeMistral:
		return true
	case ProviderTypeOllama:
		return true
	case ProviderTypeOpenAi:
		return true
	case ProviderTypeTogether:
		return true
	case ProviderTypeXAi:
		return true
	default:
		return false
	}
}

// Defines values for RequirementCadence0Type.
const (
	EveryTurn RequirementCadence0Type = "every_turn"
)

// Valid indicates whether the value is a known member of the RequirementCadence0Type enum.
func (e RequirementCadence0Type) Valid() bool {
	switch e {
	case EveryTurn:
		return true
	default:
		return false
	}
}

// Defines values for RequirementCadence1Type.
const (
	FirstTurnOnly RequirementCadence1Type = "first_turn_only"
)

// Valid indicates whether the value is a known member of the RequirementCadence1Type enum.
func (e RequirementCadence1Type) Valid() bool {
	switch e {
	case FirstTurnOnly:
		return true
	default:
		return false
	}
}

// Defines values for RequirementCadence2Type.
const (
	EveryNTurns RequirementCadence2Type = "every_n_turns"
)

// Valid indicates whether the value is a known member of the RequirementCadence2Type enum.
func (e RequirementCadence2Type) Valid() bool {
	switch e {
	case EveryNTurns:
		return true
	default:
		return false
	}
}

// Defines values for RequirementEnforcement.
const (
	NextTurnReminder RequirementEnforcement = "next_turn_reminder"
	Reprompt         RequirementEnforcement = "reprompt"
	Warn             RequirementEnforcement = "warn"
)

// Valid indicates whether the value is a known member of the RequirementEnforcement enum.
func (e RequirementEnforcement) Valid() bool {
	switch e {
	case NextTurnReminder:
		return true
	case Reprompt:
		return true
	case Warn:
		return true
	default:
		return false
	}
}

// Defines values for RequirementPosition.
const (
	Anywhere  RequirementPosition = "anywhere"
	TurnEnd   RequirementPosition = "turn_end"
	TurnStart RequirementPosition = "turn_start"
)

// Valid indicates whether the value is a known member of the RequirementPosition enum.
func (e RequirementPosition) Valid() bool {
	switch e {
	case Anywhere:
		return true
	case TurnEnd:
		return true
	case TurnStart:
		return true
	default:
		return false
	}
}

// Defines values for Role.
const (
	Assistant Role = "assistant"
	System    Role = "system"
	Tool      Role = "tool"
	User      Role = "user"
)

// Valid indicates whether the value is a known member of the Role enum.
func (e Role) Valid() bool {
	switch e {
	case Assistant:
		return true
	case System:
		return true
	case Tool:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Defines values for SkillSource.
const (
	AgentSkills   SkillSource = "agent_skills"
	ClaudeCode    SkillSource = "claude_code"
	ControlPlane  SkillSource = "control_plane"
	CursorRules   SkillSource = "cursor_rules"
	GitHubCopilot SkillSource = "git_hub_copilot"
	WindsurfRules SkillSource = "windsurf_rules"
)

// Valid indicates whether the value is a known member of the SkillSource enum.
func (e SkillSource) Valid() bool {
	switch e {
	case AgentSkills:
		return true
	case ClaudeCode:
		return true
	case ControlPlane:
		return true
	case CursorRules:
		return true
	case GitHubCopilot:
		return true
	case WindsurfRules:
		return true
	default:
		return false
	}
}

// Defines values for ToolPermission.
const (
	ToolPermissionAllow           ToolPermission = "allow"
	ToolPermissionDeny            ToolPermission = "deny"
	ToolPermissionRequireApproval ToolPermission = "require_approval"
)

// Valid indicates whether the value is a known member of the ToolPermission enum.
func (e ToolPermission) Valid() bool {
	switch e {
	case ToolPermissionAllow:
		return true
	case ToolPermissionDeny:
		return true
	case ToolPermissionRequireApproval:
		return true
	default:
		return false
	}
}

// Defines values for VerifierProvider.
const (
	VerifierProviderGemini VerifierProvider = "gemini"
	VerifierProviderOpenAi VerifierProvider = "open_ai"
)

// Valid indicates whether the value is a known member of the VerifierProvider enum.
func (e VerifierProvider) Valid() bool {
	switch e {
	case VerifierProviderGemini:
		return true
	case VerifierProviderOpenAi:
		return true
	default:
		return false
	}
}

// AbortConversationResponse Response for aborting a conversation turn.
type AbortConversationResponse struct {
	// Status Status of the abort operation.
	Status string `json:"status"`
}

// AgentConfig Configuration options for an agent.
type AgentConfig struct {
	// DisabledTools Tools to disable for this agent. Takes priority over everything else —
	// disabled tools are removed from the registry before the agent is built,
	// so the LLM never sees them. Works for built-in tools, MCP tools,
	// integration tools, and spider tools.
	DisabledTools *[]string                 `json:"disabled_tools,omitempty"`
	HistoryStrip  *AgentConfig_HistoryStrip `json:"history_strip,omitempty"`
	Immortal      *AgentConfig_Immortal     `json:"immortal,omitempty"`

	// JsonSchema JSON schema for structured output
	JsonSchema interface{} `json:"json_schema,omitempty"`

	// MaxConcurrentConversations Maximum concurrent conversations for this specific agent.
	// Takes precedence over the global max_concurrent_conversations.
	MaxConcurrentConversations *int32 `json:"max_concurrent_conversations,omitempty"`

	// MaxTasksPerConversation Maximum total subagent tasks per conversation. Limits resource consumption
	// from recursive/parallel subagent spawning. Default: 50.
	MaxTasksPerConversation *int32 `json:"max_tasks_per_conversation,omitempty"`

	// MaxTokens Maximum tokens for LLM response
	MaxTokens *int32 `json:"max_tokens,omitempty"`

	// MaxTurns Maximum conversation turns
	MaxTurns *int32 `json:"max_turns,omitempty"`

	// RateLimitRpm Rate limit in requests per minute
	RateLimitRpm *int32 `json:"rate_limit_rpm,omitempty"`

	// SubagentTimeoutBackgroundSecs Wall-clock timeout (seconds) applied when this agent is invoked as a
	// background subagent. Default: 300 (5 minutes).
	SubagentTimeoutBackgroundSecs *int64 `json:"subagent_timeout_background_secs,omitempty"`

	// SubagentTimeoutForegroundSecs Wall-clock timeout (seconds) applied when this agent is invoked as a
	// foreground subagent. Default: 300 (5 minutes).
	SubagentTimeoutForegroundSecs *int64 `json:"subagent_timeout_foreground_secs,omitempty"`

	// SystemReminderRefreshTurns How often (in turns) to re-emit the stable system reminder (skills,
	// subagents, todos) at the head of the user message. Always emitted on
	// turn 0; thereafter on turns where `turn_count % N == 0`. Lower values
	// reinforce the reminders more often at the cost of bigger uncached
	// tails on those turns; higher values let the reminder go stale but
	// keep prompt sizes lean.
	//
	// Default: 10. Set to 1 for every-turn refresh; values <1 are clamped
	// to 1.
	SystemReminderRefreshTurns *int32 `json:"system_reminder_refresh_turns,omitempty"`

	// Temperature Temperature for LLM sampling
	Temperature *float64 `json:"temperature,omitempty"`

	// ToolCallsOnly When true, the agent can complete a turn with only tool calls and no text.
	// Empty text responses are treated as success if tool calls were executed.
	// Default: false.
	ToolCallsOnly *bool `json:"tool_calls_only,omitempty"`

	// ToolRequirements Declarative tool-call requirements evaluated at the end of every agent
	// turn. Each entry describes a tool that must be called (with optional
	// cadence, position, and min-call constraints) and what bridge should do
	// if the requirement is violated. See [`ToolRequirement`] for the shape
	// and [`RequirementEnforcement`] for the dispatch options.
	//
	// Default: empty (no enforcement).
	ToolRequirements *[]ToolRequirement    `json:"tool_requirements,omitempty"`
	Verifier         *AgentConfig_Verifier `json:"verifier,omitempty"`
}

// AgentConfig_HistoryStrip defines model for AgentConfig.HistoryStrip.
type AgentConfig_HistoryStrip struct {
	union json.RawMessage
}

// AgentConfig_Immortal defines model for AgentConfig.Immortal.
type AgentConfig_Immortal struct {
	union json.RawMessage
}

// AgentConfig_Verifier defines model for AgentConfig.Verifier.
type AgentConfig_Verifier struct {
	union json.RawMessage
}

// AgentDefinition Complete definition of an AI agent fetched from the control plane.
type AgentDefinition struct {
	Artifacts *AgentDefinition_Artifacts `json:"artifacts,omitempty"`

	// Config Configuration options for an agent.
	Config *AgentConfig `json:"config,omitempty"`

	// Description Human-readable description of the agent's purpose and capabilities.
	// Used in tool documentation when this agent is a subagent.
	Description *string `json:"description,omitempty"`
	Id          String  `json:"id"`

	// Integrations External integrations (e.g., GitHub, Slack, Mailchimp).
	// Each integration's actions become individual tools for the agent.
	Integrations *[]IntegrationDefinition `json:"integrations,omitempty"`

	// McpServers MCP server connections
	McpServers *[]McpServerDefinition `json:"mcp_servers,omitempty"`

	// Name Human-readable agent name
	Name string `json:"name"`

	// Permissions Per-tool permission overrides. Key = tool name, Value = permission level.
	// Tools not listed default to `Allow`.
	Permissions *map[string]ToolPermission `json:"permissions,omitempty"`

	// Provider Configuration for an LLM provider.
	Provider ProviderConfig `json:"provider"`

	// Skills Available skills
	Skills *[]SkillDefinition `json:"skills,omitempty"`

	// Subagents Nested subagent definitions
	Subagents *[]AgentDefinition `json:"subagents,omitempty"`

	// SystemPrompt System prompt for the agent
	SystemPrompt string `json:"system_prompt"`

	// Tools Agent-defined tools
	Tools *[]ToolDefinition `json:"tools,omitempty"`

	// UpdatedAt Last updated timestamp for change detection
	UpdatedAt *string `json:"updated_at,omitempty"`

	// Version Version field for change detection during sync
	Version *string `json:"version,omitempty"`

	// WebhookSecret Webhook secret for HMAC signing
	WebhookSecret *string `json:"webhook_secret,omitempty"`

	// WebhookUrl Webhook URL for event delivery
	WebhookUrl *string `json:"webhook_url,omitempty"`
}

// AgentDefinition_Artifacts defines model for AgentDefinition.Artifacts.
type AgentDefinition_Artifacts struct {
	union json.RawMessage
}

// AgentResponse Full agent response — returned by both list and detail endpoints.
// System prompts may be truncated on the list endpoint.
type AgentResponse struct {
	ActiveConversations int                      `json:"active_conversations"`
	Artifacts           *AgentResponse_Artifacts `json:"artifacts,omitempty"`

	// Config Configuration options for an agent.
	Config       AgentConfig             `json:"config"`
	Description  *string                 `json:"description,omitempty"`
	Id           string                  `json:"id"`
	Integrations []IntegrationDefinition `json:"integrations"`
	McpServers   []McpServerDefinition   `json:"mcp_servers"`

	// Metrics Serializable snapshot of agent metrics for the /metrics endpoint.
	Metrics     MetricsSnapshot           `json:"metrics"`
	Name        string                    `json:"name"`
	Permissions map[string]ToolPermission `json:"permissions"`

	// Provider Provider info with secrets redacted.
	Provider ProviderSummary `json:"provider"`

	// RegisteredTools All tools registered and available to this agent (built-in + MCP + integrations).
	RegisteredTools []RegisteredToolSummary `json:"registered_tools"`
	Skills          []SkillDefinition       `json:"skills"`
	Subagents       []SubAgentSummary       `json:"subagents"`
	SystemPrompt    string                  `json:"system_prompt"`
	Tools           []ToolDefinition        `json:"tools"`
	UpdatedAt       *string                 `json:"updated_at,omitempty"`
	Version         *string                 `json:"version,omitempty"`
	WebhookUrl      *string                 `json:"webhook_url,omitempty"`
}

// AgentResponse_Artifacts defines model for AgentResponse.Artifacts.
type AgentResponse_Artifacts struct {
	union json.RawMessage
}

// ApprovalDecision The user's decision on an approval request.
type ApprovalDecision string

// ApprovalReply HTTP request body for resolving a single approval.
type ApprovalReply struct {
	// Decision The user's decision on an approval request.
	Decision ApprovalDecision `json:"decision"`

	// Reason Optional message explaining why the tool call was denied.
	// Included in the error returned to the LLM so the agent can adjust.
	Reason *string `json:"reason,omitempty"`
}

// ApprovalRequest A pending approval request for a tool call.
type ApprovalRequest struct {
	// AgentId Agent that initiated the tool call.
	AgentId string `json:"agent_id"`

	// Arguments Arguments passed to the tool.
	Arguments interface{} `json:"arguments"`

	// ConversationId Conversation in which the tool call occurred.
	ConversationId string `json:"conversation_id"`

	// CreatedAt When the approval request was created.
	CreatedAt time.Time `json:"created_at"`

	// Id Unique ID for this approval request.
	Id string `json:"id"`

	// Status Status of an approval request.
	Status ApprovalStatus `json:"status"`

	// ToolCallId The LLM's tool call ID.
	ToolCallId string `json:"tool_call_id"`

	// ToolName Name of the tool being called.
	ToolName string `json:"tool_name"`
}

// ApprovalStatus Status of an approval request.
type ApprovalStatus string

// ArtifactsConfig Per-agent workspace artifact upload configuration.
//
// When present on an [`crate::agent::AgentDefinition`], bridge auto-registers
// an `upload_to_workspace` tool that streams files from the agent's sandbox
// to the control plane via a tus.io-compatible resumable upload protocol.
type ArtifactsConfig struct {
	// AcceptedFileTypes Allowed file types. Each entry is matched against the file's MIME type
	// (e.g. `text/csv`, `video/mp4`) or its extension (e.g. `csv`, `mp4`).
	// Wildcards are supported on the MIME-type side (e.g. `video/*`).
	AcceptedFileTypes []string `json:"accepted_file_types"`

	// ChunkSizeBytes Chunk size used for PATCH requests. Defaults to 8 MiB. Smaller values
	// give finer-grained resume but more HTTP round-trips.
	ChunkSizeBytes *int64 `json:"chunk_size_bytes,omitempty"`

	// DownloadUrl Optional canonical download URL template returned to the agent
	// alongside the upload result. Bridge does not call this — it's a hint
	// the control plane includes for downstream consumers.
	DownloadUrl *string `json:"download_url,omitempty"`

	// Headers Extra headers forwarded on every upload request (creation + each
	// chunk). Use for workspace IDs, tenant identifiers, etc.
	Headers *map[string]string `json:"headers,omitempty"`

	// MaxConcurrentUploads Maximum concurrent in-flight uploads for this agent. Defaults to a
	// modest ceiling so a runaway agent can't saturate the network.
	MaxConcurrentUploads *int32 `json:"max_concurrent_uploads,omitempty"`

	// MaxSizeBytes Hard upper bound on file size in bytes. Files larger than this are
	// rejected before any network I/O.
	MaxSizeBytes int64 `json:"max_size_bytes"`

	// UploadUrl tus.io creation endpoint on the control plane. A POST here returns a
	// per-upload `Location` URL used for chunked PATCH operations.
	UploadUrl string `json:"upload_url"`
}

// BulkApprovalReply HTTP request body for resolving multiple approvals at once.
type BulkApprovalReply struct {
	// Decision The user's decision on an approval request.
	Decision ApprovalDecision `json:"decision"`

	// Reason Optional message explaining why the tool calls were denied.
	Reason     *string  `json:"reason,omitempty"`
	RequestIds []string `json:"request_ids"`
}

// BulkResolveApprovalsResponse Response for bulk resolving approvals.
type BulkResolveApprovalsResponse struct {
	// NotFound List of request IDs that were not found.
	NotFound []string `json:"not_found"`

	// Resolved List of request IDs that were successfully resolved.
	Resolved []string `json:"resolved"`
}

// CacheTtl Prompt-cache TTL hint.
//
// Anthropic supports two TTLs today: 5-minute ephemeral (default,
// 1.25× cache-write multiplier) and 1-hour extended (2.0× write, needs
// `extended-cache-ttl-2025-04-11` beta header). Other providers ignore
// this field — their caches are automatic and provider-managed.
//
// **Note (rig 0.31)**: `with_prompt_caching()` only emits the
// `{"type": "ephemeral"}` breakpoint, which corresponds to the 5-minute
// TTL. Setting `OneHour` here sends the beta header but does not yet
// add `"ttl": "1h"` to the cache_control block — upgrade rig to get
// true 1-hour writes. The field is wired now so the choice survives
// the upgrade.
type CacheTtl string

// ContentBlock A content block within a message.
type ContentBlock struct {
	union json.RawMessage
}

// ContentBlock0 Plain text content
type ContentBlock0 struct {
	// Text The text content
	Text string            `json:"text"`
	Type ContentBlock0Type `json:"type"`
}

// ContentBlock0Type defines model for ContentBlock.0.Type.
type ContentBlock0Type string

// ContentBlock1 defines model for .
type ContentBlock1 struct {
	// Arguments Arguments to pass to the tool
	Arguments interface{} `json:"arguments"`

	// Id Unique identifier for this tool call
	Id string `json:"id"`

	// Name Name of the tool to call
	Name string            `json:"name"`
	Type ContentBlock1Type `json:"type"`
}

// ContentBlock1Type defines model for ContentBlock.1.Type.
type ContentBlock1Type string

// ContentBlock2 defines model for .
type ContentBlock2 struct {
	// Content The result content
	Content string `json:"content"`

	// IsError Whether the tool execution resulted in an error
	IsError *bool `json:"is_error,omitempty"`

	// ToolCallId ID of the tool call this result corresponds to
	ToolCallId string            `json:"tool_call_id"`
	Type       ContentBlock2Type `json:"type"`
}

// ContentBlock2Type defines model for ContentBlock.2.Type.
type ContentBlock2Type string

// ContentBlock3 An image attachment
type ContentBlock3 struct {
	// Data Base64-encoded image data
	Data string `json:"data"`

	// MediaType MIME type of the image
	MediaType string            `json:"media_type"`
	Type      ContentBlock3Type `json:"type"`
}

// ContentBlock3Type defines model for ContentBlock.3.Type.
type ContentBlock3Type string

// ConversationRecord A conversation with its full message history, as returned by the control plane.
type ConversationRecord struct {
	// AgentId Agent that owns this conversation.
	AgentId string `json:"agent_id"`

	// CreatedAt When the conversation was created.
	CreatedAt time.Time `json:"created_at"`
	Id        String    `json:"id"`

	// Messages Full message history.
	Messages []Message `json:"messages"`

	// Title Optional human-readable title.
	Title *string `json:"title,omitempty"`

	// UpdatedAt When the conversation was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// CreateConversationRequest Optional request body for creating a conversation with tool/MCP scoping.
type CreateConversationRequest struct {
	// ApiKey When provided, overrides the agent's LLM API key for this conversation only.
	// For full provider/model override, use the `provider` field instead.
	ApiKey *string `json:"api_key,omitempty"`

	// McpServerNames When provided, only tools from these MCP servers are available.
	// Server names must match the agent's configured MCP server names.
	McpServerNames *[]string `json:"mcp_server_names,omitempty"`

	// McpServers Additional MCP servers to load for this conversation only.
	// Connected at conversation creation, torn down when the conversation ends
	// (or is aborted, drained, or cancelled). Tool names produced by these
	// servers must not collide with the agent's existing tool names.
	//
	// Stdio transport requires the runtime config flag
	// `allow_stdio_mcp_from_api` to be enabled; otherwise only
	// `streamable_http` is accepted.
	McpServers *[]McpServerDefinition              `json:"mcp_servers,omitempty"`
	Provider   *CreateConversationRequest_Provider `json:"provider,omitempty"`

	// SubagentApiKeys Per-subagent API key overrides. Key = subagent name, Value = API key.
	// Only named subagents are overridden; others keep their configured keys.
	SubagentApiKeys *map[string]string `json:"subagent_api_keys,omitempty"`

	// ToolNames When provided, only these tools are available in the conversation.
	// Tool names must match the agent's registered tool names exactly.
	ToolNames *[]string `json:"tool_names,omitempty"`
}

// CreateConversationRequest_Provider defines model for CreateConversationRequest.Provider.
type CreateConversationRequest_Provider struct {
	union json.RawMessage
}

// CreateConversationResponse Response for creating a conversation.
type CreateConversationResponse struct {
	// ConversationId The ID of the newly created conversation.
	ConversationId string `json:"conversation_id"`

	// StreamUrl The URL to stream events from this conversation.
	StreamUrl string `json:"stream_url"`
}

// EndConversationResponse Response for ending a conversation.
type EndConversationResponse struct {
	// Status Status of the end operation.
	Status string `json:"status"`
}

// GlobalMetrics Global metrics across all agents.
type GlobalMetrics struct {
	// TotalActiveConversations Total active conversations across all agents
	TotalActiveConversations int64 `json:"total_active_conversations"`

	// TotalAgents Total number of loaded agents
	TotalAgents int `json:"total_agents"`

	// UptimeSecs Seconds since the runtime started
	UptimeSecs int64 `json:"uptime_secs"`
}

// HealthResponse Health check response.
type HealthResponse struct {
	// Status Health status - always "ok" if the server is running.
	Status string `json:"status"`

	// UptimeSecs Server uptime in seconds.
	UptimeSecs int64 `json:"uptime_secs"`
}

// HistoryStripConfig Configuration for stripping tool-result bodies from old messages before
// they are sent to the LLM. Reduces input tokens while preserving the
// ability to recover the full content via the on-disk spill file.
// Independent of immortal mode — applied at every send.
type HistoryStripConfig struct {
	// AgeThreshold Number of assistant messages that must follow a tool result before
	// it becomes eligible for stripping.
	AgeThreshold *int `json:"age_threshold,omitempty"`

	// Enabled Master switch. When false, strip is a no-op.
	Enabled *bool `json:"enabled,omitempty"`

	// PinErrors When true, tool results with `is_error: true` are never stripped.
	PinErrors *bool `json:"pin_errors,omitempty"`

	// PinRecentCount Always keep the most recent N tool results regardless of age.
	PinRecentCount *int `json:"pin_recent_count,omitempty"`
}

// HydrateConversationsRequest defines model for HydrateConversationsRequest.
type HydrateConversationsRequest struct {
	Conversations []ConversationRecord `json:"conversations"`
}

// HydrateConversationsResponse Response for hydrating conversations.
type HydrateConversationsResponse struct {
	// Hydrated Number of conversations hydrated.
	Hydrated int `json:"hydrated"`
}

// ImmortalConfig Configuration for immortal conversations — forgecode-style in-place
// compaction.
//
// When the conversation grows past `token_budget`, the eligible head of
// the history is replaced in place with a single user message containing
// a structured summary. Pure code — no LLM call, no scaffolding.
type ImmortalConfig struct {
	// EvictionWindow Maximum fraction of total tokens eligible for compaction in any
	// single pass (0.0–1.0). Mirrors forgecode's `eviction_window`.
	// Default 1.0 — compaction may take everything from the first
	// assistant message up to the retention boundary. Reduce to keep
	// the head of the conversation more stable across compactions
	// (each pass takes a smaller slice).
	EvictionWindow *float64 `json:"eviction_window,omitempty"`

	// ExposeJournalTools When true (default), bridge registers `journal_read` /
	// `journal_write` tools so the agent can record durable notes. The
	// journal is no longer read or written by the compaction engine
	// itself — it's only available as a tool for the agent's own use.
	ExposeJournalTools *bool `json:"expose_journal_tools,omitempty"`

	// RetentionWindow Number of most-recent messages preserved verbatim — never
	// compacted. Mirrors forgecode's `retention_window`. Default 0
	// (compaction may take everything except the system prompt and
	// initial user message). Increase to keep more recent context
	// pristine; the trade-off is the eligible compaction range shrinks.
	RetentionWindow *int32 `json:"retention_window,omitempty"`

	// TokenBudget Token budget. Compaction triggers when estimated history tokens
	// exceed this. Used by both the top-of-turn check and the
	// mid-rig-loop hook.
	TokenBudget *int32 `json:"token_budget,omitempty"`
}

// IntegrationAction A single action within an integration that an agent can invoke.
//
// Each action maps to a specific API operation on the external service.
// The control plane defines the schema and permissions for each action.
type IntegrationAction struct {
	// Description Human-readable description of what this action does.
	Description string `json:"description"`

	// Name Action identifier (e.g., "create_pull_request", "send_message").
	Name string `json:"name"`

	// ParametersSchema JSON Schema for the action's parameters.
	ParametersSchema interface{} `json:"parameters_schema"`

	// Permission Permission level for a tool within an agent.
	Permission ToolPermission `json:"permission"`
}

// IntegrationDefinition Definition of an external integration available to an agent.
//
// Each integration represents a connection to an external service (e.g., GitHub,
// Mailchimp, Slack) managed by the control plane. The control plane handles
// authentication and proxies requests to the underlying service.
type IntegrationDefinition struct {
	// Actions Available actions within this integration.
	Actions []IntegrationAction `json:"actions"`

	// Description Human-readable description of the integration.
	Description string `json:"description"`

	// Name Integration identifier (e.g., "github", "mailchimp", "slack").
	Name string `json:"name"`
}

// McpServerDefinition Definition of an MCP server that an agent connects to.
type McpServerDefinition struct {
	// Name Name of the MCP server
	Name string `json:"name"`

	// Transport Transport configuration for MCP server connections.
	Transport McpTransport `json:"transport"`
}

// McpTransport Transport configuration for MCP server connections.
type McpTransport struct {
	union json.RawMessage
}

// McpTransport0 Stdio transport — spawns a child process
type McpTransport0 struct {
	// Args Command arguments
	Args *[]string `json:"args,omitempty"`

	// Command Command to execute
	Command string `json:"command"`

	// Env Environment variables for the process
	Env  *map[string]string `json:"env,omitempty"`
	Type McpTransport0Type  `json:"type"`
}

// McpTransport0Type defines model for McpTransport.0.Type.
type McpTransport0Type string

// McpTransport1 Streamable HTTP transport — connects to an HTTP endpoint
type McpTransport1 struct {
	// Headers Additional HTTP headers
	Headers *map[string]string `json:"headers,omitempty"`
	Type    McpTransport1Type  `json:"type"`

	// Url Server URL
	Url string `json:"url"`
}

// McpTransport1Type defines model for McpTransport.1.Type.
type McpTransport1Type string

// Message A message in a conversation.
type Message struct {
	// Content Content blocks of the message
	Content []ContentBlock `json:"content"`

	// Role Role of a message sender in a conversation.
	Role Role `json:"role"`

	// SystemReminder Optional per-message system reminder injected by the control plane.
	// Wrapped in `<system-reminder>` tags and prepended to the user message.
	SystemReminder *string `json:"system_reminder,omitempty"`

	// Timestamp Timestamp when the message was created
	Timestamp time.Time `json:"timestamp"`
}

// MetricsResponse Complete metrics response for GET /metrics.
type MetricsResponse struct {
	// Agents Per-agent metrics
	Agents []MetricsSnapshot `json:"agents"`

	// Global Global metrics across all agents.
	Global GlobalMetrics `json:"global"`

	// Timestamp Timestamp of the snapshot
	Timestamp time.Time `json:"timestamp"`
}

// MetricsSnapshot Serializable snapshot of agent metrics for the /metrics endpoint.
type MetricsSnapshot struct {
	// ActiveConversations Currently active conversations
	ActiveConversations int64  `json:"active_conversations"`
	AgentId             String `json:"agent_id"`

	// AgentName Agent name
	AgentName string `json:"agent_name"`

	// AvgLatencyMs Average latency in milliseconds
	AvgLatencyMs float64 `json:"avg_latency_ms"`

	// CacheHitRatio cached_input_tokens / (input_tokens + cached_input_tokens).
	CacheHitRatio *float64 `json:"cache_hit_ratio,omitempty"`

	// CachedInputTokens Total input tokens served from the provider prompt cache (discounted).
	CachedInputTokens *int64 `json:"cached_input_tokens,omitempty"`

	// FailedRequests Failed requests
	FailedRequests int64 `json:"failed_requests"`

	// InputTokens Total non-cached input tokens consumed (full price).
	InputTokens int64 `json:"input_tokens"`

	// OutputTokens Total output tokens generated
	OutputTokens int64 `json:"output_tokens"`

	// ToolCallDetails Per-tool call metrics
	ToolCallDetails []ToolCallStatsSnapshot `json:"tool_call_details"`

	// ToolCalls Total tool calls executed
	ToolCalls int64 `json:"tool_calls"`

	// TotalConversations Total conversations ever created
	TotalConversations int64 `json:"total_conversations"`

	// TotalRequests Total LLM requests
	TotalRequests int64 `json:"total_requests"`

	// TotalTokens Total tokens (fresh input + cached input + output)
	TotalTokens int64 `json:"total_tokens"`
}

// ProviderConfig Configuration for an LLM provider.
type ProviderConfig struct {
	// ApiKey API key for authentication
	ApiKey string `json:"api_key"`

	// BaseUrl Optional custom endpoint URL
	BaseUrl *string `json:"base_url,omitempty"`

	// CacheTtl Prompt-cache TTL hint.
	//
	// Anthropic supports two TTLs today: 5-minute ephemeral (default,
	// 1.25× cache-write multiplier) and 1-hour extended (2.0× write, needs
	// `extended-cache-ttl-2025-04-11` beta header). Other providers ignore
	// this field — their caches are automatic and provider-managed.
	//
	// **Note (rig 0.31)**: `with_prompt_caching()` only emits the
	// `{"type": "ephemeral"}` breakpoint, which corresponds to the 5-minute
	// TTL. Setting `OneHour` here sends the beta header but does not yet
	// add `"ttl": "1h"` to the cache_control block — upgrade rig to get
	// true 1-hour writes. The field is wired now so the choice survives
	// the upgrade.
	CacheTtl *CacheTtl `json:"cache_ttl,omitempty"`

	// Model Model identifier (e.g., "gpt-4o", "claude-sonnet-4-20250514")
	Model string `json:"model"`

	// PromptCachingEnabled Whether to enable explicit prompt-cache breakpoints for providers
	// that require them (Anthropic today; MiniMax's Anthropic-shape
	// endpoint tomorrow). Implicit-cache providers (OpenAI, GLM, Gemini
	// 2.5 implicit, Kimi K2) ignore this — they cache unconditionally.
	PromptCachingEnabled *bool `json:"prompt_caching_enabled,omitempty"`

	// ProviderType Supported LLM provider types.
	ProviderType ProviderType `json:"provider_type"`
}

// ProviderSummary Provider info with secrets redacted.
type ProviderSummary struct {
	BaseUrl *string `json:"base_url,omitempty"`
	Model   string  `json:"model"`

	// ProviderType Supported LLM provider types.
	ProviderType ProviderType `json:"provider_type"`
}

// ProviderType Supported LLM provider types.
type ProviderType string

// PushAgentsRequest defines model for PushAgentsRequest.
type PushAgentsRequest struct {
	Agents []AgentDefinition `json:"agents"`
}

// PushAgentsResponse Response for pushing agents.
type PushAgentsResponse struct {
	// Loaded Number of agents loaded.
	Loaded int `json:"loaded"`
}

// PushDiffRequest defines model for PushDiffRequest.
type PushDiffRequest struct {
	Added   []AgentDefinition `json:"added"`
	Removed []string          `json:"removed"`
	Updated []AgentDefinition `json:"updated"`
}

// PushDiffResponse Response for pushing a diff.
type PushDiffResponse struct {
	// Added Number of agents added.
	Added int `json:"added"`

	// Removed Number of agents removed.
	Removed int `json:"removed"`

	// Updated Number of agents updated.
	Updated int `json:"updated"`
}

// RegisteredToolSummary Summary of a registered tool (built-in, MCP, or integration).
type RegisteredToolSummary struct {
	Description string `json:"description"`
	Name        string `json:"name"`
}

// RemoveAgentResponse Response for removing an agent.
type RemoveAgentResponse struct {
	// Status Status of the operation.
	Status string `json:"status"`
}

// RequirementCadence Describes which turns a tool requirement applies to.
type RequirementCadence struct {
	union json.RawMessage
}

// RequirementCadence0 Required on every turn.
type RequirementCadence0 struct {
	Type RequirementCadence0Type `json:"type"`
}

// RequirementCadence0Type defines model for RequirementCadence.0.Type.
type RequirementCadence0Type string

// RequirementCadence1 Required only on the very first turn of the conversation.
type RequirementCadence1 struct {
	Type RequirementCadence1Type `json:"type"`
}

// RequirementCadence1Type defines model for RequirementCadence.1.Type.
type RequirementCadence1Type string

// RequirementCadence2 Required whenever `n` turns have passed without the tool being called.
// The counter resets any time the tool is called (on- or off-cycle).
// So `n=3` means "never go more than 3 consecutive turns without
// calling this tool" — useful for periodic memory-retain / checkpoint
// patterns.
type RequirementCadence2 struct {
	N    int32                   `json:"n"`
	Type RequirementCadence2Type `json:"type"`
}

// RequirementCadence2Type defines model for RequirementCadence.2.Type.
type RequirementCadence2Type string

// RequirementEnforcement How bridge reacts when a tool requirement is violated.
type RequirementEnforcement string

// RequirementPosition Where in the turn's tool-call sequence the required call must appear.
type RequirementPosition string

// ResolveApprovalResponse Response for resolving an approval.
type ResolveApprovalResponse struct {
	// RequestId The ID of the resolved request.
	RequestId string `json:"request_id"`

	// Status Status of the resolution.
	Status string `json:"status"`
}

// Role Role of a message sender in a conversation.
type Role string

// SendMessageRequest Request body for creating a message.
type SendMessageRequest struct {
	// Content The text content to send. When [`full_message`](Self::full_message) is
	// also supplied, `content` is the LLM-visible summary; omit it to let
	// bridge auto-generate one from the first bytes of `full_message`.
	Content *string `json:"content,omitempty"`

	// FullMessage Optional full payload written to a per-conversation attachment file.
	// When present, bridge writes it to disk, appends a `<system-reminder>`
	// with the file path and tool-usage hint to `content`, and sends the
	// composed text to the LLM. Callers use this to offload large inputs
	// (stack traces, log dumps, file contents) without bloating the
	// agent's context on every turn.
	//
	// Failures (disk full, permission denied) do NOT reject the message —
	// bridge logs a warning and delivers `content` alone.
	FullMessage *string `json:"full_message,omitempty"`

	// SystemReminder Optional system reminder to inject with this message.
	// Will be wrapped in `<system-reminder>` tags and prepended to the user message.
	SystemReminder *string `json:"system_reminder,omitempty"`
}

// SendMessageResponse Response for sending a message.
type SendMessageResponse struct {
	// Status Status of the message acceptance.
	Status string `json:"status"`
}

// SkillDefinition Definition of a skill that can be activated by an agent.
type SkillDefinition struct {
	// Content Full skill prompt/instructions content (the SKILL.md body or single-content string).
	// Can contain template variables like {{args}}, $ARGUMENTS, $1, $2, etc.
	Content string `json:"content"`

	// Description Description of what the skill does
	Description string `json:"description"`

	// Files Supporting files: relative_path -> file_content.
	// Contains files referenced by the skill (e.g., "api-reference.md", "examples/ex1.md").
	Files       *map[string]string           `json:"files,omitempty"`
	Frontmatter *SkillDefinition_Frontmatter `json:"frontmatter,omitempty"`
	Id          String                       `json:"id"`

	// ParametersSchema Optional JSON Schema for structured parameters (for future use)
	ParametersSchema interface{} `json:"parameters_schema,omitempty"`

	// Source Where a skill originated from.
	Source *SkillSource `json:"source,omitempty"`

	// Title Human-readable title
	Title string `json:"title"`
}

// SkillDefinition_Frontmatter defines model for SkillDefinition.Frontmatter.
type SkillDefinition_Frontmatter struct {
	union json.RawMessage
}

// SkillFrontmatter Frontmatter configuration parsed from a SKILL.md YAML header.
//
// Only applicable to sources that support frontmatter (ClaudeCode, AgentSkills).
type SkillFrontmatter struct {
	// Agent Sub-agent type to delegate to when context is "fork".
	Agent *string `json:"agent,omitempty"`

	// AllowedTools List of tools the skill is allowed to use.
	AllowedTools *[]string `json:"allowed_tools,omitempty"`

	// ArgumentHint Hint text shown for the argument placeholder in autocomplete.
	ArgumentHint *string `json:"argument_hint,omitempty"`

	// Context Execution context. "fork" runs in an isolated subagent.
	Context *string `json:"context,omitempty"`

	// DisableModelInvocation When true, only users can invoke this skill (hidden from the model).
	DisableModelInvocation *bool `json:"disable_model_invocation,omitempty"`

	// Effort Reasoning effort level (e.g., "low", "medium", "high").
	Effort *string `json:"effort,omitempty"`

	// Paths Glob patterns for auto-activation on matching files.
	Paths *[]string `json:"paths,omitempty"`

	// Shell Shell to use for shell-related operations (e.g., "bash", "powershell").
	Shell *string `json:"shell,omitempty"`

	// UserInvocable When false, only the model can invoke this skill (hidden from slash commands).
	UserInvocable *bool `json:"user_invocable,omitempty"`
}

// SkillSource Where a skill originated from.
type SkillSource string

// String defines model for String.
type String = string

// SubAgentSummary Subagent summary for API responses.
type SubAgentSummary struct {
	// Config Configuration options for an agent.
	Config      AgentConfig           `json:"config"`
	Description *string               `json:"description,omitempty"`
	McpServers  []McpServerDefinition `json:"mcp_servers"`
	Name        string                `json:"name"`

	// Provider Provider info with secrets redacted.
	Provider ProviderSummary `json:"provider"`

	// RegisteredTools All tools registered and available to this subagent at runtime.
	RegisteredTools []RegisteredToolSummary `json:"registered_tools"`
	SystemPrompt    string                  `json:"system_prompt"`
	Tools           []ToolDefinition        `json:"tools"`
}

// ToolCall A request to call a tool.
type ToolCall struct {
	// Arguments Arguments to pass to the tool
	Arguments interface{} `json:"arguments"`

	// Id Unique identifier for this tool call
	Id string `json:"id"`

	// Name Name of the tool to call
	Name string `json:"name"`
}

// ToolCallStatsSnapshot Serializable snapshot of per-tool call statistics.
type ToolCallStatsSnapshot struct {
	// AvgLatencyMs Average latency in milliseconds
	AvgLatencyMs float64 `json:"avg_latency_ms"`

	// FailureResults Number of completions where the executor returned `Ok(...)` but the
	// result string described a failure (e.g. `Read` returned
	// `"Toolset error: File not found"`, `bash` returned a non-zero
	// `exit_code`, `edit` returned `{"error":"..."}`). The model received
	// the result as a normal tool message; only the content signals the
	// failure. Tracked separately so operators can distinguish bridge-side
	// dispatch errors (`failures`) from in-tool failures (`failure_results`).
	FailureResults *int64 `json:"failure_results,omitempty"`

	// Failures Number of completions where the executor itself returned `Err` —
	// process-level dispatch failure (tool not found, schema validation
	// rejected, permission denied, executor panic).
	Failures int64 `json:"failures"`

	// SuccessRate Success rate (successes / total_calls)
	SuccessRate float64 `json:"success_rate"`

	// Successes Number of completions that succeeded cleanly (executor returned `Ok`
	// AND the result content does not look like a failure shape).
	Successes int64 `json:"successes"`

	// ToolName Tool name
	ToolName string `json:"tool_name"`

	// TotalCalls Total number of calls to this tool
	TotalCalls int64 `json:"total_calls"`
}

// ToolDefinition Definition of a tool that an agent can use.
type ToolDefinition struct {
	// Description Human-readable description of what the tool does
	Description string `json:"description"`

	// Name Unique name of the tool
	Name string `json:"name"`

	// ParametersSchema JSON Schema for the tool's parameters
	ParametersSchema interface{} `json:"parameters_schema"`
}

// ToolPermission Permission level for a tool within an agent.
type ToolPermission string

// ToolRequirement A single tool-call requirement that bridge enforces at turn boundaries.
//
// Typical configurations:
//   - `journal_write` every turn: `{ tool: "journal_write" }` (all defaults).
//   - `memory_recall` at the start of every turn:
//     `{ tool: "memory_recall", position: "turn_start" }`.
//   - `memory_retain` at most every 3 turns:
//     `{ tool: "memory_retain", cadence: { type: "every_n_turns", n: 3 }, position: "turn_end" }`.
//
// Tool-name matching is flexible to reduce MCP verbosity: if `tool` contains
// `__`, match it verbatim; otherwise match any registered tool whose full
// name equals `tool` OR ends with `__<tool>`. So `"post_message"` matches
// an MCP tool exposed as `slack__post_message` without the user having to
// write the server prefix.
type ToolRequirement struct {
	// Cadence Describes which turns a tool requirement applies to.
	Cadence *RequirementCadence `json:"cadence,omitempty"`

	// Enforcement How bridge reacts when a tool requirement is violated.
	Enforcement *RequirementEnforcement `json:"enforcement,omitempty"`

	// MinCalls Minimum number of calls required in a qualifying turn. Default: 1.
	MinCalls *int32 `json:"min_calls,omitempty"`

	// Position Where in the turn's tool-call sequence the required call must appear.
	Position *RequirementPosition `json:"position,omitempty"`

	// ReminderMessage Custom reminder text injected when the requirement is violated.
	// Falls back to a generated default when unset.
	ReminderMessage *string `json:"reminder_message,omitempty"`

	// Tool Tool name to require (built-in, MCP, integration, or custom).
	Tool string `json:"tool"`
}

// ToolResult The result of a tool execution.
type ToolResult struct {
	// Content The result content
	Content string `json:"content"`

	// IsError Whether the tool execution resulted in an error
	IsError *bool `json:"is_error,omitempty"`

	// ToolCallId ID of the tool call this result corresponds to
	ToolCallId string `json:"tool_call_id"`
}

// UpsertAgentResponse Response for upserting an agent.
type UpsertAgentResponse struct {
	// Status Status of the operation: "unchanged", "updated", or "created".
	Status string `json:"status"`
}

// VerifierAgentConfig defines model for VerifierAgentConfig.
type VerifierAgentConfig struct {
	Blocking              *bool                         `json:"blocking,omitempty"`
	Enabled               *bool                         `json:"enabled,omitempty"`
	Fallback              *VerifierAgentConfig_Fallback `json:"fallback,omitempty"`
	MaxInputTokens        *int32                        `json:"max_input_tokens,omitempty"`
	MaxRepromptsPerTurn   *int32                        `json:"max_reprompts_per_turn,omitempty"`
	Primary               VerifierModel                 `json:"primary"`
	RequireHighConfidence *bool                         `json:"require_high_confidence,omitempty"`
	TimeoutMs             *int32                        `json:"timeout_ms,omitempty"`
}

// VerifierAgentConfig_Fallback defines model for VerifierAgentConfig.Fallback.
type VerifierAgentConfig_Fallback struct {
	union json.RawMessage
}

// VerifierModel defines model for VerifierModel.
type VerifierModel struct {
	ApiKey   string           `json:"api_key"`
	BaseUrl  *string          `json:"base_url,omitempty"`
	Model    string           `json:"model"`
	Provider VerifierProvider `json:"provider"`
}

// VerifierProvider defines model for VerifierProvider.
type VerifierProvider string

// CreateConversationJSONBody defines parameters for CreateConversation.
type CreateConversationJSONBody struct {
	union json.RawMessage
}

// CreateConversationJSONRequestBody defines body for CreateConversation for application/json ContentType.
type CreateConversationJSONRequestBody CreateConversationJSONBody

// BulkResolveApprovalsJSONRequestBody defines body for BulkResolveApprovals for application/json ContentType.
type BulkResolveApprovalsJSONRequestBody = BulkApprovalReply

// ResolveApprovalJSONRequestBody defines body for ResolveApproval for application/json ContentType.
type ResolveApprovalJSONRequestBody = ApprovalReply

// SendMessageJSONRequestBody defines body for SendMessage for application/json ContentType.
type SendMessageJSONRequestBody = SendMessageRequest

// PushAgentsJSONRequestBody defines body for PushAgents for application/json ContentType.
type PushAgentsJSONRequestBody = PushAgentsRequest

// UpsertAgentJSONRequestBody defines body for UpsertAgent for application/json ContentType.
type UpsertAgentJSONRequestBody = AgentDefinition

// HydrateConversationsJSONRequestBody defines body for HydrateConversations for application/json ContentType.
type HydrateConversationsJSONRequestBody = HydrateConversationsRequest

// PushDiffJSONRequestBody defines body for PushDiff for application/json ContentType.
type PushDiffJSONRequestBody = PushDiffRequest

// AsHistoryStripConfig returns the union data inside the AgentConfig_HistoryStrip as a HistoryStripConfig
func (t AgentConfig_HistoryStrip) AsHistoryStripConfig() (HistoryStripConfig, error) {
	var body HistoryStripConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromHistoryStripConfig overwrites any union data inside the AgentConfig_HistoryStrip as the provided HistoryStripConfig
func (t *AgentConfig_HistoryStrip) FromHistoryStripConfig(v HistoryStripConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeHistoryStripConfig performs a merge with any union data inside the AgentConfig_HistoryStrip, using the provided HistoryStripConfig
func (t *AgentConfig_HistoryStrip) MergeHistoryStripConfig(v HistoryStripConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t AgentConfig_HistoryStrip) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AgentConfig_HistoryStrip) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsImmortalConfig returns the union data inside the AgentConfig_Immortal as a ImmortalConfig
func (t AgentConfig_Immortal) AsImmortalConfig() (ImmortalConfig, error) {
	var body ImmortalConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromImmortalConfig overwrites any union data inside the AgentConfig_Immortal as the provided ImmortalConfig
func (t *AgentConfig_Immortal) FromImmortalConfig(v ImmortalConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeImmortalConfig performs a merge with any union data inside the AgentConfig_Immortal, using the provided ImmortalConfig
func (t *AgentConfig_Immortal) MergeImmortalConfig(v ImmortalConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t AgentConfig_Immortal) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AgentConfig_Immortal) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsVerifierAgentConfig returns the union data inside the AgentConfig_Verifier as a VerifierAgentConfig
func (t AgentConfig_Verifier) AsVerifierAgentConfig() (VerifierAgentConfig, error) {
	var body VerifierAgentConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromVerifierAgentConfig overwrites any union data inside the AgentConfig_Verifier as the provided VerifierAgentConfig
func (t *AgentConfig_Verifier) FromVerifierAgentConfig(v VerifierAgentConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeVerifierAgentConfig performs a merge with any union data inside the AgentConfig_Verifier, using the provided VerifierAgentConfig
func (t *AgentConfig_Verifier) MergeVerifierAgentConfig(v VerifierAgentConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t AgentConfig_Verifier) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AgentConfig_Verifier) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsArtifactsConfig returns the union data inside the AgentDefinition_Artifacts as a ArtifactsConfig
func (t AgentDefinition_Artifacts) AsArtifactsConfig() (ArtifactsConfig, error) {
	var body ArtifactsConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromArtifactsConfig overwrites any union data inside the AgentDefinition_Artifacts as the provided ArtifactsConfig
func (t *AgentDefinition_Artifacts) FromArtifactsConfig(v ArtifactsConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeArtifactsConfig performs a merge with any union data inside the AgentDefinition_Artifacts, using the provided ArtifactsConfig
func (t *AgentDefinition_Artifacts) MergeArtifactsConfig(v ArtifactsConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t AgentDefinition_Artifacts) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AgentDefinition_Artifacts) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsArtifactsConfig returns the union data inside the AgentResponse_Artifacts as a ArtifactsConfig
func (t AgentResponse_Artifacts) AsArtifactsConfig() (ArtifactsConfig, error) {
	var body ArtifactsConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromArtifactsConfig overwrites any union data inside the AgentResponse_Artifacts as the provided ArtifactsConfig
func (t *AgentResponse_Artifacts) FromArtifactsConfig(v ArtifactsConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeArtifactsConfig performs a merge with any union data inside the AgentResponse_Artifacts, using the provided ArtifactsConfig
func (t *AgentResponse_Artifacts) MergeArtifactsConfig(v ArtifactsConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t AgentResponse_Artifacts) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AgentResponse_Artifacts) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsContentBlock0 returns the union data inside the ContentBlock as a ContentBlock0
func (t ContentBlock) AsContentBlock0() (ContentBlock0, error) {
	var body ContentBlock0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromContentBlock0 overwrites any union data inside the ContentBlock as the provided ContentBlock0
func (t *ContentBlock) FromContentBlock0(v ContentBlock0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeContentBlock0 performs a merge with any union data inside the ContentBlock, using the provided ContentBlock0
func (t *ContentBlock) MergeContentBlock0(v ContentBlock0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsContentBlock1 returns the union data inside the ContentBlock as a ContentBlock1
func (t ContentBlock) AsContentBlock1() (ContentBlock1, error) {
	var body ContentBlock1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromContentBlock1 overwrites any union data inside the ContentBlock as the provided ContentBlock1
func (t *ContentBlock) FromContentBlock1(v ContentBlock1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeContentBlock1 performs a merge with any union data inside the ContentBlock, using the provided ContentBlock1
func (t *ContentBlock) MergeContentBlock1(v ContentBlock1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsContentBlock2 returns the union data inside the ContentBlock as a ContentBlock2
func (t ContentBlock) AsContentBlock2() (ContentBlock2, error) {
	var body ContentBlock2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromContentBlock2 overwrites any union data inside the ContentBlock as the provided ContentBlock2
func (t *ContentBlock) FromContentBlock2(v ContentBlock2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeContentBlock2 performs a merge with any union data inside the ContentBlock, using the provided ContentBlock2
func (t *ContentBlock) MergeContentBlock2(v ContentBlock2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsContentBlock3 returns the union data inside the ContentBlock as a ContentBlock3
func (t ContentBlock) AsContentBlock3() (ContentBlock3, error) {
	var body ContentBlock3
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromContentBlock3 overwrites any union data inside the ContentBlock as the provided ContentBlock3
func (t *ContentBlock) FromContentBlock3(v ContentBlock3) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeContentBlock3 performs a merge with any union data inside the ContentBlock, using the provided ContentBlock3
func (t *ContentBlock) MergeContentBlock3(v ContentBlock3) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ContentBlock) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ContentBlock) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsProviderConfig returns the union data inside the CreateConversationRequest_Provider as a ProviderConfig
func (t CreateConversationRequest_Provider) AsProviderConfig() (ProviderConfig, error) {
	var body ProviderConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromProviderConfig overwrites any union data inside the CreateConversationRequest_Provider as the provided ProviderConfig
func (t *CreateConversationRequest_Provider) FromProviderConfig(v ProviderConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeProviderConfig performs a merge with any union data inside the CreateConversationRequest_Provider, using the provided ProviderConfig
func (t *CreateConversationRequest_Provider) MergeProviderConfig(v ProviderConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t CreateConversationRequest_Provider) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CreateConversationRequest_Provider) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsMcpTransport0 returns the union data inside the McpTransport as a McpTransport0
func (t McpTransport) AsMcpTransport0() (McpTransport0, error) {
	var body McpTransport0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMcpTransport0 overwrites any union data inside the McpTransport as the provided McpTransport0
func (t *McpTransport) FromMcpTransport0(v McpTransport0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMcpTransport0 performs a merge with any union data inside the McpTransport, using the provided McpTransport0
func (t *McpTransport) MergeMcpTransport0(v McpTransport0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMcpTransport1 returns the union data inside the McpTransport as a McpTransport1
func (t McpTransport) AsMcpTransport1() (McpTransport1, error) {
	var body McpTransport1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMcpTransport1 overwrites any union data inside the McpTransport as the provided McpTransport1
func (t *McpTransport) FromMcpTransport1(v McpTransport1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMcpTransport1 performs a merge with any union data inside the McpTransport, using the provided McpTransport1
func (t *McpTransport) MergeMcpTransport1(v McpTransport1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t McpTransport) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *McpTransport) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsRequirementCadence0 returns the union data inside the RequirementCadence as a RequirementCadence0
func (t RequirementCadence) AsRequirementCadence0() (RequirementCadence0, error) {
	var body RequirementCadence0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRequirementCadence0 overwrites any union data inside the RequirementCadence as the provided RequirementCadence0
func (t *RequirementCadence) FromRequirementCadence0(v RequirementCadence0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRequirementCadence0 performs a merge with any union data inside the RequirementCadence, using the provided RequirementCadence0
func (t *RequirementCadence) MergeRequirementCadence0(v RequirementCadence0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRequirementCadence1 returns the union data inside the RequirementCadence as a RequirementCadence1
func (t RequirementCadence) AsRequirementCadence1() (RequirementCadence1, error) {
	var body RequirementCadence1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRequirementCadence1 overwrites any union data inside the RequirementCadence as the provided RequirementCadence1
func (t *RequirementCadence) FromRequirementCadence1(v RequirementCadence1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRequirementCadence1 performs a merge with any union data inside the RequirementCadence, using the provided RequirementCadence1
func (t *RequirementCadence) MergeRequirementCadence1(v RequirementCadence1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRequirementCadence2 returns the union data inside the RequirementCadence as a RequirementCadence2
func (t RequirementCadence) AsRequirementCadence2() (RequirementCadence2, error) {
	var body RequirementCadence2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRequirementCadence2 overwrites any union data inside the RequirementCadence as the provided RequirementCadence2
func (t *RequirementCadence) FromRequirementCadence2(v RequirementCadence2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRequirementCadence2 performs a merge with any union data inside the RequirementCadence, using the provided RequirementCadence2
func (t *RequirementCadence) MergeRequirementCadence2(v RequirementCadence2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t RequirementCadence) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *RequirementCadence) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsSkillFrontmatter returns the union data inside the SkillDefinition_Frontmatter as a SkillFrontmatter
func (t SkillDefinition_Frontmatter) AsSkillFrontmatter() (SkillFrontmatter, error) {
	var body SkillFrontmatter
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSkillFrontmatter overwrites any union data inside the SkillDefinition_Frontmatter as the provided SkillFrontmatter
func (t *SkillDefinition_Frontmatter) FromSkillFrontmatter(v SkillFrontmatter) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSkillFrontmatter performs a merge with any union data inside the SkillDefinition_Frontmatter, using the provided SkillFrontmatter
func (t *SkillDefinition_Frontmatter) MergeSkillFrontmatter(v SkillFrontmatter) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t SkillDefinition_Frontmatter) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *SkillDefinition_Frontmatter) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsVerifierModel returns the union data inside the VerifierAgentConfig_Fallback as a VerifierModel
func (t VerifierAgentConfig_Fallback) AsVerifierModel() (VerifierModel, error) {
	var body VerifierModel
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromVerifierModel overwrites any union data inside the VerifierAgentConfig_Fallback as the provided VerifierModel
func (t *VerifierAgentConfig_Fallback) FromVerifierModel(v VerifierModel) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeVerifierModel performs a merge with any union data inside the VerifierAgentConfig_Fallback, using the provided VerifierModel
func (t *VerifierAgentConfig_Fallback) MergeVerifierModel(v VerifierModel) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t VerifierAgentConfig_Fallback) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *VerifierAgentConfig_Fallback) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsCreateConversationRequest returns the union data inside the CreateConversationJSONBody as a CreateConversationRequest
func (t CreateConversationJSONBody) AsCreateConversationRequest() (CreateConversationRequest, error) {
	var body CreateConversationRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCreateConversationRequest overwrites any union data inside the CreateConversationJSONBody as the provided CreateConversationRequest
func (t *CreateConversationJSONBody) FromCreateConversationRequest(v CreateConversationRequest) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCreateConversationRequest performs a merge with any union data inside the CreateConversationJSONBody, using the provided CreateConversationRequest
func (t *CreateConversationJSONBody) MergeCreateConversationRequest(v CreateConversationRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t CreateConversationJSONBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CreateConversationJSONBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
