// Package bridge provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package bridge

import (
	"encoding/json"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	BearerScopes bearerContextKey = "bearer.Scopes"
)

// Defines values for ApprovalDecision.
const (
	ApprovalDecisionApprove ApprovalDecision = "approve"
	ApprovalDecisionDeny    ApprovalDecision = "deny"
)

// Valid indicates whether the value is a known member of the ApprovalDecision enum.
func (e ApprovalDecision) Valid() bool {
	switch e {
	case ApprovalDecisionApprove:
		return true
	case ApprovalDecisionDeny:
		return true
	default:
		return false
	}
}

// Defines values for ApprovalStatus.
const (
	Approved ApprovalStatus = "approved"
	Denied   ApprovalStatus = "denied"
	Pending  ApprovalStatus = "pending"
)

// Valid indicates whether the value is a known member of the ApprovalStatus enum.
func (e ApprovalStatus) Valid() bool {
	switch e {
	case Approved:
		return true
	case Denied:
		return true
	case Pending:
		return true
	default:
		return false
	}
}

// Defines values for ContentBlock0Type.
const (
	Text ContentBlock0Type = "text"
)

// Valid indicates whether the value is a known member of the ContentBlock0Type enum.
func (e ContentBlock0Type) Valid() bool {
	switch e {
	case Text:
		return true
	default:
		return false
	}
}

// Defines values for ContentBlock1Type.
const (
	ContentBlock1TypeToolCall ContentBlock1Type = "tool_call"
)

// Valid indicates whether the value is a known member of the ContentBlock1Type enum.
func (e ContentBlock1Type) Valid() bool {
	switch e {
	case ContentBlock1TypeToolCall:
		return true
	default:
		return false
	}
}

// Defines values for ContentBlock2Type.
const (
	ContentBlock2TypeToolResult ContentBlock2Type = "tool_result"
)

// Valid indicates whether the value is a known member of the ContentBlock2Type enum.
func (e ContentBlock2Type) Valid() bool {
	switch e {
	case ContentBlock2TypeToolResult:
		return true
	default:
		return false
	}
}

// Defines values for ContentBlock3Type.
const (
	Image ContentBlock3Type = "image"
)

// Valid indicates whether the value is a known member of the ContentBlock3Type enum.
func (e ContentBlock3Type) Valid() bool {
	switch e {
	case Image:
		return true
	default:
		return false
	}
}

// Defines values for Harness.
const (
	Claude   Harness = "claude"
	OpenCode Harness = "open_code"
)

// Valid indicates whether the value is a known member of the Harness enum.
func (e Harness) Valid() bool {
	switch e {
	case Claude:
		return true
	case OpenCode:
		return true
	default:
		return false
	}
}

// Defines values for McpTransport0Type.
const (
	Stdio McpTransport0Type = "stdio"
)

// Valid indicates whether the value is a known member of the McpTransport0Type enum.
func (e McpTransport0Type) Valid() bool {
	switch e {
	case Stdio:
		return true
	default:
		return false
	}
}

// Defines values for McpTransport1Type.
const (
	StreamableHttp McpTransport1Type = "streamable_http"
)

// Valid indicates whether the value is a known member of the McpTransport1Type enum.
func (e McpTransport1Type) Valid() bool {
	switch e {
	case StreamableHttp:
		return true
	default:
		return false
	}
}

// Defines values for ProviderType.
const (
	Anthropic ProviderType = "anthropic"
	Cohere    ProviderType = "cohere"
	Custom    ProviderType = "custom"
	DeepSeek  ProviderType = "deep_seek"
	Fireworks ProviderType = "fireworks"
	Google    ProviderType = "google"
	Groq      ProviderType = "groq"
	Mistral   ProviderType = "mistral"
	Ollama    ProviderType = "ollama"
	OpenAi    ProviderType = "open_ai"
	Together  ProviderType = "together"
	XAi       ProviderType = "x_ai"
)

// Valid indicates whether the value is a known member of the ProviderType enum.
func (e ProviderType) Valid() bool {
	switch e {
	case Anthropic:
		return true
	case Cohere:
		return true
	case Custom:
		return true
	case DeepSeek:
		return true
	case Fireworks:
		return true
	case Google:
		return true
	case Groq:
		return true
	case Mistral:
		return true
	case Ollama:
		return true
	case OpenAi:
		return true
	case Together:
		return true
	case XAi:
		return true
	default:
		return false
	}
}

// Defines values for Role.
const (
	Assistant Role = "assistant"
	System    Role = "system"
	Tool      Role = "tool"
	User      Role = "user"
)

// Valid indicates whether the value is a known member of the Role enum.
func (e Role) Valid() bool {
	switch e {
	case Assistant:
		return true
	case System:
		return true
	case Tool:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Defines values for SkillSource.
const (
	AgentSkills   SkillSource = "agent_skills"
	ClaudeCode    SkillSource = "claude_code"
	ControlPlane  SkillSource = "control_plane"
	CursorRules   SkillSource = "cursor_rules"
	GitHubCopilot SkillSource = "git_hub_copilot"
	WindsurfRules SkillSource = "windsurf_rules"
)

// Valid indicates whether the value is a known member of the SkillSource enum.
func (e SkillSource) Valid() bool {
	switch e {
	case AgentSkills:
		return true
	case ClaudeCode:
		return true
	case ControlPlane:
		return true
	case CursorRules:
		return true
	case GitHubCopilot:
		return true
	case WindsurfRules:
		return true
	default:
		return false
	}
}

// Defines values for ToolPermission.
const (
	ToolPermissionAllow           ToolPermission = "allow"
	ToolPermissionDeny            ToolPermission = "deny"
	ToolPermissionRequireApproval ToolPermission = "require_approval"
)

// Valid indicates whether the value is a known member of the ToolPermission enum.
func (e ToolPermission) Valid() bool {
	switch e {
	case ToolPermissionAllow:
		return true
	case ToolPermissionDeny:
		return true
	case ToolPermissionRequireApproval:
		return true
	default:
		return false
	}
}

// AbortConversationResponse Response for aborting a conversation turn.
type AbortConversationResponse struct {
	// Status Status of the abort operation.
	Status string `json:"status"`
}

// AgentConfig Per-agent configuration written into the harness's settings file at
// session start. Every field is harness-agnostic in shape — the adapter
// is responsible for translating it into the harness-native config
// (`~/.claude/settings.json`, `~/.config/opencode/opencode.json`, etc.).
type AgentConfig struct {
	// AllowedTools Tool allowlist. Empty = every tool the harness exposes is allowed.
	// Names are harness-native (e.g. `"Read"`, `"Bash"`, `"mcp__github__*"`).
	AllowedTools *[]string `json:"allowed_tools,omitempty"`

	// DisabledTools Tool denylist. Always wins over [`Self::allowed_tools`].
	DisabledTools *[]string `json:"disabled_tools,omitempty"`

	// Env Extra environment variables merged into the harness process at
	// session start. Useful for custom proxy endpoints, telemetry
	// flags, or harness-specific feature flags.
	Env *map[string]string `json:"env,omitempty"`

	// FallbackModel Optional fallback model the harness routes to when the primary
	// model errors or is rate-limited.
	FallbackModel *string `json:"fallback_model,omitempty"`

	// MaxTokens Maximum tokens per assistant response.
	MaxTokens *int32 `json:"max_tokens,omitempty"`

	// MaxTurns Maximum conversation turns before bridge stops the loop.
	MaxTurns *int32 `json:"max_turns,omitempty"`

	// PermissionMode Permission mode written to the harness config. Harness-specific
	// string. Claude Code: `"default"` / `"acceptEdits"` /
	// `"bypassPermissions"` / `"plan"`. OpenCode has its own set.
	PermissionMode *string `json:"permission_mode,omitempty"`

	// ReasoningEffort Reasoning effort hint. Forwarded to harnesses that support it
	// (Claude Code thinking budget, OpenCode reasoning effort).
	// Conventional values: `"low"`, `"medium"`, `"high"`.
	ReasoningEffort *string `json:"reasoning_effort,omitempty"`

	// SmallFastModel Optional faster/cheaper model used by the harness for utility
	// calls (summarization, title generation, etc.).
	SmallFastModel *string `json:"small_fast_model,omitempty"`

	// Temperature Sampling temperature for the underlying model.
	Temperature *float64 `json:"temperature,omitempty"`
}

// AgentDefinition Complete definition of an AI agent fetched from the control plane.
//
// Bridge persists the definition; the harness adapter (one of the
// [`Harness`] variants) reads it and drives the underlying CLI process.
// MCP servers and skills are passed through to the harness — bridge does
// not execute tools itself.
type AgentDefinition struct {
	// Config Per-agent configuration written into the harness's settings file at
	// session start. Every field is harness-agnostic in shape — the adapter
	// is responsible for translating it into the harness-native config
	// (`~/.claude/settings.json`, `~/.config/opencode/opencode.json`, etc.).
	Config *AgentConfig `json:"config,omitempty"`

	// Description Human-readable description of the agent's purpose and capabilities.
	Description *string `json:"description,omitempty"`

	// Harness Which underlying coding-agent harness this agent runs against.
	Harness Harness `json:"harness"`
	Id      String  `json:"id"`

	// McpServers MCP server connections passed through to the harness as `--mcp-config`.
	McpServers *[]McpServerDefinition `json:"mcp_servers,omitempty"`

	// Name Human-readable agent name
	Name string `json:"name"`

	// Permissions Per-tool permission overrides. Drives the bridge approvals API
	// (`/agents/{id}/conversations/{cid}/approvals`). Tools not listed
	// default to `Allow`.
	Permissions *map[string]ToolPermission `json:"permissions,omitempty"`

	// Provider Configuration for an LLM provider.
	//
	// Materialized into the harness's expected env vars / config file at
	// session start. Caching is delegated entirely to the harness.
	Provider ProviderConfig `json:"provider"`

	// Skills Skills written to the harness's skill discovery directory at session start
	// (e.g. `~/.claude/skills/<id>/SKILL.md` for Claude Code).
	Skills *[]SkillDefinition `json:"skills,omitempty"`

	// SystemPrompt System prompt for the agent (mapped to the harness's system-prompt input)
	SystemPrompt string `json:"system_prompt"`

	// UpdatedAt Last updated timestamp for change detection
	UpdatedAt *string `json:"updated_at,omitempty"`

	// Version Version field for change detection during sync
	Version *string `json:"version,omitempty"`

	// WebhookSecret Webhook secret for HMAC signing
	WebhookSecret *string `json:"webhook_secret,omitempty"`

	// WebhookUrl Webhook URL for event delivery
	WebhookUrl *string `json:"webhook_url,omitempty"`
}

// AgentResponse Full agent response — returned by both list and detail endpoints.
// System prompts may be truncated on the list endpoint.
type AgentResponse struct {
	ActiveConversations int `json:"active_conversations"`

	// Config Per-agent configuration written into the harness's settings file at
	// session start. Every field is harness-agnostic in shape — the adapter
	// is responsible for translating it into the harness-native config
	// (`~/.claude/settings.json`, `~/.config/opencode/opencode.json`, etc.).
	Config      AgentConfig `json:"config"`
	Description *string     `json:"description,omitempty"`

	// Harness Which underlying coding-agent harness this agent runs against.
	Harness    Harness               `json:"harness"`
	Id         string                `json:"id"`
	McpServers []McpServerDefinition `json:"mcp_servers"`

	// Metrics Serializable snapshot of agent metrics for the /metrics endpoint.
	Metrics     MetricsSnapshot           `json:"metrics"`
	Name        string                    `json:"name"`
	Permissions map[string]ToolPermission `json:"permissions"`

	// Provider Provider info with secrets redacted.
	Provider     ProviderSummary   `json:"provider"`
	Skills       []SkillDefinition `json:"skills"`
	SystemPrompt string            `json:"system_prompt"`
	UpdatedAt    *string           `json:"updated_at,omitempty"`
	Version      *string           `json:"version,omitempty"`
	WebhookUrl   *string           `json:"webhook_url,omitempty"`
}

// ApprovalDecision The user's decision on an approval request.
type ApprovalDecision string

// ApprovalReply HTTP request body for resolving a single approval.
type ApprovalReply struct {
	// Decision The user's decision on an approval request.
	Decision ApprovalDecision `json:"decision"`

	// Reason Optional message explaining why the tool call was denied.
	// Included in the error returned to the LLM so the agent can adjust.
	Reason *string `json:"reason,omitempty"`
}

// ApprovalRequest A pending approval request for a tool call.
type ApprovalRequest struct {
	// AgentId Agent that initiated the tool call.
	AgentId string `json:"agent_id"`

	// Arguments Arguments passed to the tool.
	Arguments interface{} `json:"arguments"`

	// ConversationId Conversation in which the tool call occurred.
	ConversationId string `json:"conversation_id"`

	// CreatedAt When the approval request was created.
	CreatedAt time.Time `json:"created_at"`

	// Id Unique ID for this approval request.
	Id string `json:"id"`

	// Status Status of an approval request.
	Status ApprovalStatus `json:"status"`

	// ToolCallId The LLM's tool call ID.
	ToolCallId string `json:"tool_call_id"`

	// ToolName Name of the tool being called.
	ToolName string `json:"tool_name"`
}

// ApprovalStatus Status of an approval request.
type ApprovalStatus string

// BulkApprovalReply HTTP request body for resolving multiple approvals at once.
type BulkApprovalReply struct {
	// Decision The user's decision on an approval request.
	Decision ApprovalDecision `json:"decision"`

	// Reason Optional message explaining why the tool calls were denied.
	Reason     *string  `json:"reason,omitempty"`
	RequestIds []string `json:"request_ids"`
}

// BulkResolveApprovalsResponse Response for bulk resolving approvals.
type BulkResolveApprovalsResponse struct {
	// NotFound List of request IDs that were not found.
	NotFound []string `json:"not_found"`

	// Resolved List of request IDs that were successfully resolved.
	Resolved []string `json:"resolved"`
}

// ContentBlock A content block within a message.
type ContentBlock struct {
	union json.RawMessage
}

// ContentBlock0 Plain text content
type ContentBlock0 struct {
	// Text The text content
	Text string            `json:"text"`
	Type ContentBlock0Type `json:"type"`
}

// ContentBlock0Type defines model for ContentBlock.0.Type.
type ContentBlock0Type string

// ContentBlock1 defines model for .
type ContentBlock1 struct {
	// Arguments Arguments to pass to the tool
	Arguments interface{} `json:"arguments"`

	// Id Unique identifier for this tool call
	Id string `json:"id"`

	// Name Name of the tool to call
	Name string            `json:"name"`
	Type ContentBlock1Type `json:"type"`
}

// ContentBlock1Type defines model for ContentBlock.1.Type.
type ContentBlock1Type string

// ContentBlock2 defines model for .
type ContentBlock2 struct {
	// Content The result content
	Content string `json:"content"`

	// IsError Whether the tool execution resulted in an error
	IsError *bool `json:"is_error,omitempty"`

	// ToolCallId ID of the tool call this result corresponds to
	ToolCallId string            `json:"tool_call_id"`
	Type       ContentBlock2Type `json:"type"`
}

// ContentBlock2Type defines model for ContentBlock.2.Type.
type ContentBlock2Type string

// ContentBlock3 An image attachment
type ContentBlock3 struct {
	// Data Base64-encoded image data
	Data string `json:"data"`

	// MediaType MIME type of the image
	MediaType string            `json:"media_type"`
	Type      ContentBlock3Type `json:"type"`
}

// ContentBlock3Type defines model for ContentBlock.3.Type.
type ContentBlock3Type string

// ConversationRecord A conversation with its full message history, as returned by the control plane.
type ConversationRecord struct {
	// AgentId Agent that owns this conversation.
	AgentId string `json:"agent_id"`

	// CreatedAt When the conversation was created.
	CreatedAt time.Time `json:"created_at"`
	Id        String    `json:"id"`

	// Messages Full message history.
	Messages []Message `json:"messages"`

	// Title Optional human-readable title.
	Title *string `json:"title,omitempty"`

	// UpdatedAt When the conversation was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// CreateConversationRequest Optional request body for creating a conversation with per-call overrides.
type CreateConversationRequest struct {
	// ApiKey When provided, overrides the agent's LLM API key for this conversation only.
	// For full provider/model override, use the `provider` field instead.
	ApiKey *string `json:"api_key,omitempty"`

	// McpServers Additional MCP servers to load for this conversation only.
	// Merged into the harness's MCP configuration at session start and torn
	// down when the conversation ends.
	McpServers *[]McpServerDefinition `json:"mcp_servers,omitempty"`

	// Provider Configuration for an LLM provider.
	//
	// Materialized into the harness's expected env vars / config file at
	// session start. Caching is delegated entirely to the harness.
	Provider *ProviderConfig `json:"provider,omitempty"`
}

// CreateConversationResponse Response for creating a conversation.
type CreateConversationResponse struct {
	// ConversationId The ID of the newly created conversation.
	ConversationId string `json:"conversation_id"`

	// StreamUrl The URL to stream events from this conversation.
	StreamUrl string `json:"stream_url"`
}

// EndConversationResponse Response for ending a conversation.
type EndConversationResponse struct {
	// Status Status of the end operation.
	Status string `json:"status"`
}

// GlobalMetrics Global metrics across all agents.
type GlobalMetrics struct {
	// TotalActiveConversations Total active conversations across all agents
	TotalActiveConversations int64 `json:"total_active_conversations"`

	// TotalAgents Total number of loaded agents
	TotalAgents int `json:"total_agents"`

	// UptimeSecs Seconds since the runtime started
	UptimeSecs int64 `json:"uptime_secs"`
}

// Harness Which underlying coding-agent harness this agent runs against.
type Harness string

// HealthResponse Health check response.
type HealthResponse struct {
	// Status Health status - always "ok" if the server is running.
	Status string `json:"status"`

	// UptimeSecs Server uptime in seconds.
	UptimeSecs int64 `json:"uptime_secs"`
}

// HydrateConversationsRequest defines model for HydrateConversationsRequest.
type HydrateConversationsRequest struct {
	Conversations []ConversationRecord `json:"conversations"`
}

// HydrateConversationsResponse Response for hydrating conversations.
type HydrateConversationsResponse struct {
	// Hydrated Number of conversations hydrated.
	Hydrated int `json:"hydrated"`
}

// McpServerDefinition Definition of an MCP server that an agent connects to.
type McpServerDefinition struct {
	// Name Name of the MCP server
	Name string `json:"name"`

	// Transport Transport configuration for MCP server connections.
	Transport McpTransport `json:"transport"`
}

// McpTransport Transport configuration for MCP server connections.
type McpTransport struct {
	union json.RawMessage
}

// McpTransport0 Stdio transport — spawns a child process
type McpTransport0 struct {
	// Args Command arguments
	Args *[]string `json:"args,omitempty"`

	// Command Command to execute
	Command string `json:"command"`

	// Env Environment variables for the process
	Env  *map[string]string `json:"env,omitempty"`
	Type McpTransport0Type  `json:"type"`
}

// McpTransport0Type defines model for McpTransport.0.Type.
type McpTransport0Type string

// McpTransport1 Streamable HTTP transport — connects to an HTTP endpoint
type McpTransport1 struct {
	// Headers Additional HTTP headers
	Headers *map[string]string `json:"headers,omitempty"`
	Type    McpTransport1Type  `json:"type"`

	// Url Server URL
	Url string `json:"url"`
}

// McpTransport1Type defines model for McpTransport.1.Type.
type McpTransport1Type string

// Message A message in a conversation.
type Message struct {
	// Content Content blocks of the message
	Content []ContentBlock `json:"content"`

	// Role Role of a message sender in a conversation.
	Role Role `json:"role"`

	// SystemReminder Optional per-message system reminder injected by the control plane.
	// Wrapped in `<system-reminder>` tags and prepended to the user message.
	SystemReminder *string `json:"system_reminder,omitempty"`

	// Timestamp Timestamp when the message was created
	Timestamp time.Time `json:"timestamp"`
}

// MetricsResponse Complete metrics response for GET /metrics.
type MetricsResponse struct {
	// Agents Per-agent metrics
	Agents []MetricsSnapshot `json:"agents"`

	// Global Global metrics across all agents.
	Global GlobalMetrics `json:"global"`

	// Timestamp Timestamp of the snapshot
	Timestamp time.Time `json:"timestamp"`
}

// MetricsSnapshot Serializable snapshot of agent metrics for the /metrics endpoint.
type MetricsSnapshot struct {
	// ActiveConversations Currently active conversations
	ActiveConversations int64  `json:"active_conversations"`
	AgentId             String `json:"agent_id"`

	// AgentName Agent name
	AgentName string `json:"agent_name"`

	// AvgLatencyMs Average latency in milliseconds
	AvgLatencyMs float64 `json:"avg_latency_ms"`

	// CacheHitRatio cached_input_tokens / (input_tokens + cached_input_tokens).
	CacheHitRatio *float64 `json:"cache_hit_ratio,omitempty"`

	// CachedInputTokens Total input tokens served from the provider prompt cache (discounted).
	CachedInputTokens *int64 `json:"cached_input_tokens,omitempty"`

	// FailedRequests Failed requests
	FailedRequests int64 `json:"failed_requests"`

	// InputTokens Total non-cached input tokens consumed (full price).
	InputTokens int64 `json:"input_tokens"`

	// OutputTokens Total output tokens generated
	OutputTokens int64 `json:"output_tokens"`

	// ToolCallDetails Per-tool call metrics
	ToolCallDetails []ToolCallStatsSnapshot `json:"tool_call_details"`

	// ToolCalls Total tool calls executed
	ToolCalls int64 `json:"tool_calls"`

	// TotalConversations Total conversations ever created
	TotalConversations int64 `json:"total_conversations"`

	// TotalRequests Total LLM requests
	TotalRequests int64 `json:"total_requests"`

	// TotalTokens Total tokens (fresh input + cached input + output)
	TotalTokens int64 `json:"total_tokens"`
}

// ProviderConfig Configuration for an LLM provider.
//
// Materialized into the harness's expected env vars / config file at
// session start. Caching is delegated entirely to the harness.
type ProviderConfig struct {
	// ApiKey API key for authentication
	ApiKey string `json:"api_key"`

	// BaseUrl Optional custom endpoint URL
	BaseUrl *string `json:"base_url,omitempty"`

	// Model Model identifier (e.g., "gpt-4o", "claude-sonnet-4-20250514")
	Model string `json:"model"`

	// ProviderType Supported LLM provider types.
	ProviderType ProviderType `json:"provider_type"`
}

// ProviderSummary Provider info with secrets redacted.
type ProviderSummary struct {
	BaseUrl *string `json:"base_url,omitempty"`
	Model   string  `json:"model"`

	// ProviderType Supported LLM provider types.
	ProviderType ProviderType `json:"provider_type"`
}

// ProviderType Supported LLM provider types.
type ProviderType string

// PushAgentsRequest defines model for PushAgentsRequest.
type PushAgentsRequest struct {
	Agents []AgentDefinition `json:"agents"`
}

// PushAgentsResponse Response for pushing agents.
type PushAgentsResponse struct {
	// Loaded Number of agents loaded.
	Loaded int `json:"loaded"`
}

// PushDiffRequest defines model for PushDiffRequest.
type PushDiffRequest struct {
	Added   []AgentDefinition `json:"added"`
	Removed []string          `json:"removed"`
	Updated []AgentDefinition `json:"updated"`
}

// PushDiffResponse Response for pushing a diff.
type PushDiffResponse struct {
	// Added Number of agents added.
	Added int `json:"added"`

	// Removed Number of agents removed.
	Removed int `json:"removed"`

	// Updated Number of agents updated.
	Updated int `json:"updated"`
}

// RemoveAgentResponse Response for removing an agent.
type RemoveAgentResponse struct {
	// Status Status of the operation.
	Status string `json:"status"`
}

// ResolveApprovalResponse Response for resolving an approval.
type ResolveApprovalResponse struct {
	// RequestId The ID of the resolved request.
	RequestId string `json:"request_id"`

	// Status Status of the resolution.
	Status string `json:"status"`
}

// Role Role of a message sender in a conversation.
type Role string

// SendMessageRequest Request body for creating a message.
type SendMessageRequest struct {
	// Content The text content to send. When [`full_message`](Self::full_message) is
	// also supplied, `content` is the LLM-visible summary; omit it to let
	// bridge auto-generate one from the first bytes of `full_message`.
	Content *string `json:"content,omitempty"`

	// FullMessage Optional full payload written to a per-conversation attachment file.
	// When present, bridge writes it to disk, appends a `<system-reminder>`
	// with the file path and tool-usage hint to `content`, and sends the
	// composed text to the LLM. Callers use this to offload large inputs
	// (stack traces, log dumps, file contents) without bloating the
	// agent's context on every turn.
	//
	// Failures (disk full, permission denied) do NOT reject the message —
	// bridge logs a warning and delivers `content` alone.
	FullMessage *string `json:"full_message,omitempty"`

	// SystemReminder Optional system reminder to inject with this message.
	// Will be wrapped in `<system-reminder>` tags and prepended to the user message.
	SystemReminder *string `json:"system_reminder,omitempty"`
}

// SendMessageResponse Response for sending a message.
type SendMessageResponse struct {
	// Status Status of the message acceptance.
	Status string `json:"status"`
}

// SkillDefinition Definition of a skill that can be activated by an agent.
type SkillDefinition struct {
	// Content Full skill prompt/instructions content (the SKILL.md body or single-content string).
	// Can contain template variables like {{args}}, $ARGUMENTS, $1, $2, etc.
	Content string `json:"content"`

	// Description Description of what the skill does
	Description string `json:"description"`

	// Files Supporting files: relative_path -> file_content.
	// Contains files referenced by the skill (e.g., "api-reference.md", "examples/ex1.md").
	Files *map[string]string `json:"files,omitempty"`

	// Frontmatter Frontmatter configuration parsed from a SKILL.md YAML header.
	//
	// Only applicable to sources that support frontmatter (ClaudeCode, AgentSkills).
	Frontmatter *SkillFrontmatter `json:"frontmatter,omitempty"`
	Id          String            `json:"id"`

	// ParametersSchema Optional JSON Schema for structured parameters (for future use)
	ParametersSchema interface{} `json:"parameters_schema,omitempty"`

	// Source Where a skill originated from.
	Source *SkillSource `json:"source,omitempty"`

	// Title Human-readable title
	Title string `json:"title"`
}

// SkillFrontmatter Frontmatter configuration parsed from a SKILL.md YAML header.
//
// Only applicable to sources that support frontmatter (ClaudeCode, AgentSkills).
type SkillFrontmatter struct {
	// Agent Sub-agent type to delegate to when context is "fork".
	Agent *string `json:"agent,omitempty"`

	// AllowedTools List of tools the skill is allowed to use.
	AllowedTools *[]string `json:"allowed_tools,omitempty"`

	// ArgumentHint Hint text shown for the argument placeholder in autocomplete.
	ArgumentHint *string `json:"argument_hint,omitempty"`

	// Context Execution context. "fork" runs in an isolated subagent.
	Context *string `json:"context,omitempty"`

	// DisableModelInvocation When true, only users can invoke this skill (hidden from the model).
	DisableModelInvocation *bool `json:"disable_model_invocation,omitempty"`

	// Effort Reasoning effort level (e.g., "low", "medium", "high").
	Effort *string `json:"effort,omitempty"`

	// Paths Glob patterns for auto-activation on matching files.
	Paths *[]string `json:"paths,omitempty"`

	// Shell Shell to use for shell-related operations (e.g., "bash", "powershell").
	Shell *string `json:"shell,omitempty"`

	// UserInvocable When false, only the model can invoke this skill (hidden from slash commands).
	UserInvocable *bool `json:"user_invocable,omitempty"`
}

// SkillSource Where a skill originated from.
type SkillSource string

// String defines model for String.
type String = string

// ToolCall A request to call a tool.
type ToolCall struct {
	// Arguments Arguments to pass to the tool
	Arguments interface{} `json:"arguments"`

	// Id Unique identifier for this tool call
	Id string `json:"id"`

	// Name Name of the tool to call
	Name string `json:"name"`
}

// ToolCallStatsSnapshot Serializable snapshot of per-tool call statistics.
type ToolCallStatsSnapshot struct {
	// AvgLatencyMs Average latency in milliseconds
	AvgLatencyMs float64 `json:"avg_latency_ms"`

	// FailureResults Number of completions where the executor returned `Ok(...)` but the
	// result string described a failure (e.g. `Read` returned
	// `"Toolset error: File not found"`, `bash` returned a non-zero
	// `exit_code`, `edit` returned `{"error":"..."}`). The model received
	// the result as a normal tool message; only the content signals the
	// failure. Tracked separately so operators can distinguish bridge-side
	// dispatch errors (`failures`) from in-tool failures (`failure_results`).
	FailureResults *int64 `json:"failure_results,omitempty"`

	// Failures Number of completions where the executor itself returned `Err` —
	// process-level dispatch failure (tool not found, schema validation
	// rejected, permission denied, executor panic).
	Failures int64 `json:"failures"`

	// SuccessRate Success rate (successes / total_calls)
	SuccessRate float64 `json:"success_rate"`

	// Successes Number of completions that succeeded cleanly (executor returned `Ok`
	// AND the result content does not look like a failure shape).
	Successes int64 `json:"successes"`

	// ToolName Tool name
	ToolName string `json:"tool_name"`

	// TotalCalls Total number of calls to this tool
	TotalCalls int64 `json:"total_calls"`
}

// ToolPermission Permission level for a tool within an agent.
type ToolPermission string

// ToolResult The result of a tool execution.
type ToolResult struct {
	// Content The result content
	Content string `json:"content"`

	// IsError Whether the tool execution resulted in an error
	IsError *bool `json:"is_error,omitempty"`

	// ToolCallId ID of the tool call this result corresponds to
	ToolCallId string `json:"tool_call_id"`
}

// UpsertAgentResponse Response for upserting an agent.
type UpsertAgentResponse struct {
	// Status Status of the operation: "unchanged", "updated", or "created".
	Status string `json:"status"`
}

// CreateConversationJSONRequestBody defines body for CreateConversation for application/json ContentType.
type CreateConversationJSONRequestBody = CreateConversationRequest

// BulkResolveApprovalsJSONRequestBody defines body for BulkResolveApprovals for application/json ContentType.
type BulkResolveApprovalsJSONRequestBody = BulkApprovalReply

// ResolveApprovalJSONRequestBody defines body for ResolveApproval for application/json ContentType.
type ResolveApprovalJSONRequestBody = ApprovalReply

// SendMessageJSONRequestBody defines body for SendMessage for application/json ContentType.
type SendMessageJSONRequestBody = SendMessageRequest

// PushAgentsJSONRequestBody defines body for PushAgents for application/json ContentType.
type PushAgentsJSONRequestBody = PushAgentsRequest

// UpsertAgentJSONRequestBody defines body for UpsertAgent for application/json ContentType.
type UpsertAgentJSONRequestBody = AgentDefinition

// HydrateConversationsJSONRequestBody defines body for HydrateConversations for application/json ContentType.
type HydrateConversationsJSONRequestBody = HydrateConversationsRequest

// PushDiffJSONRequestBody defines body for PushDiff for application/json ContentType.
type PushDiffJSONRequestBody = PushDiffRequest

// AsContentBlock0 returns the union data inside the ContentBlock as a ContentBlock0
func (t ContentBlock) AsContentBlock0() (ContentBlock0, error) {
	var body ContentBlock0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromContentBlock0 overwrites any union data inside the ContentBlock as the provided ContentBlock0
func (t *ContentBlock) FromContentBlock0(v ContentBlock0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeContentBlock0 performs a merge with any union data inside the ContentBlock, using the provided ContentBlock0
func (t *ContentBlock) MergeContentBlock0(v ContentBlock0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsContentBlock1 returns the union data inside the ContentBlock as a ContentBlock1
func (t ContentBlock) AsContentBlock1() (ContentBlock1, error) {
	var body ContentBlock1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromContentBlock1 overwrites any union data inside the ContentBlock as the provided ContentBlock1
func (t *ContentBlock) FromContentBlock1(v ContentBlock1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeContentBlock1 performs a merge with any union data inside the ContentBlock, using the provided ContentBlock1
func (t *ContentBlock) MergeContentBlock1(v ContentBlock1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsContentBlock2 returns the union data inside the ContentBlock as a ContentBlock2
func (t ContentBlock) AsContentBlock2() (ContentBlock2, error) {
	var body ContentBlock2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromContentBlock2 overwrites any union data inside the ContentBlock as the provided ContentBlock2
func (t *ContentBlock) FromContentBlock2(v ContentBlock2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeContentBlock2 performs a merge with any union data inside the ContentBlock, using the provided ContentBlock2
func (t *ContentBlock) MergeContentBlock2(v ContentBlock2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsContentBlock3 returns the union data inside the ContentBlock as a ContentBlock3
func (t ContentBlock) AsContentBlock3() (ContentBlock3, error) {
	var body ContentBlock3
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromContentBlock3 overwrites any union data inside the ContentBlock as the provided ContentBlock3
func (t *ContentBlock) FromContentBlock3(v ContentBlock3) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeContentBlock3 performs a merge with any union data inside the ContentBlock, using the provided ContentBlock3
func (t *ContentBlock) MergeContentBlock3(v ContentBlock3) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ContentBlock) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ContentBlock) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsMcpTransport0 returns the union data inside the McpTransport as a McpTransport0
func (t McpTransport) AsMcpTransport0() (McpTransport0, error) {
	var body McpTransport0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMcpTransport0 overwrites any union data inside the McpTransport as the provided McpTransport0
func (t *McpTransport) FromMcpTransport0(v McpTransport0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMcpTransport0 performs a merge with any union data inside the McpTransport, using the provided McpTransport0
func (t *McpTransport) MergeMcpTransport0(v McpTransport0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMcpTransport1 returns the union data inside the McpTransport as a McpTransport1
func (t McpTransport) AsMcpTransport1() (McpTransport1, error) {
	var body McpTransport1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMcpTransport1 overwrites any union data inside the McpTransport as the provided McpTransport1
func (t *McpTransport) FromMcpTransport1(v McpTransport1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMcpTransport1 performs a merge with any union data inside the McpTransport, using the provided McpTransport1
func (t *McpTransport) MergeMcpTransport1(v McpTransport1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t McpTransport) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *McpTransport) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
