all:
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/use_portal_dev

  children:
    control:
      hosts:
        controlplane:
          ansible_host: 77.42.84.83

    runners:
      hosts:
        runner1:
          ansible_host: 135.181.114.227
          runner_name: runner-1
          runner_index: 1
        runner2:
          ansible_host: 65.108.227.222
          runner_name: runner-2
          runner_index: 2
        runner3:
          ansible_host: 65.108.231.19
          runner_name: runner-3
          runner_index: 3
