package mcpserver

import (
	"context"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/usehivy/hivy/internal/mcp/catalog"
	"github.com/usehivy/hivy/internal/nango"
)

func TestExecuteAction_REST_NoGraphQL(t *testing.T) {
	var capturedBodyMap map[string]any

	server := httptest.NewServer(http.HandlerFunc(func(writer http.ResponseWriter, request *http.Request) {
		bodyBytes, _ := io.ReadAll(request.Body)
		_ = json.Unmarshal(bodyBytes, &capturedBodyMap)
		writer.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(writer).Encode(map[string]any{"ok": true})
	}))
	defer server.Close()

	nangoClient := nango.NewClient(server.URL, "test")

	action := &catalog.ActionDef{
		DisplayName: "List Items",
		Access:      "read",
		Execution: &catalog.ExecutionConfig{
			Method:      "POST",
			Path:        "/api/items",
			BodyMapping: map[string]string{"limit": "limit"},
		},
	}

	_, err := ExecuteAction(
		context.Background(),
		nangoClient,
		"some-provider",
		"cfg-key",
		"conn-id",
		action,
		map[string]any{"limit": 10},
		nil,
	)
	if err != nil {
		t.Fatalf("ExecuteAction failed: %v", err)
	}

	if _, hasQuery := capturedBodyMap["query"]; hasQuery {
		t.Errorf("REST action should not send GraphQL query, got %v", capturedBodyMap)
	}
	if capturedBodyMap["limit"] != float64(10) {
		t.Errorf("expected limit=10 in body, got %v", capturedBodyMap["limit"])
	}
}

func TestExecuteAction_GraphQLQuery_PreDefinedQuery(t *testing.T) {
	var capturedBodyMap map[string]any

	server := httptest.NewServer(http.HandlerFunc(func(writer http.ResponseWriter, request *http.Request) {
		bodyBytes, _ := io.ReadAll(request.Body)
		_ = json.Unmarshal(bodyBytes, &capturedBodyMap)
		writer.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(writer).Encode(map[string]any{"data": map[string]any{"buildLogs": []any{}}})
	}))
	defer server.Close()

	nangoClient := nango.NewClient(server.URL, "test")

	action := &catalog.ActionDef{
		DisplayName: "Build Logs",
		Access:      "read",
		Execution: &catalog.ExecutionConfig{
			Method:           "POST",
			Path:             "/graphql/v2",
			GraphQLOperation: "query",
			GraphQLField:     "buildLogs",
			GraphQLQuery:     "query($deploymentId: String!, $limit: Int) { buildLogs(deploymentId: $deploymentId, limit: $limit) { timestamp message severity } }",
			BodyMapping:      map[string]string{"deploymentId": "deploymentId", "limit": "limit"},
		},
	}

	params := map[string]any{
		"deploymentId": "deploy-abc",
		"limit":        500,
	}

	_, err := ExecuteAction(
		context.Background(),
		nangoClient,
		"railway",
		"in_railway-test",
		"nango-conn",
		action,
		params,
		nil,
	)
	if err != nil {
		t.Fatalf("ExecuteAction failed: %v", err)
	}

	query, ok := capturedBodyMap["query"].(string)
	if !ok || query == "" {
		t.Fatal("expected query in body")
	}
	if query != action.Execution.GraphQLQuery {
		t.Errorf("expected pre-defined query, got %q", query)
	}

	variables, ok := capturedBodyMap["variables"].(map[string]any)
	if !ok {
		t.Fatalf("expected variables map, got %T", capturedBodyMap["variables"])
	}
	if variables["deploymentId"] != "deploy-abc" {
		t.Errorf("expected deploymentId=deploy-abc, got %v", variables["deploymentId"])
	}
	if variables["limit"] != float64(500) {
		t.Errorf("expected limit=500, got %v", variables["limit"])
	}

	if _, hasDeplID := capturedBodyMap["deploymentId"]; hasDeplID {
		t.Error("body should not have top-level deploymentId - it should be in variables")
	}
}

func TestExecuteAction_GraphQLQuery_TakesPriorityOverAutoGenerated(t *testing.T) {
	var capturedBodyMap map[string]any

	server := httptest.NewServer(http.HandlerFunc(func(writer http.ResponseWriter, request *http.Request) {
		bodyBytes, _ := io.ReadAll(request.Body)
		_ = json.Unmarshal(bodyBytes, &capturedBodyMap)
		writer.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(writer).Encode(map[string]any{"data": map[string]any{"service": map[string]any{}}})
	}))
	defer server.Close()

	nangoClient := nango.NewClient(server.URL, "test")

	action := &catalog.ActionDef{
		DisplayName:    "Service",
		Access:         "read",
		ResponseSchema: "service",
		Execution: &catalog.ExecutionConfig{
			Method:           "POST",
			Path:             "/graphql/v2",
			BodyMapping:      map[string]string{"id": "id"},
			GraphQLOperation: "query",
			GraphQLField:     "service",
			GraphQLQuery:     "query($id: String!) { service(id: $id) { id name icon } }",
		},
	}

	_, err := ExecuteAction(
		context.Background(),
		nangoClient,
		"railway",
		"in_railway-test",
		"nango-conn",
		action,
		map[string]any{"id": "svc-123"},
		nil,
	)
	if err != nil {
		t.Fatalf("ExecuteAction failed: %v", err)
	}

	query := capturedBodyMap["query"].(string)

	if !strings.Contains(query, "service(id: $id) { id name icon }") {
		t.Errorf("expected pre-defined query with explicit selection set, got %q", query)
	}

	if variables, ok := capturedBodyMap["variables"].(map[string]any); ok {
		if variables["id"] != "svc-123" {
			t.Errorf("expected id=svc-123 in variables, got %v", variables["id"])
		}
	} else {
		t.Error("expected variables in body")
	}
}
