// This is the authoritative contract between Hiveloop's Go backend and the Rust rag-engine service. Field numbers are LOCKED after merge. Never re-number; only append.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.0
// source: rag_engine.proto

package ragpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RagEngine_CreateDataset_FullMethodName = "/hiveloop.rag.v1.RagEngine/CreateDataset"
	RagEngine_DropDataset_FullMethodName   = "/hiveloop.rag.v1.RagEngine/DropDataset"
	RagEngine_IngestBatch_FullMethodName   = "/hiveloop.rag.v1.RagEngine/IngestBatch"
	RagEngine_UpdateACL_FullMethodName     = "/hiveloop.rag.v1.RagEngine/UpdateACL"
	RagEngine_Search_FullMethodName        = "/hiveloop.rag.v1.RagEngine/Search"
	RagEngine_DeleteByDocID_FullMethodName = "/hiveloop.rag.v1.RagEngine/DeleteByDocID"
	RagEngine_DeleteByOrg_FullMethodName   = "/hiveloop.rag.v1.RagEngine/DeleteByOrg"
	RagEngine_Prune_FullMethodName         = "/hiveloop.rag.v1.RagEngine/Prune"
)

// RagEngineClient is the client API for RagEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RagEngineClient interface {
	// Dataset lifecycle — one dataset per (provider, model, dim) triple.
	// Onyx analog: Verifiable.ensure_indices_exist
	//
	//	backend/onyx/document_index/interfaces.py:171-190
	CreateDataset(ctx context.Context, in *CreateDatasetRequest, opts ...grpc.CallOption) (*CreateDatasetResponse, error)
	DropDataset(ctx context.Context, in *DropDatasetRequest, opts ...grpc.CallOption) (*DropDatasetResponse, error)
	// Unary batch ingest — Go sends 500-1000 raw documents per call.
	// Rust chunks + embeds + writes; returns per-doc detailed results.
	// Onyx analog: Indexable.index  backend/onyx/document_index/interfaces.py:205-243
	// SLO: each batch completes in ≤10s. Client deadline: 15s.
	IngestBatch(ctx context.Context, in *IngestBatchRequest, opts ...grpc.CallOption) (*IngestBatchResponse, error)
	// Metadata-only update — THE operation that failed the lance-go spike.
	// Onyx analog: Updatable.update_single
	//
	//	backend/onyx/document_index/interfaces.py:268-302
	//	plus vespa impl: backend/onyx/document_index/vespa/index.py:653
	UpdateACL(ctx context.Context, in *UpdateACLRequest, opts ...grpc.CallOption) (*UpdateACLResponse, error)
	// Retrieval — hybrid vector + BM25, with ACL + org + custom filters.
	// Onyx analog: HybridCapable.hybrid_retrieval
	//
	//	backend/onyx/document_index/interfaces.py:339-383
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// Deletion.
	// Onyx analog: Deletable.delete_single
	//
	//	backend/onyx/document_index/interfaces.py:246-265
	DeleteByDocID(ctx context.Context, in *DeleteByDocIDRequest, opts ...grpc.CallOption) (*DeleteByDocIDResponse, error)
	// Org-wide deletion — cascaded from Postgres org deletion (Phase 1 FK pattern).
	// Onyx analog: backend/onyx/document_index/vespa/index.py:913
	//
	//	(delete_entries_by_tenant_id)
	DeleteByOrg(ctx context.Context, in *DeleteByOrgRequest, opts ...grpc.CallOption) (*DeleteByOrgResponse, error)
	// Prune — delete chunks for a set of doc ids that the source no longer has.
	// Onyx analog: backend/onyx/background/celery/tasks/pruning/
	Prune(ctx context.Context, in *PruneRequest, opts ...grpc.CallOption) (*PruneResponse, error)
}

type ragEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewRagEngineClient(cc grpc.ClientConnInterface) RagEngineClient {
	return &ragEngineClient{cc}
}

func (c *ragEngineClient) CreateDataset(ctx context.Context, in *CreateDatasetRequest, opts ...grpc.CallOption) (*CreateDatasetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDatasetResponse)
	err := c.cc.Invoke(ctx, RagEngine_CreateDataset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragEngineClient) DropDataset(ctx context.Context, in *DropDatasetRequest, opts ...grpc.CallOption) (*DropDatasetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DropDatasetResponse)
	err := c.cc.Invoke(ctx, RagEngine_DropDataset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragEngineClient) IngestBatch(ctx context.Context, in *IngestBatchRequest, opts ...grpc.CallOption) (*IngestBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestBatchResponse)
	err := c.cc.Invoke(ctx, RagEngine_IngestBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragEngineClient) UpdateACL(ctx context.Context, in *UpdateACLRequest, opts ...grpc.CallOption) (*UpdateACLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateACLResponse)
	err := c.cc.Invoke(ctx, RagEngine_UpdateACL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragEngineClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, RagEngine_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragEngineClient) DeleteByDocID(ctx context.Context, in *DeleteByDocIDRequest, opts ...grpc.CallOption) (*DeleteByDocIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteByDocIDResponse)
	err := c.cc.Invoke(ctx, RagEngine_DeleteByDocID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragEngineClient) DeleteByOrg(ctx context.Context, in *DeleteByOrgRequest, opts ...grpc.CallOption) (*DeleteByOrgResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteByOrgResponse)
	err := c.cc.Invoke(ctx, RagEngine_DeleteByOrg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragEngineClient) Prune(ctx context.Context, in *PruneRequest, opts ...grpc.CallOption) (*PruneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PruneResponse)
	err := c.cc.Invoke(ctx, RagEngine_Prune_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RagEngineServer is the server API for RagEngine service.
// All implementations must embed UnimplementedRagEngineServer
// for forward compatibility.
type RagEngineServer interface {
	// Dataset lifecycle — one dataset per (provider, model, dim) triple.
	// Onyx analog: Verifiable.ensure_indices_exist
	//
	//	backend/onyx/document_index/interfaces.py:171-190
	CreateDataset(context.Context, *CreateDatasetRequest) (*CreateDatasetResponse, error)
	DropDataset(context.Context, *DropDatasetRequest) (*DropDatasetResponse, error)
	// Unary batch ingest — Go sends 500-1000 raw documents per call.
	// Rust chunks + embeds + writes; returns per-doc detailed results.
	// Onyx analog: Indexable.index  backend/onyx/document_index/interfaces.py:205-243
	// SLO: each batch completes in ≤10s. Client deadline: 15s.
	IngestBatch(context.Context, *IngestBatchRequest) (*IngestBatchResponse, error)
	// Metadata-only update — THE operation that failed the lance-go spike.
	// Onyx analog: Updatable.update_single
	//
	//	backend/onyx/document_index/interfaces.py:268-302
	//	plus vespa impl: backend/onyx/document_index/vespa/index.py:653
	UpdateACL(context.Context, *UpdateACLRequest) (*UpdateACLResponse, error)
	// Retrieval — hybrid vector + BM25, with ACL + org + custom filters.
	// Onyx analog: HybridCapable.hybrid_retrieval
	//
	//	backend/onyx/document_index/interfaces.py:339-383
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	// Deletion.
	// Onyx analog: Deletable.delete_single
	//
	//	backend/onyx/document_index/interfaces.py:246-265
	DeleteByDocID(context.Context, *DeleteByDocIDRequest) (*DeleteByDocIDResponse, error)
	// Org-wide deletion — cascaded from Postgres org deletion (Phase 1 FK pattern).
	// Onyx analog: backend/onyx/document_index/vespa/index.py:913
	//
	//	(delete_entries_by_tenant_id)
	DeleteByOrg(context.Context, *DeleteByOrgRequest) (*DeleteByOrgResponse, error)
	// Prune — delete chunks for a set of doc ids that the source no longer has.
	// Onyx analog: backend/onyx/background/celery/tasks/pruning/
	Prune(context.Context, *PruneRequest) (*PruneResponse, error)
	mustEmbedUnimplementedRagEngineServer()
}

// UnimplementedRagEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRagEngineServer struct{}

func (UnimplementedRagEngineServer) CreateDataset(context.Context, *CreateDatasetRequest) (*CreateDatasetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDataset not implemented")
}
func (UnimplementedRagEngineServer) DropDataset(context.Context, *DropDatasetRequest) (*DropDatasetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DropDataset not implemented")
}
func (UnimplementedRagEngineServer) IngestBatch(context.Context, *IngestBatchRequest) (*IngestBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IngestBatch not implemented")
}
func (UnimplementedRagEngineServer) UpdateACL(context.Context, *UpdateACLRequest) (*UpdateACLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateACL not implemented")
}
func (UnimplementedRagEngineServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedRagEngineServer) DeleteByDocID(context.Context, *DeleteByDocIDRequest) (*DeleteByDocIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteByDocID not implemented")
}
func (UnimplementedRagEngineServer) DeleteByOrg(context.Context, *DeleteByOrgRequest) (*DeleteByOrgResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteByOrg not implemented")
}
func (UnimplementedRagEngineServer) Prune(context.Context, *PruneRequest) (*PruneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Prune not implemented")
}
func (UnimplementedRagEngineServer) mustEmbedUnimplementedRagEngineServer() {}
func (UnimplementedRagEngineServer) testEmbeddedByValue()                   {}

// UnsafeRagEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RagEngineServer will
// result in compilation errors.
type UnsafeRagEngineServer interface {
	mustEmbedUnimplementedRagEngineServer()
}

func RegisterRagEngineServer(s grpc.ServiceRegistrar, srv RagEngineServer) {
	// If the following call panics, it indicates UnimplementedRagEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RagEngine_ServiceDesc, srv)
}

func _RagEngine_CreateDataset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDatasetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagEngineServer).CreateDataset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagEngine_CreateDataset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagEngineServer).CreateDataset(ctx, req.(*CreateDatasetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagEngine_DropDataset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropDatasetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagEngineServer).DropDataset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagEngine_DropDataset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagEngineServer).DropDataset(ctx, req.(*DropDatasetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagEngine_IngestBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagEngineServer).IngestBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagEngine_IngestBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagEngineServer).IngestBatch(ctx, req.(*IngestBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagEngine_UpdateACL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateACLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagEngineServer).UpdateACL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagEngine_UpdateACL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagEngineServer).UpdateACL(ctx, req.(*UpdateACLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagEngine_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagEngineServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagEngine_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagEngineServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagEngine_DeleteByDocID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteByDocIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagEngineServer).DeleteByDocID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagEngine_DeleteByDocID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagEngineServer).DeleteByDocID(ctx, req.(*DeleteByDocIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagEngine_DeleteByOrg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteByOrgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagEngineServer).DeleteByOrg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagEngine_DeleteByOrg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagEngineServer).DeleteByOrg(ctx, req.(*DeleteByOrgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagEngine_Prune_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PruneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagEngineServer).Prune(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagEngine_Prune_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagEngineServer).Prune(ctx, req.(*PruneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RagEngine_ServiceDesc is the grpc.ServiceDesc for RagEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RagEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hiveloop.rag.v1.RagEngine",
	HandlerType: (*RagEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDataset",
			Handler:    _RagEngine_CreateDataset_Handler,
		},
		{
			MethodName: "DropDataset",
			Handler:    _RagEngine_DropDataset_Handler,
		},
		{
			MethodName: "IngestBatch",
			Handler:    _RagEngine_IngestBatch_Handler,
		},
		{
			MethodName: "UpdateACL",
			Handler:    _RagEngine_UpdateACL_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _RagEngine_Search_Handler,
		},
		{
			MethodName: "DeleteByDocID",
			Handler:    _RagEngine_DeleteByDocID_Handler,
		},
		{
			MethodName: "DeleteByOrg",
			Handler:    _RagEngine_DeleteByOrg_Handler,
		},
		{
			MethodName: "Prune",
			Handler:    _RagEngine_Prune_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rag_engine.proto",
}
