// This is the authoritative contract between Hiveloop's Go backend and the Rust rag-engine service. Source of truth: plans/onyx-port-phase2.md §gRPC. Field numbers are LOCKED after merge. Never re-number; only append.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: rag_engine.proto

package ragpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IngestionMode int32

const (
	IngestionMode_INGESTION_MODE_UNSPECIFIED IngestionMode = 0
	IngestionMode_INGESTION_MODE_UPSERT      IngestionMode = 1 // chunk+embed; overwrites chunks for (doc_id, dataset)
	IngestionMode_INGESTION_MODE_REINDEX     IngestionMode = 2 // wipes all existing chunks for each doc_id first, then upserts
)

// Enum value maps for IngestionMode.
var (
	IngestionMode_name = map[int32]string{
		0: "INGESTION_MODE_UNSPECIFIED",
		1: "INGESTION_MODE_UPSERT",
		2: "INGESTION_MODE_REINDEX",
	}
	IngestionMode_value = map[string]int32{
		"INGESTION_MODE_UNSPECIFIED": 0,
		"INGESTION_MODE_UPSERT":      1,
		"INGESTION_MODE_REINDEX":     2,
	}
)

func (x IngestionMode) Enum() *IngestionMode {
	p := new(IngestionMode)
	*p = x
	return p
}

func (x IngestionMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IngestionMode) Descriptor() protoreflect.EnumDescriptor {
	return file_rag_engine_proto_enumTypes[0].Descriptor()
}

func (IngestionMode) Type() protoreflect.EnumType {
	return &file_rag_engine_proto_enumTypes[0]
}

func (x IngestionMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IngestionMode.Descriptor instead.
func (IngestionMode) EnumDescriptor() ([]byte, []int) {
	return file_rag_engine_proto_rawDescGZIP(), []int{0}
}

type DocumentStatus int32

const (
	DocumentStatus_DOCUMENT_STATUS_UNSPECIFIED DocumentStatus = 0
	DocumentStatus_DOCUMENT_STATUS_SUCCESS     DocumentStatus = 1
	DocumentStatus_DOCUMENT_STATUS_FAILED      DocumentStatus = 2 // fatal error for this doc; rest of batch continues
	DocumentStatus_DOCUMENT_STATUS_SKIPPED     DocumentStatus = 3 // e.g. empty content, no sections
)

// Enum value maps for DocumentStatus.
var (
	DocumentStatus_name = map[int32]string{
		0: "DOCUMENT_STATUS_UNSPECIFIED",
		1: "DOCUMENT_STATUS_SUCCESS",
		2: "DOCUMENT_STATUS_FAILED",
		3: "DOCUMENT_STATUS_SKIPPED",
	}
	DocumentStatus_value = map[string]int32{
		"DOCUMENT_STATUS_UNSPECIFIED": 0,
		"DOCUMENT_STATUS_SUCCESS":     1,
		"DOCUMENT_STATUS_FAILED":      2,
		"DOCUMENT_STATUS_SKIPPED":     3,
	}
)

func (x DocumentStatus) Enum() *DocumentStatus {
	p := new(DocumentStatus)
	*p = x
	return p
}

func (x DocumentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DocumentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_rag_engine_proto_enumTypes[1].Descriptor()
}

func (DocumentStatus) Type() protoreflect.EnumType {
	return &file_rag_engine_proto_enumTypes[1]
}

func (x DocumentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DocumentStatus.Descriptor instead.
func (DocumentStatus) EnumDescriptor() ([]byte, []int) {
	return file_rag_engine_proto_rawDescGZIP(), []int{1}
}

type SearchMode int32

const (
	SearchMode_SEARCH_MODE_UNSPECIFIED SearchMode = 0
	SearchMode_SEARCH_MODE_HYBRID      SearchMode = 1
	SearchMode_SEARCH_MODE_VECTOR_ONLY SearchMode = 2
	SearchMode_SEARCH_MODE_BM25_ONLY   SearchMode = 3
)

// Enum value maps for SearchMode.
var (
	SearchMode_name = map[int32]string{
		0: "SEARCH_MODE_UNSPECIFIED",
		1: "SEARCH_MODE_HYBRID",
		2: "SEARCH_MODE_VECTOR_ONLY",
		3: "SEARCH_MODE_BM25_ONLY",
	}
	SearchMode_value = map[string]int32{
		"SEARCH_MODE_UNSPECIFIED": 0,
		"SEARCH_MODE_HYBRID":      1,
		"SEARCH_MODE_VECTOR_ONLY": 2,
		"SEARCH_MODE_BM25_ONLY":   3,
	}
)

func (x SearchMode) Enum() *SearchMode {
	p := new(SearchMode)
	*p = x
	return p
}

func (x SearchMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchMode) Descriptor() protoreflect.EnumDescriptor {
	return file_rag_engine_proto_enumTypes[2].Descriptor()
}

func (SearchMode) Type() protoreflect.EnumType {
	return &file_rag_engine_proto_enumTypes[2]
}

func (x SearchMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchMode.Descriptor instead.
func (SearchMode) EnumDescriptor() ([]byte, []int) {
	return file_rag_engine_proto_rawDescGZIP(), []int{2}
}

type CreateDatasetRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DatasetName        string                 `protobuf:"bytes,1,opt,name=dataset_name,json=datasetName,proto3" json:"dataset_name,omitempty"`                      // rag_chunks__siliconflow_qwen3_embedding_4b__2560
	VectorDim          uint32                 `protobuf:"varint,2,opt,name=vector_dim,json=vectorDim,proto3" json:"vector_dim,omitempty"`                           // must match embedder for this org
	EmbeddingPrecision string                 `protobuf:"bytes,3,opt,name=embedding_precision,json=embeddingPrecision,proto3" json:"embedding_precision,omitempty"` // "float32" | "float16" | "int8" per Onyx EmbeddingPrecision
	IdempotencyKey     string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`             // client-generated; server returns ALREADY_EXISTS if replayed
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateDatasetRequest) Reset() {
	*x = CreateDatasetRequest{}
	mi := &file_rag_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDatasetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDatasetRequest) ProtoMessage() {}

func (x *CreateDatasetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDatasetRequest.ProtoReflect.Descriptor instead.
func (*CreateDatasetRequest) Descriptor() ([]byte, []int) {
	return file_rag_engine_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDatasetRequest) GetDatasetName() string {
	if x != nil {
		return x.DatasetName
	}
	return ""
}

func (x *CreateDatasetRequest) GetVectorDim() uint32 {
	if x != nil {
		return x.VectorDim
	}
	return 0
}

func (x *CreateDatasetRequest) GetEmbeddingPrecision() string {
	if x != nil {
		return x.EmbeddingPrecision
	}
	return ""
}

func (x *CreateDatasetRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type CreateDatasetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Created       bool                   `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`                   // false = already existed and schema matches
	SchemaOk      bool                   `protobuf:"varint,2,opt,name=schema_ok,json=schemaOk,proto3" json:"schema_ok,omitempty"` // schema verified consistent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDatasetResponse) Reset() {
	*x = CreateDatasetResponse{}
	mi := &file_rag_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDatasetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDatasetResponse) ProtoMessage() {}

func (x *CreateDatasetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDatasetResponse.ProtoReflect.Descriptor instead.
func (*CreateDatasetResponse) Descriptor() ([]byte, []int) {
	return file_rag_engine_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDatasetResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

func (x *CreateDatasetResponse) GetSchemaOk() bool {
	if x != nil {
		return x.SchemaOk
	}
	return false
}

type DropDatasetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatasetName   string                 `protobuf:"bytes,1,opt,name=dataset_name,json=datasetName,proto3" json:"dataset_name,omitempty"`
	Confirm       bool                   `protobuf:"varint,2,opt,name=confirm,proto3" json:"confirm,omitempty"` // must be true — safety interlock
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropDatasetRequest) Reset() {
	*x = DropDatasetRequest{}
	mi := &file_rag_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropDatasetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropDatasetRequest) ProtoMessage() {}

func (x *DropDatasetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropDatasetRequest.ProtoReflect.Descriptor instead.
func (*DropDatasetRequest) Descriptor() ([]byte, []int) {
	return file_rag_engine_proto_rawDescGZIP(), []int{2}
}

func (x *DropDatasetRequest) GetDatasetName() string {
	if x != nil {
		return x.DatasetName
	}
	return ""
}

func (x *DropDatasetRequest) GetConfirm() bool {
	if x != nil {
		return x.Confirm
	}
	return false
}

type DropDatasetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dropped       bool                   `protobuf:"varint,1,opt,name=dropped,proto3" json:"dropped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropDatasetResponse) Reset() {
	*x = DropDatasetResponse{}
	mi := &file_rag_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropDatasetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropDatasetResponse) ProtoMessage() {}

func (x *DropDatasetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropDatasetResponse.ProtoReflect.Descriptor instead.
func (*DropDatasetResponse) Descriptor() ([]byte, []int) {
	return file_rag_engine_proto_rawDescGZIP(), []int{3}
}

func (x *DropDatasetResponse) GetDropped() bool {
	if x != nil {
		return x.Dropped
	}
	return false
}

type IngestBatchRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DatasetName       string                 `protobuf:"bytes,1,opt,name=dataset_name,json=datasetName,proto3" json:"dataset_name,omitempty"`
	OrgId             string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`                                        // tenant partition key (opaque to Rust)
	Mode              IngestionMode          `protobuf:"varint,3,opt,name=mode,proto3,enum=hiveloop.rag.v1.IngestionMode" json:"mode,omitempty"`                   // UPSERT | REINDEX
	IdempotencyKey    string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`             // batch-level; replayed request returns prior result
	DeclaredVectorDim uint32                 `protobuf:"varint,5,opt,name=declared_vector_dim,json=declaredVectorDim,proto3" json:"declared_vector_dim,omitempty"` // Rust validates matches dataset schema
	Documents         []*DocumentToIngest    `protobuf:"bytes,6,rep,name=documents,proto3" json:"documents,omitempty"`                                             // 500-1000 per batch (soft limit; hard max enforced server-side)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *IngestBatchRequest) Reset() {
	*x = IngestBatchRequest{}
	mi := &file_rag_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestBatchRequest) ProtoMessage() {}

func (x *IngestBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestBatchRequest.ProtoReflect.Descriptor instead.
func (*IngestBatchRequest) Descriptor() ([]byte, []int) {
	return file_rag_engine_proto_rawDescGZIP(), []int{4}
}

func (x *IngestBatchRequest) GetDatasetName() string {
	if x != nil {
		return x.DatasetName
	}
	return ""
}

func (x *IngestBatchRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *IngestBatchRequest) GetMode() IngestionMode {
	if x != nil {
		return x.Mode
	}
	return IngestionMode_INGESTION_MODE_UNSPECIFIED
}

func (x *IngestBatchRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *IngestBatchRequest) GetDeclaredVectorDim() uint32 {
	if x != nil {
		return x.DeclaredVectorDim
	}
	return 0
}

func (x *IngestBatchRequest) GetDocuments() []*DocumentToIngest {
	if x != nil {
		return x.Documents
	}
	return nil
}

// Onyx analog: backend/onyx/connectors/models.py (Document + Section)
type DocumentToIngest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DocId           string                 `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	SemanticId      string                 `protobuf:"bytes,2,opt,name=semantic_id,json=semanticId,proto3" json:"semantic_id,omitempty"` // human-readable title
	Link            string                 `protobuf:"bytes,3,opt,name=link,proto3" json:"link,omitempty"`
	DocUpdatedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=doc_updated_at,json=docUpdatedAt,proto3" json:"doc_updated_at,omitempty"`
	Acl             []string               `protobuf:"bytes,5,rep,name=acl,proto3" json:"acl,omitempty"`                                                                                     // OPAQUE tokens; server does not interpret
	IsPublic        bool                   `protobuf:"varint,6,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`                                                          // mirrors ExternalAccess.is_public
	Sections        []*Section             `protobuf:"bytes,7,rep,name=sections,proto3" json:"sections,omitempty"`                                                                           // raw text — Rust chunks
	Metadata        map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // string-string only; typed metadata lives in Postgres
	PrimaryOwners   []string               `protobuf:"bytes,9,rep,name=primary_owners,json=primaryOwners,proto3" json:"primary_owners,omitempty"`
	SecondaryOwners []string               `protobuf:"bytes,10,rep,name=secondary_owners,json=secondaryOwners,proto3" json:"secondary_owners,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DocumentToIngest) Reset() {
	*x = DocumentToIngest{}
	mi := &file_rag_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentToIngest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentToIngest) ProtoMessage() {}

func (x *DocumentToIngest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentToIngest.ProtoReflect.Descriptor instead.
func (*DocumentToIngest) Descriptor() ([]byte, []int) {
	return file_rag_engine_proto_rawDescGZIP(), []int{5}
}

func (x *DocumentToIngest) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *DocumentToIngest) GetSemanticId() string {
	if x != nil {
		return x.SemanticId
	}
	return ""
}

func (x *DocumentToIngest) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *DocumentToIngest) GetDocUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DocUpdatedAt
	}
	return nil
}

func (x *DocumentToIngest) GetAcl() []string {
	if x != nil {
		return x.Acl
	}
	return nil
}

func (x *DocumentToIngest) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *DocumentToIngest) GetSections() []*Section {
	if x != nil {
		return x.Sections
	}
	return nil
}

func (x *DocumentToIngest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DocumentToIngest) GetPrimaryOwners() []string {
	if x != nil {
		return x.PrimaryOwners
	}
	return nil
}

func (x *DocumentToIngest) GetSecondaryOwners() []string {
	if x != nil {
		return x.SecondaryOwners
	}
	return nil
}

type Section struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Link          string                 `protobuf:"bytes,2,opt,name=link,proto3" json:"link,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"` // optional section heading
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Section) Reset() {
	*x = Section{}
	mi := &file_rag_engine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Section) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Section) ProtoMessage() {}

func (x *Section) ProtoReflect() protoreflect.Message {
	mi := &file_rag_engine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Section.ProtoReflect.Descriptor instead.
func (*Section) Descriptor() ([]byte, []int) {
	return file_rag_engine_proto_rawDescGZIP(), []int{6}
}

func (x *Section) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Section) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *Section) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type IngestBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*DocumentResult      `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"` // ONE per doc in request, SAME ORDER
	Totals        *BatchTotals           `protobuf:"bytes,2,opt,name=totals,proto3" json:"totals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestBatchResponse) Reset() {
	*x = IngestBatchResponse{}
	mi := &file_rag_engine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestBatchResponse) ProtoMessage() {}

func (x *IngestBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_engine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestBatchResponse.ProtoReflect.Descriptor instead.
func (*IngestBatchResponse) Descriptor() ([]byte, []int) {
	return file_rag_engine_proto_rawDescGZIP(), []int{7}
}

func (x *IngestBatchResponse) GetResults() []*DocumentResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *IngestBatchResponse) GetTotals() *BatchTotals {
	if x != nil {
		return x.Totals
	}
	return nil
}

type DocumentResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DocId          string                 `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Status         DocumentStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=hiveloop.rag.v1.DocumentStatus" json:"status,omitempty"`
	ChunksWritten  uint32                 `protobuf:"varint,3,opt,name=chunks_written,json=chunksWritten,proto3" json:"chunks_written,omitempty"`
	TokensEmbedded uint32                 `protobuf:"varint,4,opt,name=tokens_embedded,json=tokensEmbedded,proto3" json:"tokens_embedded,omitempty"`
	ErrorCode      string                 `protobuf:"bytes,5,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`       // populated iff status=FAILED
	ErrorReason    string                 `protobuf:"bytes,6,opt,name=error_reason,json=errorReason,proto3" json:"error_reason,omitempty"` // human-readable
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DocumentResult) Reset() {
	*x = DocumentResult{}
	mi := &file_rag_engine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentResult) ProtoMessage() {}

func (x *DocumentResult) ProtoReflect() protoreflect.Message {
	mi := &file_rag_engine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentResult.ProtoReflect.Descriptor instead.
func (*DocumentResult) Descriptor() ([]byte, []int) {
	return file_rag_engine_proto_rawDescGZIP(), []int{8}
}

func (x *DocumentResult) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *DocumentResult) GetStatus() DocumentStatus {
	if x != nil {
		return x.Status
	}
	return DocumentStatus_DOCUMENT_STATUS_UNSPECIFIED
}

func (x *DocumentResult) GetChunksWritten() uint32 {
	if x != nil {
		return x.ChunksWritten
	}
	return 0
}

func (x *DocumentResult) GetTokensEmbedded() uint32 {
	if x != nil {
		return x.TokensEmbedded
	}
	return 0
}

func (x *DocumentResult) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *DocumentResult) GetErrorReason() string {
	if x != nil {
		return x.ErrorReason
	}
	return ""
}

type BatchTotals struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RowsWritten         uint64                 `protobuf:"varint,1,opt,name=rows_written,json=rowsWritten,proto3" json:"rows_written,omitempty"`
	BytesWritten        uint64                 `protobuf:"varint,2,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	BatchDurationMs     uint32                 `protobuf:"varint,3,opt,name=batch_duration_ms,json=batchDurationMs,proto3" json:"batch_duration_ms,omitempty"`
	ChunkDurationMs     uint32                 `protobuf:"varint,4,opt,name=chunk_duration_ms,json=chunkDurationMs,proto3" json:"chunk_duration_ms,omitempty"`
	EmbeddingDurationMs uint32                 `protobuf:"varint,5,opt,name=embedding_duration_ms,json=embeddingDurationMs,proto3" json:"embedding_duration_ms,omitempty"`
	WriteDurationMs     uint32                 `protobuf:"varint,6,opt,name=write_duration_ms,json=writeDurationMs,proto3" json:"write_duration_ms,omitempty"`
	DocsSucceeded       uint32                 `protobuf:"varint,7,opt,name=docs_succeeded,json=docsSucceeded,proto3" json:"docs_succeeded,omitempty"`
	DocsFailed          uint32                 `protobuf:"varint,8,opt,name=docs_failed,json=docsFailed,proto3" json:"docs_failed,omitempty"`
	DocsSkipped         uint32                 `protobuf:"varint,9,opt,name=docs_skipped,json=docsSkipped,proto3" json:"docs_skipped,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BatchTotals) Reset() {
	*x = BatchTotals{}
	mi := &file_rag_engine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchTotals) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchTotals) ProtoMessage() {}

func (x *BatchTotals) ProtoReflect() protoreflect.Message {
	mi := &file_rag_engine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchTotals.ProtoReflect.Descriptor instead.
func (*BatchTotals) Descriptor() ([]byte, []int) {
	return file_rag_engine_proto_rawDescGZIP(), []int{9}
}

func (x *BatchTotals) GetRowsWritten() uint64 {
	if x != nil {
		return x.RowsWritten
	}
	return 0
}

func (x *BatchTotals) GetBytesWritten() uint64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

func (x *BatchTotals) GetBatchDurationMs() uint32 {
	if x != nil {
		return x.BatchDurationMs
	}
	return 0
}

func (x *BatchTotals) GetChunkDurationMs() uint32 {
	if x != nil {
		return x.ChunkDurationMs
	}
	return 0
}

func (x *BatchTotals) GetEmbeddingDurationMs() uint32 {
	if x != nil {
		return x.EmbeddingDurationMs
	}
	return 0
}

func (x *BatchTotals) GetWriteDurationMs() uint32 {
	if x != nil {
		return x.WriteDurationMs
	}
	return 0
}

func (x *BatchTotals) GetDocsSucceeded() uint32 {
	if x != nil {
		return x.DocsSucceeded
	}
	return 0
}

func (x *BatchTotals) GetDocsFailed() uint32 {
	if x != nil {
		return x.DocsFailed
	}
	return 0
}

func (x *BatchTotals) GetDocsSkipped() uint32 {
	if x != nil {
		return x.DocsSkipped
	}
	return 0
}

type UpdateACLRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DatasetName    string                 `protobuf:"bytes,1,opt,name=dataset_name,json=datasetName,proto3" json:"dataset_name,omitempty"`
	OrgId          string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Entries        []*UpdateACLEntry      `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateACLRequest) Reset() {
	*x = UpdateACLRequest{}
	mi := &file_rag_engine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateACLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateACLRequest) ProtoMessage() {}

func (x *UpdateACLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_engine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateACLRequest.ProtoReflect.Descriptor instead.
func (*UpdateACLRequest) Descriptor() ([]byte, []int) {
	return file_rag_engine_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateACLRequest) GetDatasetName() string {
	if x != nil {
		return x.DatasetName
	}
	return ""
}

func (x *UpdateACLRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *UpdateACLRequest) GetEntries() []*UpdateACLEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *UpdateACLRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type UpdateACLEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocId         string                 `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"` // applies to ALL chunks with this doc_id
	Acl           []string               `protobuf:"bytes,2,rep,name=acl,proto3" json:"acl,omitempty"`                  // full replacement (not patch)
	IsPublic      bool                   `protobuf:"varint,3,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateACLEntry) Reset() {
	*x = UpdateACLEntry{}
	mi := &file_rag_engine_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateACLEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateACLEntry) ProtoMessage() {}

func (x *UpdateACLEntry) ProtoReflect() protoreflect.Message {
	mi := &file_rag_engine_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateACLEntry.ProtoReflect.Descriptor instead.
func (*UpdateACLEntry) Descriptor() ([]byte, []int) {
	return file_rag_engine_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateACLEntry) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *UpdateACLEntry) GetAcl() []string {
	if x != nil {
		return x.Acl
	}
	return nil
}

func (x *UpdateACLEntry) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

type UpdateACLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocsUpdated   uint64                 `protobuf:"varint,1,opt,name=docs_updated,json=docsUpdated,proto3" json:"docs_updated,omitempty"`
	ChunksUpdated uint64                 `protobuf:"varint,2,opt,name=chunks_updated,json=chunksUpdated,proto3" json:"chunks_updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateACLResponse) Reset() {
	*x = UpdateACLResponse{}
	mi := &file_rag_engine_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateACLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateACLResponse) ProtoMessage() {}

func (x *UpdateACLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_engine_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateACLResponse.ProtoReflect.Descriptor instead.
func (*UpdateACLResponse) Descriptor() ([]byte, []int) {
	return file_rag_engine_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateACLResponse) GetDocsUpdated() uint64 {
	if x != nil {
		return x.DocsUpdated
	}
	return 0
}

func (x *UpdateACLResponse) GetChunksUpdated() uint64 {
	if x != nil {
		return x.ChunksUpdated
	}
	return 0
}

type SearchRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DatasetName     string                 `protobuf:"bytes,1,opt,name=dataset_name,json=datasetName,proto3" json:"dataset_name,omitempty"`
	OrgId           string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`                            // always applied as a filter
	QueryText       string                 `protobuf:"bytes,3,opt,name=query_text,json=queryText,proto3" json:"query_text,omitempty"`                // for BM25 + display
	QueryVector     []float32              `protobuf:"fixed32,4,rep,packed,name=query_vector,json=queryVector,proto3" json:"query_vector,omitempty"` // for vector search; server validates dim
	Mode            SearchMode             `protobuf:"varint,5,opt,name=mode,proto3,enum=hiveloop.rag.v1.SearchMode" json:"mode,omitempty"`
	AclAnyOf        []string               `protobuf:"bytes,6,rep,name=acl_any_of,json=aclAnyOf,proto3" json:"acl_any_of,omitempty"`               // array_has_any(acl, [...])
	IncludePublic   bool                   `protobuf:"varint,7,opt,name=include_public,json=includePublic,proto3" json:"include_public,omitempty"` // OR PUBLIC into the ACL filter
	Limit           uint32                 `protobuf:"varint,8,opt,name=limit,proto3" json:"limit,omitempty"`
	CandidatePool   uint32                 `protobuf:"varint,9,opt,name=candidate_pool,json=candidatePool,proto3" json:"candidate_pool,omitempty"`         // how many to pull before fusion/rerank
	CustomSqlFilter string                 `protobuf:"bytes,10,opt,name=custom_sql_filter,json=customSqlFilter,proto3" json:"custom_sql_filter,omitempty"` // escape hatch; will be Phase 3+ (Phase 2 ignores)
	HybridAlpha     float64                `protobuf:"fixed64,11,opt,name=hybrid_alpha,json=hybridAlpha,proto3" json:"hybrid_alpha,omitempty"`             // 0..1; 1.0 = pure vector, 0.0 = pure BM25
	Rerank          bool                   `protobuf:"varint,12,opt,name=rerank,proto3" json:"rerank,omitempty"`                                           // if true and reranker configured, rerank before returning
	DocUpdatedAfter *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=doc_updated_after,json=docUpdatedAfter,proto3" json:"doc_updated_after,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_rag_engine_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_engine_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_rag_engine_proto_rawDescGZIP(), []int{13}
}

func (x *SearchRequest) GetDatasetName() string {
	if x != nil {
		return x.DatasetName
	}
	return ""
}

func (x *SearchRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *SearchRequest) GetQueryText() string {
	if x != nil {
		return x.QueryText
	}
	return ""
}

func (x *SearchRequest) GetQueryVector() []float32 {
	if x != nil {
		return x.QueryVector
	}
	return nil
}

func (x *SearchRequest) GetMode() SearchMode {
	if x != nil {
		return x.Mode
	}
	return SearchMode_SEARCH_MODE_UNSPECIFIED
}

func (x *SearchRequest) GetAclAnyOf() []string {
	if x != nil {
		return x.AclAnyOf
	}
	return nil
}

func (x *SearchRequest) GetIncludePublic() bool {
	if x != nil {
		return x.IncludePublic
	}
	return false
}

func (x *SearchRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchRequest) GetCandidatePool() uint32 {
	if x != nil {
		return x.CandidatePool
	}
	return 0
}

func (x *SearchRequest) GetCustomSqlFilter() string {
	if x != nil {
		return x.CustomSqlFilter
	}
	return ""
}

func (x *SearchRequest) GetHybridAlpha() float64 {
	if x != nil {
		return x.HybridAlpha
	}
	return 0
}

func (x *SearchRequest) GetRerank() bool {
	if x != nil {
		return x.Rerank
	}
	return false
}

func (x *SearchRequest) GetDocUpdatedAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.DocUpdatedAfter
	}
	return nil
}

type SearchResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Hits             []*SearchHit           `protobuf:"bytes,1,rep,name=hits,proto3" json:"hits,omitempty"`
	Bm25Candidates   uint32                 `protobuf:"varint,2,opt,name=bm25_candidates,json=bm25Candidates,proto3" json:"bm25_candidates,omitempty"` // debug/observability
	VectorCandidates uint32                 `protobuf:"varint,3,opt,name=vector_candidates,json=vectorCandidates,proto3" json:"vector_candidates,omitempty"`
	AfterFusion      uint32                 `protobuf:"varint,4,opt,name=after_fusion,json=afterFusion,proto3" json:"after_fusion,omitempty"`
	AfterRerank      uint32                 `protobuf:"varint,5,opt,name=after_rerank,json=afterRerank,proto3" json:"after_rerank,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_rag_engine_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_engine_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_rag_engine_proto_rawDescGZIP(), []int{14}
}

func (x *SearchResponse) GetHits() []*SearchHit {
	if x != nil {
		return x.Hits
	}
	return nil
}

func (x *SearchResponse) GetBm25Candidates() uint32 {
	if x != nil {
		return x.Bm25Candidates
	}
	return 0
}

func (x *SearchResponse) GetVectorCandidates() uint32 {
	if x != nil {
		return x.VectorCandidates
	}
	return 0
}

func (x *SearchResponse) GetAfterFusion() uint32 {
	if x != nil {
		return x.AfterFusion
	}
	return 0
}

func (x *SearchResponse) GetAfterRerank() uint32 {
	if x != nil {
		return x.AfterRerank
	}
	return 0
}

type SearchHit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	DocId         string                 `protobuf:"bytes,2,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	ChunkIndex    uint32                 `protobuf:"varint,3,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	Score         float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`                                // fused score post-rerank
	VectorScore   float64                `protobuf:"fixed64,5,opt,name=vector_score,json=vectorScore,proto3" json:"vector_score,omitempty"` // raw pre-fusion
	Bm25Score     float64                `protobuf:"fixed64,6,opt,name=bm25_score,json=bm25Score,proto3" json:"bm25_score,omitempty"`       // raw pre-fusion
	RerankScore   float64                `protobuf:"fixed64,7,opt,name=rerank_score,json=rerankScore,proto3" json:"rerank_score,omitempty"`
	Content       string                 `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	Blurb         string                 `protobuf:"bytes,9,opt,name=blurb,proto3" json:"blurb,omitempty"`
	DocUpdatedAt  *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=doc_updated_at,json=docUpdatedAt,proto3" json:"doc_updated_at,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,11,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchHit) Reset() {
	*x = SearchHit{}
	mi := &file_rag_engine_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHit) ProtoMessage() {}

func (x *SearchHit) ProtoReflect() protoreflect.Message {
	mi := &file_rag_engine_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHit.ProtoReflect.Descriptor instead.
func (*SearchHit) Descriptor() ([]byte, []int) {
	return file_rag_engine_proto_rawDescGZIP(), []int{15}
}

func (x *SearchHit) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *SearchHit) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *SearchHit) GetChunkIndex() uint32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *SearchHit) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SearchHit) GetVectorScore() float64 {
	if x != nil {
		return x.VectorScore
	}
	return 0
}

func (x *SearchHit) GetBm25Score() float64 {
	if x != nil {
		return x.Bm25Score
	}
	return 0
}

func (x *SearchHit) GetRerankScore() float64 {
	if x != nil {
		return x.RerankScore
	}
	return 0
}

func (x *SearchHit) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SearchHit) GetBlurb() string {
	if x != nil {
		return x.Blurb
	}
	return ""
}

func (x *SearchHit) GetDocUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DocUpdatedAt
	}
	return nil
}

func (x *SearchHit) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DeleteByDocIDRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DatasetName    string                 `protobuf:"bytes,1,opt,name=dataset_name,json=datasetName,proto3" json:"dataset_name,omitempty"`
	OrgId          string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	DocIds         []string               `protobuf:"bytes,3,rep,name=doc_ids,json=docIds,proto3" json:"doc_ids,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteByDocIDRequest) Reset() {
	*x = DeleteByDocIDRequest{}
	mi := &file_rag_engine_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteByDocIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteByDocIDRequest) ProtoMessage() {}

func (x *DeleteByDocIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_engine_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteByDocIDRequest.ProtoReflect.Descriptor instead.
func (*DeleteByDocIDRequest) Descriptor() ([]byte, []int) {
	return file_rag_engine_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteByDocIDRequest) GetDatasetName() string {
	if x != nil {
		return x.DatasetName
	}
	return ""
}

func (x *DeleteByDocIDRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *DeleteByDocIDRequest) GetDocIds() []string {
	if x != nil {
		return x.DocIds
	}
	return nil
}

func (x *DeleteByDocIDRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type DeleteByDocIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunksDeleted uint64                 `protobuf:"varint,1,opt,name=chunks_deleted,json=chunksDeleted,proto3" json:"chunks_deleted,omitempty"`
	DocsDeleted   uint64                 `protobuf:"varint,2,opt,name=docs_deleted,json=docsDeleted,proto3" json:"docs_deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteByDocIDResponse) Reset() {
	*x = DeleteByDocIDResponse{}
	mi := &file_rag_engine_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteByDocIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteByDocIDResponse) ProtoMessage() {}

func (x *DeleteByDocIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_engine_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteByDocIDResponse.ProtoReflect.Descriptor instead.
func (*DeleteByDocIDResponse) Descriptor() ([]byte, []int) {
	return file_rag_engine_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteByDocIDResponse) GetChunksDeleted() uint64 {
	if x != nil {
		return x.ChunksDeleted
	}
	return 0
}

func (x *DeleteByDocIDResponse) GetDocsDeleted() uint64 {
	if x != nil {
		return x.DocsDeleted
	}
	return 0
}

type DeleteByOrgRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrgId          string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	DatasetNames   []string               `protobuf:"bytes,2,rep,name=dataset_names,json=datasetNames,proto3" json:"dataset_names,omitempty"` // caller supplies ALL datasets this org has chunks in
	Confirm        bool                   `protobuf:"varint,3,opt,name=confirm,proto3" json:"confirm,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteByOrgRequest) Reset() {
	*x = DeleteByOrgRequest{}
	mi := &file_rag_engine_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteByOrgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteByOrgRequest) ProtoMessage() {}

func (x *DeleteByOrgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_engine_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteByOrgRequest.ProtoReflect.Descriptor instead.
func (*DeleteByOrgRequest) Descriptor() ([]byte, []int) {
	return file_rag_engine_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteByOrgRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *DeleteByOrgRequest) GetDatasetNames() []string {
	if x != nil {
		return x.DatasetNames
	}
	return nil
}

func (x *DeleteByOrgRequest) GetConfirm() bool {
	if x != nil {
		return x.Confirm
	}
	return false
}

func (x *DeleteByOrgRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type DeleteByOrgResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunksDeleted uint64                 `protobuf:"varint,1,opt,name=chunks_deleted,json=chunksDeleted,proto3" json:"chunks_deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteByOrgResponse) Reset() {
	*x = DeleteByOrgResponse{}
	mi := &file_rag_engine_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteByOrgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteByOrgResponse) ProtoMessage() {}

func (x *DeleteByOrgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_engine_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteByOrgResponse.ProtoReflect.Descriptor instead.
func (*DeleteByOrgResponse) Descriptor() ([]byte, []int) {
	return file_rag_engine_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteByOrgResponse) GetChunksDeleted() uint64 {
	if x != nil {
		return x.ChunksDeleted
	}
	return 0
}

type PruneRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	DatasetName string                 `protobuf:"bytes,1,opt,name=dataset_name,json=datasetName,proto3" json:"dataset_name,omitempty"`
	OrgId       string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	KeepDocIds  []string               `protobuf:"bytes,3,rep,name=keep_doc_ids,json=keepDocIds,proto3" json:"keep_doc_ids,omitempty"` // opposite polarity: delete docs NOT in this set
	// When keep_doc_ids is empty, server must refuse (safety).
	IdempotencyKey string `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PruneRequest) Reset() {
	*x = PruneRequest{}
	mi := &file_rag_engine_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PruneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PruneRequest) ProtoMessage() {}

func (x *PruneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_engine_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PruneRequest.ProtoReflect.Descriptor instead.
func (*PruneRequest) Descriptor() ([]byte, []int) {
	return file_rag_engine_proto_rawDescGZIP(), []int{20}
}

func (x *PruneRequest) GetDatasetName() string {
	if x != nil {
		return x.DatasetName
	}
	return ""
}

func (x *PruneRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *PruneRequest) GetKeepDocIds() []string {
	if x != nil {
		return x.KeepDocIds
	}
	return nil
}

func (x *PruneRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type PruneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocsPruned    uint64                 `protobuf:"varint,1,opt,name=docs_pruned,json=docsPruned,proto3" json:"docs_pruned,omitempty"`
	ChunksPruned  uint64                 `protobuf:"varint,2,opt,name=chunks_pruned,json=chunksPruned,proto3" json:"chunks_pruned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PruneResponse) Reset() {
	*x = PruneResponse{}
	mi := &file_rag_engine_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PruneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PruneResponse) ProtoMessage() {}

func (x *PruneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_engine_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PruneResponse.ProtoReflect.Descriptor instead.
func (*PruneResponse) Descriptor() ([]byte, []int) {
	return file_rag_engine_proto_rawDescGZIP(), []int{21}
}

func (x *PruneResponse) GetDocsPruned() uint64 {
	if x != nil {
		return x.DocsPruned
	}
	return 0
}

func (x *PruneResponse) GetChunksPruned() uint64 {
	if x != nil {
		return x.ChunksPruned
	}
	return 0
}

var File_rag_engine_proto protoreflect.FileDescriptor

const file_rag_engine_proto_rawDesc = "" +
	"\n" +
	"\x10rag_engine.proto\x12\x0fhiveloop.rag.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb2\x01\n" +
	"\x14CreateDatasetRequest\x12!\n" +
	"\fdataset_name\x18\x01 \x01(\tR\vdatasetName\x12\x1d\n" +
	"\n" +
	"vector_dim\x18\x02 \x01(\rR\tvectorDim\x12/\n" +
	"\x13embedding_precision\x18\x03 \x01(\tR\x12embeddingPrecision\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\"N\n" +
	"\x15CreateDatasetResponse\x12\x18\n" +
	"\acreated\x18\x01 \x01(\bR\acreated\x12\x1b\n" +
	"\tschema_ok\x18\x02 \x01(\bR\bschemaOk\"Q\n" +
	"\x12DropDatasetRequest\x12!\n" +
	"\fdataset_name\x18\x01 \x01(\tR\vdatasetName\x12\x18\n" +
	"\aconfirm\x18\x02 \x01(\bR\aconfirm\"/\n" +
	"\x13DropDatasetResponse\x12\x18\n" +
	"\adropped\x18\x01 \x01(\bR\adropped\"\x9c\x02\n" +
	"\x12IngestBatchRequest\x12!\n" +
	"\fdataset_name\x18\x01 \x01(\tR\vdatasetName\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x122\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x1e.hiveloop.rag.v1.IngestionModeR\x04mode\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\x12.\n" +
	"\x13declared_vector_dim\x18\x05 \x01(\rR\x11declaredVectorDim\x12?\n" +
	"\tdocuments\x18\x06 \x03(\v2!.hiveloop.rag.v1.DocumentToIngestR\tdocuments\"\xe1\x03\n" +
	"\x10DocumentToIngest\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\tR\x05docId\x12\x1f\n" +
	"\vsemantic_id\x18\x02 \x01(\tR\n" +
	"semanticId\x12\x12\n" +
	"\x04link\x18\x03 \x01(\tR\x04link\x12@\n" +
	"\x0edoc_updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\fdocUpdatedAt\x12\x10\n" +
	"\x03acl\x18\x05 \x03(\tR\x03acl\x12\x1b\n" +
	"\tis_public\x18\x06 \x01(\bR\bisPublic\x124\n" +
	"\bsections\x18\a \x03(\v2\x18.hiveloop.rag.v1.SectionR\bsections\x12K\n" +
	"\bmetadata\x18\b \x03(\v2/.hiveloop.rag.v1.DocumentToIngest.MetadataEntryR\bmetadata\x12%\n" +
	"\x0eprimary_owners\x18\t \x03(\tR\rprimaryOwners\x12)\n" +
	"\x10secondary_owners\x18\n" +
	" \x03(\tR\x0fsecondaryOwners\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"G\n" +
	"\aSection\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x12\n" +
	"\x04link\x18\x02 \x01(\tR\x04link\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\"\x86\x01\n" +
	"\x13IngestBatchResponse\x129\n" +
	"\aresults\x18\x01 \x03(\v2\x1f.hiveloop.rag.v1.DocumentResultR\aresults\x124\n" +
	"\x06totals\x18\x02 \x01(\v2\x1c.hiveloop.rag.v1.BatchTotalsR\x06totals\"\xf2\x01\n" +
	"\x0eDocumentResult\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\tR\x05docId\x127\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1f.hiveloop.rag.v1.DocumentStatusR\x06status\x12%\n" +
	"\x0echunks_written\x18\x03 \x01(\rR\rchunksWritten\x12'\n" +
	"\x0ftokens_embedded\x18\x04 \x01(\rR\x0etokensEmbedded\x12\x1d\n" +
	"\n" +
	"error_code\x18\x05 \x01(\tR\terrorCode\x12!\n" +
	"\ferror_reason\x18\x06 \x01(\tR\verrorReason\"\xf8\x02\n" +
	"\vBatchTotals\x12!\n" +
	"\frows_written\x18\x01 \x01(\x04R\vrowsWritten\x12#\n" +
	"\rbytes_written\x18\x02 \x01(\x04R\fbytesWritten\x12*\n" +
	"\x11batch_duration_ms\x18\x03 \x01(\rR\x0fbatchDurationMs\x12*\n" +
	"\x11chunk_duration_ms\x18\x04 \x01(\rR\x0fchunkDurationMs\x122\n" +
	"\x15embedding_duration_ms\x18\x05 \x01(\rR\x13embeddingDurationMs\x12*\n" +
	"\x11write_duration_ms\x18\x06 \x01(\rR\x0fwriteDurationMs\x12%\n" +
	"\x0edocs_succeeded\x18\a \x01(\rR\rdocsSucceeded\x12\x1f\n" +
	"\vdocs_failed\x18\b \x01(\rR\n" +
	"docsFailed\x12!\n" +
	"\fdocs_skipped\x18\t \x01(\rR\vdocsSkipped\"\xb0\x01\n" +
	"\x10UpdateACLRequest\x12!\n" +
	"\fdataset_name\x18\x01 \x01(\tR\vdatasetName\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x129\n" +
	"\aentries\x18\x03 \x03(\v2\x1f.hiveloop.rag.v1.UpdateACLEntryR\aentries\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\"V\n" +
	"\x0eUpdateACLEntry\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\tR\x05docId\x12\x10\n" +
	"\x03acl\x18\x02 \x03(\tR\x03acl\x12\x1b\n" +
	"\tis_public\x18\x03 \x01(\bR\bisPublic\"]\n" +
	"\x11UpdateACLResponse\x12!\n" +
	"\fdocs_updated\x18\x01 \x01(\x04R\vdocsUpdated\x12%\n" +
	"\x0echunks_updated\x18\x02 \x01(\x04R\rchunksUpdated\"\xed\x03\n" +
	"\rSearchRequest\x12!\n" +
	"\fdataset_name\x18\x01 \x01(\tR\vdatasetName\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12\x1d\n" +
	"\n" +
	"query_text\x18\x03 \x01(\tR\tqueryText\x12!\n" +
	"\fquery_vector\x18\x04 \x03(\x02R\vqueryVector\x12/\n" +
	"\x04mode\x18\x05 \x01(\x0e2\x1b.hiveloop.rag.v1.SearchModeR\x04mode\x12\x1c\n" +
	"\n" +
	"acl_any_of\x18\x06 \x03(\tR\baclAnyOf\x12%\n" +
	"\x0einclude_public\x18\a \x01(\bR\rincludePublic\x12\x14\n" +
	"\x05limit\x18\b \x01(\rR\x05limit\x12%\n" +
	"\x0ecandidate_pool\x18\t \x01(\rR\rcandidatePool\x12*\n" +
	"\x11custom_sql_filter\x18\n" +
	" \x01(\tR\x0fcustomSqlFilter\x12!\n" +
	"\fhybrid_alpha\x18\v \x01(\x01R\vhybridAlpha\x12\x16\n" +
	"\x06rerank\x18\f \x01(\bR\x06rerank\x12F\n" +
	"\x11doc_updated_after\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\x0fdocUpdatedAfter\"\xdc\x01\n" +
	"\x0eSearchResponse\x12.\n" +
	"\x04hits\x18\x01 \x03(\v2\x1a.hiveloop.rag.v1.SearchHitR\x04hits\x12'\n" +
	"\x0fbm25_candidates\x18\x02 \x01(\rR\x0ebm25Candidates\x12+\n" +
	"\x11vector_candidates\x18\x03 \x01(\rR\x10vectorCandidates\x12!\n" +
	"\fafter_fusion\x18\x04 \x01(\rR\vafterFusion\x12!\n" +
	"\fafter_rerank\x18\x05 \x01(\rR\vafterRerank\"\xce\x03\n" +
	"\tSearchHit\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x15\n" +
	"\x06doc_id\x18\x02 \x01(\tR\x05docId\x12\x1f\n" +
	"\vchunk_index\x18\x03 \x01(\rR\n" +
	"chunkIndex\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\x12!\n" +
	"\fvector_score\x18\x05 \x01(\x01R\vvectorScore\x12\x1d\n" +
	"\n" +
	"bm25_score\x18\x06 \x01(\x01R\tbm25Score\x12!\n" +
	"\frerank_score\x18\a \x01(\x01R\vrerankScore\x12\x18\n" +
	"\acontent\x18\b \x01(\tR\acontent\x12\x14\n" +
	"\x05blurb\x18\t \x01(\tR\x05blurb\x12@\n" +
	"\x0edoc_updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\fdocUpdatedAt\x12D\n" +
	"\bmetadata\x18\v \x03(\v2(.hiveloop.rag.v1.SearchHit.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x92\x01\n" +
	"\x14DeleteByDocIDRequest\x12!\n" +
	"\fdataset_name\x18\x01 \x01(\tR\vdatasetName\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12\x17\n" +
	"\adoc_ids\x18\x03 \x03(\tR\x06docIds\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\"a\n" +
	"\x15DeleteByDocIDResponse\x12%\n" +
	"\x0echunks_deleted\x18\x01 \x01(\x04R\rchunksDeleted\x12!\n" +
	"\fdocs_deleted\x18\x02 \x01(\x04R\vdocsDeleted\"\x93\x01\n" +
	"\x12DeleteByOrgRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12#\n" +
	"\rdataset_names\x18\x02 \x03(\tR\fdatasetNames\x12\x18\n" +
	"\aconfirm\x18\x03 \x01(\bR\aconfirm\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\"<\n" +
	"\x13DeleteByOrgResponse\x12%\n" +
	"\x0echunks_deleted\x18\x01 \x01(\x04R\rchunksDeleted\"\x93\x01\n" +
	"\fPruneRequest\x12!\n" +
	"\fdataset_name\x18\x01 \x01(\tR\vdatasetName\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12 \n" +
	"\fkeep_doc_ids\x18\x03 \x03(\tR\n" +
	"keepDocIds\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\"U\n" +
	"\rPruneResponse\x12\x1f\n" +
	"\vdocs_pruned\x18\x01 \x01(\x04R\n" +
	"docsPruned\x12#\n" +
	"\rchunks_pruned\x18\x02 \x01(\x04R\fchunksPruned*f\n" +
	"\rIngestionMode\x12\x1e\n" +
	"\x1aINGESTION_MODE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15INGESTION_MODE_UPSERT\x10\x01\x12\x1a\n" +
	"\x16INGESTION_MODE_REINDEX\x10\x02*\x87\x01\n" +
	"\x0eDocumentStatus\x12\x1f\n" +
	"\x1bDOCUMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17DOCUMENT_STATUS_SUCCESS\x10\x01\x12\x1a\n" +
	"\x16DOCUMENT_STATUS_FAILED\x10\x02\x12\x1b\n" +
	"\x17DOCUMENT_STATUS_SKIPPED\x10\x03*y\n" +
	"\n" +
	"SearchMode\x12\x1b\n" +
	"\x17SEARCH_MODE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SEARCH_MODE_HYBRID\x10\x01\x12\x1b\n" +
	"\x17SEARCH_MODE_VECTOR_ONLY\x10\x02\x12\x19\n" +
	"\x15SEARCH_MODE_BM25_ONLY\x10\x032\xc0\x05\n" +
	"\tRagEngine\x12^\n" +
	"\rCreateDataset\x12%.hiveloop.rag.v1.CreateDatasetRequest\x1a&.hiveloop.rag.v1.CreateDatasetResponse\x12X\n" +
	"\vDropDataset\x12#.hiveloop.rag.v1.DropDatasetRequest\x1a$.hiveloop.rag.v1.DropDatasetResponse\x12X\n" +
	"\vIngestBatch\x12#.hiveloop.rag.v1.IngestBatchRequest\x1a$.hiveloop.rag.v1.IngestBatchResponse\x12R\n" +
	"\tUpdateACL\x12!.hiveloop.rag.v1.UpdateACLRequest\x1a\".hiveloop.rag.v1.UpdateACLResponse\x12I\n" +
	"\x06Search\x12\x1e.hiveloop.rag.v1.SearchRequest\x1a\x1f.hiveloop.rag.v1.SearchResponse\x12^\n" +
	"\rDeleteByDocID\x12%.hiveloop.rag.v1.DeleteByDocIDRequest\x1a&.hiveloop.rag.v1.DeleteByDocIDResponse\x12X\n" +
	"\vDeleteByOrg\x12#.hiveloop.rag.v1.DeleteByOrgRequest\x1a$.hiveloop.rag.v1.DeleteByOrgResponse\x12F\n" +
	"\x05Prune\x12\x1d.hiveloop.rag.v1.PruneRequest\x1a\x1e.hiveloop.rag.v1.PruneResponseB4Z2github.com/usehiveloop/hiveloop/internal/rag/ragpbb\x06proto3"

var (
	file_rag_engine_proto_rawDescOnce sync.Once
	file_rag_engine_proto_rawDescData []byte
)

func file_rag_engine_proto_rawDescGZIP() []byte {
	file_rag_engine_proto_rawDescOnce.Do(func() {
		file_rag_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rag_engine_proto_rawDesc), len(file_rag_engine_proto_rawDesc)))
	})
	return file_rag_engine_proto_rawDescData
}

var file_rag_engine_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_rag_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_rag_engine_proto_goTypes = []any{
	(IngestionMode)(0),            // 0: hiveloop.rag.v1.IngestionMode
	(DocumentStatus)(0),           // 1: hiveloop.rag.v1.DocumentStatus
	(SearchMode)(0),               // 2: hiveloop.rag.v1.SearchMode
	(*CreateDatasetRequest)(nil),  // 3: hiveloop.rag.v1.CreateDatasetRequest
	(*CreateDatasetResponse)(nil), // 4: hiveloop.rag.v1.CreateDatasetResponse
	(*DropDatasetRequest)(nil),    // 5: hiveloop.rag.v1.DropDatasetRequest
	(*DropDatasetResponse)(nil),   // 6: hiveloop.rag.v1.DropDatasetResponse
	(*IngestBatchRequest)(nil),    // 7: hiveloop.rag.v1.IngestBatchRequest
	(*DocumentToIngest)(nil),      // 8: hiveloop.rag.v1.DocumentToIngest
	(*Section)(nil),               // 9: hiveloop.rag.v1.Section
	(*IngestBatchResponse)(nil),   // 10: hiveloop.rag.v1.IngestBatchResponse
	(*DocumentResult)(nil),        // 11: hiveloop.rag.v1.DocumentResult
	(*BatchTotals)(nil),           // 12: hiveloop.rag.v1.BatchTotals
	(*UpdateACLRequest)(nil),      // 13: hiveloop.rag.v1.UpdateACLRequest
	(*UpdateACLEntry)(nil),        // 14: hiveloop.rag.v1.UpdateACLEntry
	(*UpdateACLResponse)(nil),     // 15: hiveloop.rag.v1.UpdateACLResponse
	(*SearchRequest)(nil),         // 16: hiveloop.rag.v1.SearchRequest
	(*SearchResponse)(nil),        // 17: hiveloop.rag.v1.SearchResponse
	(*SearchHit)(nil),             // 18: hiveloop.rag.v1.SearchHit
	(*DeleteByDocIDRequest)(nil),  // 19: hiveloop.rag.v1.DeleteByDocIDRequest
	(*DeleteByDocIDResponse)(nil), // 20: hiveloop.rag.v1.DeleteByDocIDResponse
	(*DeleteByOrgRequest)(nil),    // 21: hiveloop.rag.v1.DeleteByOrgRequest
	(*DeleteByOrgResponse)(nil),   // 22: hiveloop.rag.v1.DeleteByOrgResponse
	(*PruneRequest)(nil),          // 23: hiveloop.rag.v1.PruneRequest
	(*PruneResponse)(nil),         // 24: hiveloop.rag.v1.PruneResponse
	nil,                           // 25: hiveloop.rag.v1.DocumentToIngest.MetadataEntry
	nil,                           // 26: hiveloop.rag.v1.SearchHit.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 27: google.protobuf.Timestamp
}
var file_rag_engine_proto_depIdxs = []int32{
	0,  // 0: hiveloop.rag.v1.IngestBatchRequest.mode:type_name -> hiveloop.rag.v1.IngestionMode
	8,  // 1: hiveloop.rag.v1.IngestBatchRequest.documents:type_name -> hiveloop.rag.v1.DocumentToIngest
	27, // 2: hiveloop.rag.v1.DocumentToIngest.doc_updated_at:type_name -> google.protobuf.Timestamp
	9,  // 3: hiveloop.rag.v1.DocumentToIngest.sections:type_name -> hiveloop.rag.v1.Section
	25, // 4: hiveloop.rag.v1.DocumentToIngest.metadata:type_name -> hiveloop.rag.v1.DocumentToIngest.MetadataEntry
	11, // 5: hiveloop.rag.v1.IngestBatchResponse.results:type_name -> hiveloop.rag.v1.DocumentResult
	12, // 6: hiveloop.rag.v1.IngestBatchResponse.totals:type_name -> hiveloop.rag.v1.BatchTotals
	1,  // 7: hiveloop.rag.v1.DocumentResult.status:type_name -> hiveloop.rag.v1.DocumentStatus
	14, // 8: hiveloop.rag.v1.UpdateACLRequest.entries:type_name -> hiveloop.rag.v1.UpdateACLEntry
	2,  // 9: hiveloop.rag.v1.SearchRequest.mode:type_name -> hiveloop.rag.v1.SearchMode
	27, // 10: hiveloop.rag.v1.SearchRequest.doc_updated_after:type_name -> google.protobuf.Timestamp
	18, // 11: hiveloop.rag.v1.SearchResponse.hits:type_name -> hiveloop.rag.v1.SearchHit
	27, // 12: hiveloop.rag.v1.SearchHit.doc_updated_at:type_name -> google.protobuf.Timestamp
	26, // 13: hiveloop.rag.v1.SearchHit.metadata:type_name -> hiveloop.rag.v1.SearchHit.MetadataEntry
	3,  // 14: hiveloop.rag.v1.RagEngine.CreateDataset:input_type -> hiveloop.rag.v1.CreateDatasetRequest
	5,  // 15: hiveloop.rag.v1.RagEngine.DropDataset:input_type -> hiveloop.rag.v1.DropDatasetRequest
	7,  // 16: hiveloop.rag.v1.RagEngine.IngestBatch:input_type -> hiveloop.rag.v1.IngestBatchRequest
	13, // 17: hiveloop.rag.v1.RagEngine.UpdateACL:input_type -> hiveloop.rag.v1.UpdateACLRequest
	16, // 18: hiveloop.rag.v1.RagEngine.Search:input_type -> hiveloop.rag.v1.SearchRequest
	19, // 19: hiveloop.rag.v1.RagEngine.DeleteByDocID:input_type -> hiveloop.rag.v1.DeleteByDocIDRequest
	21, // 20: hiveloop.rag.v1.RagEngine.DeleteByOrg:input_type -> hiveloop.rag.v1.DeleteByOrgRequest
	23, // 21: hiveloop.rag.v1.RagEngine.Prune:input_type -> hiveloop.rag.v1.PruneRequest
	4,  // 22: hiveloop.rag.v1.RagEngine.CreateDataset:output_type -> hiveloop.rag.v1.CreateDatasetResponse
	6,  // 23: hiveloop.rag.v1.RagEngine.DropDataset:output_type -> hiveloop.rag.v1.DropDatasetResponse
	10, // 24: hiveloop.rag.v1.RagEngine.IngestBatch:output_type -> hiveloop.rag.v1.IngestBatchResponse
	15, // 25: hiveloop.rag.v1.RagEngine.UpdateACL:output_type -> hiveloop.rag.v1.UpdateACLResponse
	17, // 26: hiveloop.rag.v1.RagEngine.Search:output_type -> hiveloop.rag.v1.SearchResponse
	20, // 27: hiveloop.rag.v1.RagEngine.DeleteByDocID:output_type -> hiveloop.rag.v1.DeleteByDocIDResponse
	22, // 28: hiveloop.rag.v1.RagEngine.DeleteByOrg:output_type -> hiveloop.rag.v1.DeleteByOrgResponse
	24, // 29: hiveloop.rag.v1.RagEngine.Prune:output_type -> hiveloop.rag.v1.PruneResponse
	22, // [22:30] is the sub-list for method output_type
	14, // [14:22] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_rag_engine_proto_init() }
func file_rag_engine_proto_init() {
	if File_rag_engine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rag_engine_proto_rawDesc), len(file_rag_engine_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rag_engine_proto_goTypes,
		DependencyIndexes: file_rag_engine_proto_depIdxs,
		EnumInfos:         file_rag_engine_proto_enumTypes,
		MessageInfos:      file_rag_engine_proto_msgTypes,
	}.Build()
	File_rag_engine_proto = out.File
	file_rag_engine_proto_goTypes = nil
	file_rag_engine_proto_depIdxs = nil
}
