agent:
    max_turns: 180
custom_providers:
    - api_key: ptok_eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvcmdfaWQiOiJhMTNlNmFkNi1mMzEwLTQzYTQtOTQyNS1kMDkyZDIyZmRjMjQiLCJjcmVkX2lkIjoiODk0OWFjNTQtOTU5Ni00YzMwLWJkYTItOTg4MzNhODhiNDg4IiwiaXNfc3lzdGVtIjp0cnVlLCJleHAiOjE3NzgyNjIyMDcsImlhdCI6MTc3ODE3NTgwNywianRpIjoiNzYyM2U5NDYtMzYzMS00NDU5LThjYWUtMzdiMWU5YWVkZDJmIn0.pwWrpbWYQC3Tej39wBKpKhbTBkJ4EQCy5pLXbw51GPo
      base_url: https://proxy.usehiveloop.com/v1
      name: hiveloop-proxy
hindsight:
    bank_id: bank-a13e6ad6-f310-43a4-9425-d092d22fdc24
mcp_servers:
    hiveloop:
        headers:
            Authorization: Bearer ptok_eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvcmdfaWQiOiJhMTNlNmFkNi1mMzEwLTQzYTQtOTQyNS1kMDkyZDIyZmRjMjQiLCJjcmVkX2lkIjoiODk0OWFjNTQtOTU5Ni00YzMwLWJkYTItOTg4MzNhODhiNDg4IiwiaXNfc3lzdGVtIjp0cnVlLCJleHAiOjE3NzgyNjIyMDcsImlhdCI6MTc3ODE3NTgwNywianRpIjoiNzYyM2U5NDYtMzYzMS00NDU5LThjYWUtMzdiMWU5YWVkZDJmIn0.pwWrpbWYQC3Tej39wBKpKhbTBkJ4EQCy5pLXbw51GPo
        transport: streamable_http
        url: https://mcp.usehiveloop.com/7623e946-3631-4459-8cae-37b1e9aedd2f
memory:
    memory_char_limit: 2200
    memory_enabled: true
    nudge_interval: 0
    provider: hindsight
    user_char_limit: 1375
    user_profile_enabled: true
model:
    api_key: ptok_eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvcmdfaWQiOiJhMTNlNmFkNi1mMzEwLTQzYTQtOTQyNS1kMDkyZDIyZmRjMjQiLCJjcmVkX2lkIjoiODk0OWFjNTQtOTU5Ni00YzMwLWJkYTItOTg4MzNhODhiNDg4IiwiaXNfc3lzdGVtIjp0cnVlLCJleHAiOjE3NzgyNjIyMDcsImlhdCI6MTc3ODE3NTgwNywianRpIjoiNzYyM2U5NDYtMzYzMS00NDU5LThjYWUtMzdiMWU5YWVkZDJmIn0.pwWrpbWYQC3Tej39wBKpKhbTBkJ4EQCy5pLXbw51GPo
    base_url: https://proxy.usehiveloop.com/v1
    default: deepseek-v4-pro-precision
    provider: custom
platform_toolsets:
    api_server:
        - terminal
        - file
        - skills
        - todo
        - memory
        - session_search
        - vision
        - cronjob
terminal:
    backend: local