#!/usr/bin/env bash
set -euo pipefail

if [[ -f .env && "${CI:-}" != "true" && "${CI_OVERWRITE_ENV:-}" != "1" ]]; then
  echo ".env already exists; set CI_OVERWRITE_ENV=1 to overwrite it for CI simulation" >&2
  exit 1
fi

rand_b64() {
  openssl rand -base64 32 | tr -d '\n'
}

rsa_b64() {
  openssl genrsa 2048 2>/dev/null | base64 | tr -d '\n'
}

cat > .env <<EOF
HIVY_COMPOSE_API_PORT=8080
HIVY_COMPOSE_MCP_PORT=8081
HIVY_COMPOSE_WEB_PORT=30112
HIVY_COMPOSE_WORKER_HEALTH_PORT=8090
HIVY_COMPOSE_POSTGRES_PORT=5433
HIVY_COMPOSE_REDIS_PORT=16279
HIVY_COMPOSE_NANGO_PORT=23003
HIVY_COMPOSE_QDRANT_HTTP_PORT=6333
HIVY_COMPOSE_QDRANT_GRPC_PORT=6334
HIVY_COMPOSE_HINDSIGHT_API_PORT=8888
HIVY_COMPOSE_HINDSIGHT_IMAGE=ghcr.io/vectorize-io/hindsight:latest-slim

HIVY_ENVIRONMENT=development
HIVY_PORT=8080
HIVY_LOG_LEVEL=info
HIVY_LOG_FORMAT=json
HIVY_FRONTEND_URL=http://localhost:30112
HIVY_CORS_ORIGINS=http://localhost:30112
HIVY_MCP_PORT=8081
HIVY_MCP_BASE_URL=http://host.docker.internal:8081
HIVY_API_WEBHOOK_BASE_URL=http://host.docker.internal:8080
HIVY_PROXY_HOST=http://host.docker.internal:8080
HIVY_AUTO_CONFIRM_EMAIL=true
HIVY_PLATFORM_ADMIN_EMAILS=agent-test@example.com

HIVY_SESSION_SECRET=$(rand_b64)
HIVY_JWT_SIGNING_KEY=local-ci-signing-key
HIVY_AUTH_RSA_PRIVATE_KEY=$(rsa_b64)
HIVY_AUTH_ISSUER=hivy
HIVY_AUTH_AUDIENCE=http://localhost:8080
HIVY_AUTH_ACCESS_TOKEN_TTL=15m
HIVY_AUTH_REFRESH_TOKEN_TTL=720h

HIVY_KMS_TYPE=aead
HIVY_KMS_KEY=$(rand_b64)
HIVY_AWS_REGION=us-east-1

HIVY_DATABASE_URL=postgres://hivy:localdev@postgres:5432/hivy?sslmode=disable
HIVY_DB_HOST=postgres
HIVY_DB_PORT=5432
HIVY_DB_USER=hivy
HIVY_DB_PASSWORD=localdev
HIVY_DB_NAME=hivy
HIVY_DB_SSLMODE=disable

HIVY_REDIS_ADDR=redis:6379
HIVY_REDIS_DB=0
HIVY_REDIS_CACHE_TTL=30m
HIVY_MEM_CACHE_TTL=5m
HIVY_MEM_CACHE_MAX_SIZE=10000
HIVY_ASYNQ_CONCURRENCY=30
HIVY_ASYNQ_SHUTDOWN_TIMEOUT=120s
HIVY_WORKER_HEALTH_PORT=8090

HIVY_NANGO_ENDPOINT=http://nango:3003
HIVY_NANGO_PUBLIC_URL=http://localhost:23003
HIVY_NANGO_SECRET_KEY=00000000-0000-4000-8000-000000000001
HIVY_NANGO_ENCRYPTION_KEY=$(rand_b64)
HIVY_NANGO_DASHBOARD_USERNAME=local
HIVY_NANGO_DASHBOARD_PASSWORD=local

HIVY_SANDBOX_PROVIDER_ID=docker
HIVY_SANDBOX_ENCRYPTION_KEY=$(rand_b64)
HIVY_SANDBOX_RESOURCE_CHECK_INTERVAL=30m
HIVY_SPECIALIST_SANDBOX_RUNTIME_VERSION=v1.0.3
HIVY_SPECIALIST_SANDBOX_GRACE_PERIOD_MINS=5
HIVY_SANDBOXES_RUNTIME_BASE_IMAGE_PREFIX=ghcr.io/usehivy/hivy-sandboxes-runtime:latest
HIVY_SANDBOXES_RUNTIME_SPECIALIST_IMAGE_PREFIX=ghcr.io/usehivy/hivy-sandboxes-runtime-specialist:latest
HIVY_EMPLOYEE_SQLITE_BACKUP_MAX_BYTES=5368709120
HIVY_SANDBOX_DOCKER_HOST=unix:///var/run/docker.sock
HIVY_SANDBOX_DOCKER_PUBLIC_HOST=host.docker.internal

HIVY_AWS_ACCESS_KEY_ID=minioadmin
HIVY_AWS_SECRET_ACCESS_KEY=minioadmin
HIVY_AWS_ENDPOINT_URL=http://minio:9000
HIVY_AWS_PRESIGN_ENDPOINT_URL=http://host.docker.internal:9000
HIVY_PUBLIC_ASSETS_S3_BUCKET=public-files-test
HIVY_PUBLIC_ASSETS_S3_REGION=us-east-1
HIVY_PUBLIC_ASSETS_S3_ENDPOINT=http://minio:9000
HIVY_PUBLIC_ASSETS_BASE_URL=http://localhost:9000/public-files-test

HIVY_QDRANT_HOST=qdrant
HIVY_QDRANT_PORT=6334
HIVY_QDRANT_USE_TLS=false

HINDSIGHT_API_EMBEDDINGS_LOCAL_FORCE_CPU=true
HINDSIGHT_API_EMBEDDINGS_PROVIDER=local
HINDSIGHT_API_EMBEDDINGS_OPENAI_API_KEY=dummy
HINDSIGHT_API_EMBEDDINGS_OPENAI_MODEL=text-embedding-3-small
HINDSIGHT_API_HOST=0.0.0.0
HINDSIGHT_API_LLM_PROVIDER=none
HINDSIGHT_API_LLM_BASE_URL=http://localhost
HINDSIGHT_API_LLM_API_KEY=dummy
HINDSIGHT_API_LLM_MODEL=openai/gpt-oss-20b
HINDSIGHT_API_CONSOLIDATION_LLM_PROVIDER=none
HINDSIGHT_API_CONSOLIDATION_LLM_API_KEY=dummy
HINDSIGHT_API_CONSOLIDATION_LLM_MODEL=openai/gpt-oss-20b
HINDSIGHT_API_REFLECT_LLM_PROVIDER=none
HINDSIGHT_API_REFLECT_LLM_API_KEY=dummy
HINDSIGHT_API_REFLECT_LLM_MODEL=openai/gpt-oss-20b
HINDSIGHT_API_RETAIN_LLM_PROVIDER=none
HINDSIGHT_API_RETAIN_LLM_API_KEY=dummy
HINDSIGHT_API_RETAIN_LLM_MODEL=openai/gpt-oss-20b
HINDSIGHT_API_LOG_FORMAT=json
HINDSIGHT_API_LOG_LEVEL=info
HINDSIGHT_API_PORT=8888
HINDSIGHT_API_RERANKER_PROVIDER=rrf
HINDSIGHT_API_RERANKER_ZEROENTROPY_API_KEY=dummy
HINDSIGHT_API_RERANKER_ZEROENTROPY_MODEL=zerank-2
HINDSIGHT_API_RUN_MIGRATIONS_ON_STARTUP=true
HINDSIGHT_API_WORKERS=1
HINDSIGHT_API_WORKER_ENABLED=false
EOF

echo "wrote CI .env"
