//! Generated gRPC bindings for the Hiveloop `rag-engine` service.
//!
//! Both server (`rag_engine_server::RagEngine` trait, `RagEngineServer`)
//! and client (`rag_engine_client::RagEngineClient`) stubs are emitted.
//!
//! Source of truth: `<repo>/proto/rag_engine.proto`. Do NOT edit generated
//! code; edit the .proto and rebuild.

// Silence lints on generated code — we don't own its style.
#![allow(clippy::all)]
#![allow(clippy::pedantic)]
#![allow(missing_docs)]
#![allow(rustdoc::broken_intra_doc_links)]

/// The `hiveloop.rag.v1` package. Contains `RagEngine` service, requests,
/// responses, and enums. Generated by `tonic-build` at compile time.
pub mod v1 {
    tonic::include_proto!("hiveloop.rag.v1");
}

// Convenience re-exports so downstream crates write
// `rag_engine_proto::rag_engine_server::RagEngine` instead of threading
// the `v1` module everywhere.
pub use v1::rag_engine_client;
pub use v1::rag_engine_server;

// Re-export every message + enum at crate root for ergonomic use.
pub use v1::*;
