import type { SkillPreview } from "./types"

// Static sample data for the skills step. Replace with an $api.useInfiniteQuery
// call against GET /v1/skills once the backend gains the `q` search parameter.
export const MOCK_SKILLS: SkillPreview[] = [
  {
    id: "skill-01",
    slug: "triage-github-issues",
    name: "Triage GitHub Issues",
    description:
      "Classify, label, and prioritise incoming GitHub issues using your team's conventions.",
    sourceType: "git",
    scope: "public",
    tags: ["github", "triage", "issues"],
    installCount: 1284,
    featured: true,
  },
  {
    id: "skill-02",
    slug: "write-clear-release-notes",
    name: "Write clear release notes",
    description:
      "Turn a list of merged PRs into human-readable release notes with semantic sections.",
    sourceType: "inline",
    scope: "public",
    tags: ["writing", "release"],
    installCount: 842,
    featured: true,
  },
  {
    id: "skill-03",
    slug: "postgres-query-review",
    name: "Postgres query review",
    description:
      "Review SQL queries for performance, missing indexes, and common pitfalls before they ship.",
    sourceType: "git",
    scope: "public",
    tags: ["sql", "postgres", "performance"],
    installCount: 612,
    featured: false,
  },
  {
    id: "skill-04",
    slug: "secure-code-audit",
    name: "Secure code audit",
    description:
      "Walk through a diff and flag OWASP-class vulnerabilities with concrete remediation steps.",
    sourceType: "git",
    scope: "public",
    tags: ["security", "audit"],
    installCount: 1502,
    featured: true,
  },
  {
    id: "skill-05",
    slug: "summarise-slack-thread",
    name: "Summarise Slack thread",
    description:
      "Produce a TL;DR of a long Slack thread with action items and open questions.",
    sourceType: "inline",
    scope: "public",
    tags: ["slack", "writing"],
    installCount: 398,
    featured: false,
  },
  {
    id: "skill-06",
    slug: "internal-incident-playbook",
    name: "Incident response playbook",
    description:
      "Our org's incident flow: page on-call, open war room, assign scribe, draft public status update.",
    sourceType: "inline",
    scope: "org",
    tags: ["ops", "incident"],
    installCount: 12,
    featured: false,
  },
  {
    id: "skill-07",
    slug: "customer-email-voice",
    name: "Customer email voice",
    description:
      "Rewrite customer emails in the Ziraloop house voice — warm, technical, never fluffy.",
    sourceType: "inline",
    scope: "org",
    tags: ["writing", "support"],
    installCount: 7,
    featured: false,
  },
  {
    id: "skill-08",
    slug: "explain-migration-impact",
    name: "Explain migration impact",
    description:
      "Given a DB migration, describe the rollout risks, blast radius, and rollback procedure.",
    sourceType: "git",
    scope: "public",
    tags: ["db", "migration"],
    installCount: 221,
    featured: false,
  },
  {
    id: "skill-09",
    slug: "jira-ticket-breakdown",
    name: "Jira ticket breakdown",
    description:
      "Decompose a high-level Jira epic into implementation tickets with acceptance criteria.",
    sourceType: "git",
    scope: "public",
    tags: ["jira", "planning"],
    installCount: 487,
    featured: false,
  },
  {
    id: "skill-10",
    slug: "cron-sanity-check",
    name: "Cron sanity check",
    description:
      "Validate cron expressions, surface overlap windows, and warn on common scheduling mistakes.",
    sourceType: "git",
    scope: "public",
    tags: ["ops", "scheduling"],
    installCount: 158,
    featured: false,
  },
  {
    id: "skill-11",
    slug: "refactor-to-hooks",
    name: "Refactor to React hooks",
    description:
      "Convert class components to functional components with idiomatic hook usage.",
    sourceType: "inline",
    scope: "public",
    tags: ["react", "refactor"],
    installCount: 311,
    featured: false,
  },
  {
    id: "skill-12",
    slug: "typed-api-wrapper",
    name: "Typed API wrapper",
    description:
      "Generate strongly-typed TypeScript clients from an OpenAPI spec with reasonable defaults.",
    sourceType: "git",
    scope: "public",
    tags: ["typescript", "api"],
    installCount: 766,
    featured: true,
  },
  {
    id: "skill-13",
    slug: "rca-writeup",
    name: "Root cause analysis writeup",
    description:
      "Turn an incident timeline into a blameless RCA with timeline, contributing factors, and follow-ups.",
    sourceType: "inline",
    scope: "public",
    tags: ["ops", "writing"],
    installCount: 232,
    featured: false,
  },
  {
    id: "skill-14",
    slug: "k8s-deployment-review",
    name: "Kubernetes deployment review",
    description:
      "Review k8s manifests for resource limits, probes, and security context misconfigurations.",
    sourceType: "git",
    scope: "public",
    tags: ["kubernetes", "review"],
    installCount: 544,
    featured: false,
  },
  {
    id: "skill-15",
    slug: "ziraloop-style-guide",
    name: "Ziraloop style guide",
    description:
      "Internal conventions for Go handlers, React components, and OpenAPI annotations.",
    sourceType: "inline",
    scope: "org",
    tags: ["style"],
    installCount: 4,
    featured: false,
  },
  {
    id: "skill-16",
    slug: "launch-readiness-check",
    name: "Launch readiness check",
    description:
      "Pre-launch checklist: telemetry, rollback plan, on-call rota, feature flag state, support brief.",
    sourceType: "inline",
    scope: "org",
    tags: ["launch", "ops"],
    installCount: 3,
    featured: false,
  },
  {
    id: "skill-17",
    slug: "explain-tsc-errors",
    name: "Explain TypeScript errors",
    description:
      "Translate cryptic TS2345-style errors into plain English with concrete fixes.",
    sourceType: "git",
    scope: "public",
    tags: ["typescript"],
    installCount: 189,
    featured: false,
  },
  {
    id: "skill-18",
    slug: "a11y-quickscan",
    name: "Accessibility quickscan",
    description:
      "Scan JSX for missing alt text, unlabeled inputs, and contrast issues — surface fixes.",
    sourceType: "git",
    scope: "public",
    tags: ["a11y", "frontend"],
    installCount: 271,
    featured: false,
  },
  {
    id: "skill-19",
    slug: "pr-reviewer-persona",
    name: "PR reviewer persona",
    description:
      "Review a pull request as a senior engineer would — focusing on intent, tests, and long-term maintainability.",
    sourceType: "inline",
    scope: "public",
    tags: ["review", "pr"],
    installCount: 1034,
    featured: true,
  },
  {
    id: "skill-20",
    slug: "dockerfile-hardening",
    name: "Dockerfile hardening",
    description:
      "Audit Dockerfiles for pinned base images, non-root users, minimal layers, and secret leakage.",
    sourceType: "git",
    scope: "public",
    tags: ["docker", "security"],
    installCount: 332,
    featured: false,
  },
]
